// ─────────────────────────────────────────────────────────────
// TREE 3: LIBERAL OPEN ECONOMY — 35 MISSIONS, 5 TIERS
// ─────────────────────────────────────────────────────────────

const LIBERAL_MISSIONS = [
  // ══════════════ TIER 1 — MARKET FOUNDATIONS (7 missions) ══════════════

  {
    id: 'lib_t1_deregulation',
    treeId: 'liberal_open_economy',
    tier: 1,
    category: 'institutional',
    icon: '✂️',
    name: 'Business Deregulation Act',
    description: 'Cut red tape: streamline business registration to one day, remove price controls on non-essential goods, reduce licence requirements from 15 to 3 for small business. Require every ministry to cut regulatory burden by 30% within 12 months.',
    durationMonths: 9,
    prerequisiteIds: [],
    requirements: {
      description: 'Low tax policy and passed the Business Deregulation Act.',
      requiredPolicy: { taxRate: 'low' },
      requiredPassedLaws: ['business_deregulation_act'],
    },
    reward: {
      gdpBonus: 0.45,
      unemploymentBonus: 0.4,
      approvalBonus: 3,
      legacyPoints: 2,
      structuralBonus: { corruptionReduction: 5 },
      flavourText: 'Entrepreneurs no longer need seven stamps to open a shop. The informal sector begins its journey toward formality. Business formation rates triple in the first year.',
      historicalNote: 'Malaysia\'s ease of doing business ranking improved dramatically under deregulation. By 2020 it ranked 12th globally in the World Bank Ease of Doing Business Index, above Germany and Switzerland.',
    },
  },

  {
    id: 'lib_t1_free_trade',
    treeId: 'liberal_open_economy',
    tier: 1,
    category: 'external',
    icon: '🌐',
    name: 'Free Trade Agreements Drive',
    description: 'Aggressively pursue bilateral free trade agreements with the US, Japan, Australia, and India. Reduce average tariffs to under 5% across all manufactured goods. Establish a Trade Facilitation Council to resolve non-tariff barriers within 60 days.',
    durationMonths: 14,
    prerequisiteIds: [],
    requirements: {
      description: 'Open trade policy.',
      requiredPolicy: { openTrade: true },
    },
    reward: {
      gdpBonus: 0.85,
      inflationModifier: -0.45,
      budgetBonus: 65,
      legacyPoints: 4,
      crossTreeSynergies: [
        {
          beneficiaryTree: 'export_tiger',
          targetMissionId: 'tiger_t2_asean_integration',
          requirementReduction: 0.2,
          description: 'Bilateral FTAs build the diplomatic foundation for ASEAN integration.',
        },
      ],
      flavourText: 'Malaysian rubber and electronics flow to new markets. Free trade exposes uncompetitive domestic sectors to the discipline of the market — and the political challenge of explaining why protection was hiding inefficiency.',
      historicalNote: 'Malaysia signed FTAs with Japan (2006), Australia (2012), and participated in CPTPP (2018). TPP negotiations with the US collapsed with Trump\'s withdrawal in 2017.',
    },
  },

  {
    id: 'lib_t1_stock_exchange',
    treeId: 'liberal_open_economy',
    tier: 1,
    category: 'economic',
    icon: '📈',
    name: 'Bursa Malaysia Development',
    description: 'Strengthen the Securities Commission, introduce international disclosure standards, require independent audit committees for all listed companies. Develop the corporate bond market and establish Malaysia as the global centre for sukuk issuance.',
    durationMonths: 12,
    prerequisiteIds: [],
    requirements: {
      description: 'Low corruption for credible regulation.',
      maxCorruption: 50,
    },
    reward: {
      budgetBonus: 45,
      legacyPoints: 3,
      structuralBonus: { corruptionReduction: 6, humanCapitalBoost: 3 },
      policyUnlock: {
        description: 'Unlocks "Capital Market Development" financing option',
        unlockedOptions: { welfareLevel: ['capital_market'] },
      },
      flavourText: 'Public listings bring accountability — in theory. Bursa Malaysia becomes a barometer of market confidence in government policy. On bad days, the index is the most honest commentary on the news.',
      historicalNote: 'The KLSE (now Bursa Malaysia) was established 1964. Market capitalisation exceeded 100% of GDP by 2007. Malaysia became the world\'s largest sukuk market, an unexpected competitive advantage.',
    },
  },

  {
    id: 'lib_t1_competition_law',
    treeId: 'liberal_open_economy',
    tier: 1,
    category: 'institutional',
    icon: '⚖️',
    name: 'Competition Act and Commission',
    description: 'Enact a comprehensive Competition Act modelled on EU competition law. Establish the Malaysia Competition Commission (MyCC) with powers to fine companies up to 10% of global turnover. Apply competition law to GLCs as well as private companies.',
    durationMonths: 14,
    prerequisiteIds: ['lib_t1_deregulation'],
    requirements: {
      description: 'Low corruption and functional institutions.',
      maxCorruption: 45,
      minApproval: 38,
    },
    reward: {
      gdpBonus: 0.5,
      legacyPoints: 3,
      structuralBonus: { corruptionReduction: 7, humanCapitalBoost: 2 },
      crossTreeSynergies: [
        {
          beneficiaryTree: 'federal_pluralism',
          targetMissionId: 'fed_t1_judiciary_independence',
          requirementReduction: 0.15,
          description: 'Competition law creates new grounds for independent judicial review of state economic decisions.',
        },
      ],
      flavourText: 'Malaysia acquires the legal toolkit to prevent monopolistic abuse. The first test of MyCC\'s independence will come when it investigates a GLC. Whether it does determines everything about its credibility.',
    },
  },

  {
    id: 'lib_t1_property_rights',
    treeId: 'liberal_open_economy',
    tier: 1,
    category: 'institutional',
    icon: '🏠',
    name: 'Property Rights Protection',
    description: 'Amend the National Land Code to provide stronger protection against arbitrary acquisition. Reform LADA and state land authorities. Establish a Fast Track Land Court to resolve property disputes within 12 months. Introduce a Property Ombudsman.',
    durationMonths: 11,
    prerequisiteIds: [],
    requirements: {
      description: 'Functioning legal institutions.',
      maxCorruption: 52,
    },
    reward: {
      gdpBonus: 0.4,
      legacyPoints: 2,
      structuralBonus: { corruptionReduction: 4, humanCapitalBoost: 2 },
      policyUnlock: {
        description: 'Unlocks "Foreign Property Investment" visa and investment option',
        unlockedOptions: {},
      },
      flavourText: 'Investors receive the one thing they value most: predictability. The rule of law applied to property markets has an outsized economic return. The property rights Malaysia offers are now worth something.',
    },
  },

  {
    id: 'lib_t1_tax_reform',
    treeId: 'liberal_open_economy',
    tier: 1,
    category: 'economic',
    icon: '💸',
    name: 'Tax Code Simplification',
    description: 'Replace the old Corporate Income Tax with a simplified, flat 17% rate for SMEs. Introduce GST (Goods and Services Tax) as a broad-based consumption tax, replacing distortionary sector-specific levies. Strengthen LHDN\'s audit capability to close loopholes.',
    durationMonths: 16,
    prerequisiteIds: ['lib_t1_deregulation'],
    requirements: {
      description: 'Moderate tax orientation.',
      requiredPolicy: { taxRate: 'low' },
      minApproval: 40,
    },
    reward: {
      gdpBonus: 0.55,
      budgetBonus: 90,
      inflationModifier: 0.3,
      legacyPoints: 4,
      structuralBonus: { corruptionReduction: 5 },
      flavourText: 'A simpler tax code reduces the compliance cost for SMEs by 40%. GST is politically unpopular at first — but the revenue it generates funds the infrastructure that voters later demand credit for.',
      historicalNote: 'Malaysia\'s GST, introduced 2015 at 6%, was abolished in 2018 by the Pakatan Harapan government following its election victory — GST had been a major voter grievance. It was later replaced by SST.',
    },
  },

  {
    id: 'lib_t1_investment_climate',
    treeId: 'liberal_open_economy',
    tier: 1,
    category: 'external',
    icon: '🤝',
    name: 'Investment Climate Overhaul',
    description: 'Create a comprehensive package to attract foreign and domestic investment: single investment window at MIDA, 100% foreign ownership permitted in key sectors, automatic approval for investments below RM20 million, and Investment Guarantee Agreements with 50+ countries.',
    durationMonths: 10,
    prerequisiteIds: [],
    requirements: {
      description: 'Open trade and low tax orientation.',
      requiredPolicy: { openTrade: true, taxRate: 'low' },
    },
    reward: {
      gdpBonus: 0.65,
      unemploymentBonus: 0.5,
      legacyPoints: 3,
      structuralBonus: { humanCapitalBoost: 2, corruptionReduction: 3 },
      crossTreeSynergies: [
        {
          beneficiaryTree: 'export_tiger',
          targetMissionId: 'tiger_t1_port_development',
          requirementReduction: 0.15,
          description: 'Investment climate reform attracts the port investors needed for expansion.',
        },
      ],
      flavourText: 'Malaysia rises in every global competitiveness index. The investment inquiry rate doubles. Converting inquiries to commitments remains the harder challenge.',
    },
  },

  // ══════════════ TIER 2 — MARKET DEEPENING (8 missions) ══════════════

  {
    id: 'lib_t2_privatisation',
    treeId: 'liberal_open_economy',
    tier: 2,
    category: 'economic',
    icon: '🏢',
    name: 'Privatisation Programme',
    description: 'Transfer state enterprises to private ownership: Telekom Malaysia IPO, MAS privatisation, port concessions, and utility companies. Use competitive bidding rather than negotiated transfers. Ring-fence proceeds in a State Asset Trust dedicated to development spending.',
    durationMonths: 28,
    prerequisiteIds: ['lib_t1_deregulation', 'lib_t1_stock_exchange'],
    branch: 'privatisation',
    mutuallyExclusiveWith: ['lib_t2_regulatory_state'],
    requirements: {
      description: 'Low tax and moderate approval.',
      requiredPolicy: { taxRate: 'low' },
      minApproval: 40,
    },
    reward: {
      gdpBonus: 1.0,
      budgetBonus: 190,
      unemploymentBonus: -0.35,
      legacyPoints: 5,
      structuralBonus: { infrastructureBoost: 7, corruptionReduction: -3 },
      flavourText: 'Telecoms, ports, and utilities move to private hands. Efficiency improves in some. Connected political allies profit from others. Whether the privatisation was competitive or captured determines whether it is remembered as reform or plunder.',
      historicalNote: 'Malaysia\'s privatisation policy (1983) transferred over 460 entities by 2000. MAS and Proton required multiple renationalisations due to connected-party mismanagement — the downside of politically-connected privatisation.',
    },
  },

  {
    id: 'lib_t2_regulatory_state',
    treeId: 'liberal_open_economy',
    tier: 2,
    category: 'institutional',
    icon: '🔍',
    name: 'Independent Regulatory Framework',
    description: 'Establish arms-length independent regulators: the Energy Commission, Communications and Multimedia Commission, and Water Services Commission. Mandate multi-year price control frameworks, independent appeals tribunals, and annual performance reviews.',
    durationMonths: 20,
    prerequisiteIds: ['lib_t1_stock_exchange', 'lib_t1_competition_law'],
    branch: 'regulatory',
    mutuallyExclusiveWith: ['lib_t2_privatisation'],
    requirements: {
      description: 'Low corruption and governance capacity.',
      maxCorruption: 42,
      minHumanCapital: 38,
    },
    reward: {
      gdpBonus: 0.7,
      budgetBonus: 60,
      legacyPoints: 5,
      structuralBonus: { corruptionReduction: 12, humanCapitalBoost: 7 },
      policyUnlock: {
        description: 'Unlocks "Regulated Competition" — incentive-based pricing',
        unlockedOptions: { prioritySector: ['regulated_competition'] },
      },
      flavourText: 'The Energy Commission begins to price utilities according to cost rather than political calculation. Ministers hate it. Consumers slowly benefit. Investors finally have certainty.',
    },
  },

  {
    id: 'lib_t2_fdi_zones',
    treeId: 'liberal_open_economy',
    tier: 2,
    category: 'economic',
    icon: '🏗️',
    name: 'Foreign Direct Investment Drive',
    description: 'Aggressively court multinationals with ten-year tax holidays, streamlined approval through MIDA, dedicated industrial estates with world-class connectivity, and bilateral investment protection treaties with top source countries.',
    durationMonths: 20,
    prerequisiteIds: ['lib_t1_free_trade', 'lib_t1_investment_climate'],
    requirements: {
      description: 'Open trade, low taxes, low corruption.',
      requiredPolicy: { openTrade: true, taxRate: 'low' },
      maxCorruption: 44,
    },
    reward: {
      gdpBonus: 1.55,
      unemploymentBonus: 1.35,
      inflationModifier: 0.4,
      legacyPoints: 6,
      populationGrowthBonuses: [{ ethnicity: 'Chinese', bonus: 0.0007 }, { ethnicity: 'Indian', bonus: 0.0004 }],
      structuralBonus: { infrastructureBoost: 7, humanCapitalBoost: 5 },
      flavourText: 'Penang becomes the Silicon Valley of ASEAN. Electronics factories employ hundreds of thousands. Transfer pricing means much value leaves Malaysia — but the jobs, the skills, and the tax base remain.',
      historicalNote: 'Malaysia attracted US$2.5 billion in FDI annually by the mid-1990s. Intel, AMD, Bosch, and Motorola made Penang the world\'s largest semiconductor producer per capita.',
    },
  },

  {
    id: 'lib_t2_plural_rights',
    treeId: 'liberal_open_economy',
    tier: 2,
    category: 'social',
    icon: '🌺',
    name: 'Cultural Rights Charter',
    description: 'Enshrine legal protections for minority language education, religious practice, and cultural expression. Fund vernacular schools on parity with national schools. Establish a Parliamentary Select Committee on National Harmony.',
    durationMonths: 16,
    prerequisiteIds: ['lib_t1_property_rights'],
    requirements: {
      description: 'Multiracial government with moderate approval.',
      minApproval: 43,
    },
    reward: {
      approvalBonus: 9,
      legacyPoints: 5,
      populationGrowthBonuses: [{ ethnicity: 'Chinese', bonus: 0.001 }, { ethnicity: 'Indian', bonus: 0.0008 }, { ethnicity: 'Bumiputera Sabah (Non-Muslim)', bonus: 0.0005 }, { ethnicity: 'Bumiputera Sarawak (Non-Muslim)', bonus: 0.0005 }, { ethnicity: 'Orang Asli', bonus: 0.0005 }, { ethnicity: 'Others', bonus: 0.0005 }],
      structuralBonus: { inequalityReduction: -0.01 },
      crossTreeSynergies: [
        {
          beneficiaryTree: 'federal_pluralism',
          targetMissionId: 'fed_t2_language_rights',
          requirementReduction: 0.35,
          description: 'Cultural rights charter establishes the precedent for multilingual education policy.',
        },
      ],
      flavourText: 'Tamil schools and Chinese vernacular education receive legal recognition and equal funding — over the objections of Malay nationalist groups. The political coalition that passes this measure is tested.',
    },
  },

  {
    id: 'lib_t2_labour_market_flex',
    treeId: 'liberal_open_economy',
    tier: 2,
    category: 'social',
    icon: '👷',
    name: 'Labour Market Reform',
    description: 'Modernise the Employment Act: increase lay-off notice periods and severance, introduce portable benefits that follow workers between jobs, create a retrenchment fund, and strengthen enforcement against illegal foreign labour through higher penalties and digital verification.',
    durationMonths: 18,
    prerequisiteIds: ['lib_t1_tax_reform'],
    requirements: {
      description: 'Balanced welfare and moderate approval.',
      requiredPolicy: { welfareLevel: 'moderate' },
      minApproval: 40,
    },
    reward: {
      unemploymentBonus: 0.6,
      gdpBonus: 0.45,
      legacyPoints: 4,
      structuralBonus: { humanCapitalBoost: 5, inequalityReduction: -0.014 },
      crossTreeSynergies: [
        {
          beneficiaryTree: 'socialist_welfare',
          targetMissionId: 'soc_t1_labour_rights',
          requirementReduction: 0.2,
          description: 'Portable benefits model creates common ground for broader labour rights reform.',
        },
      ],
      flavourText: 'Workers gain new protections without the rigidities that destroy job creation. The balance is never perfect — but it is better than the old system where exploitation was legal and enforcement non-existent.',
    },
  },

  {
    id: 'lib_t2_financial_inclusion',
    treeId: 'liberal_open_economy',
    tier: 2,
    category: 'social',
    icon: '📱',
    name: 'Financial Inclusion Programme',
    description: 'Expand access to formal financial services for the bottom 40%: mobile banking licences, branchless banking agents in rural areas, a Financial Inclusion Fund for micro-enterprise lending, and mandatory free basic accounts at all banks.',
    durationMonths: 14,
    prerequisiteIds: ['lib_t1_stock_exchange', 'lib_t1_investment_climate'],
    requirements: {
      description: 'Open financial sector.',
      minBudgetBalance: -200,
    },
    reward: {
      gdpBonus: 0.5,
      unemploymentBonus: 0.4,
      approvalBonus: 5,
      legacyPoints: 3,
      populationGrowthBonuses: [{ ethnicity: 'all', bonus: 0.0004 }],
      structuralBonus: { inequalityReduction: -0.016, humanCapitalBoost: 4 },
      flavourText: 'Smallholders and hawkers enter the formal financial system for the first time. Mobile banking penetration reaches 80% within five years. The data generated becomes the foundation for a fintech industry.',
    },
  },

  {
    id: 'lib_t2_housing_market',
    treeId: 'liberal_open_economy',
    tier: 2,
    category: 'social',
    icon: '🏡',
    name: 'Housing Market Liberalisation',
    description: 'Reform the housing market: zone more land for residential development, streamline planning approvals from 3 years to 6 months, remove price controls on high-end properties to cross-subsidise affordable housing, and create a REIT market for institutional housing investment.',
    durationMonths: 20,
    prerequisiteIds: ['lib_t1_property_rights', 'lib_t1_deregulation'],
    requirements: {
      description: 'Adequate infrastructure and moderate approval.',
      minInfrastructure: 38,
      minApproval: 42,
    },
    reward: {
      gdpBonus: 0.7,
      unemploymentBonus: 0.5,
      legacyPoints: 4,
      structuralBonus: { infrastructureBoost: 7, inequalityReduction: -0.011 },
      crossTreeSynergies: [
        {
          beneficiaryTree: 'socialist_welfare',
          targetMissionId: 'soc_t2_public_housing',
          requirementReduction: 0.15,
          description: 'Reformed planning process applies equally to public housing construction.',
        },
      ],
      flavourText: 'Planning approvals that took years now take months. New developments multiply around urban transit nodes. Prices remain high — the market clears at a price point that excludes the young. Affordability remains the unresolved problem.',
    },
  },

  {
    id: 'lib_t2_startup_ecosystem',
    treeId: 'liberal_open_economy',
    tier: 2,
    category: 'economic',
    icon: '🚀',
    name: 'Startup Ecosystem',
    description: 'Create a startup-friendly environment: Cradle Fund grants, MDEC digital hub support, a Seed Capital Programme for deep-tech startups, and regulatory sandboxes for fintech, biotech, and clean energy. Attract Southeast Asian tech investors to establish regional headquarters in KL.',
    durationMonths: 16,
    prerequisiteIds: ['lib_t2_fdi_zones', 'lib_t1_stock_exchange'],
    requirements: {
      description: 'High human capital and light regulation.',
      minHumanCapital: 42,
      requiredPolicy: { openTrade: true },
    },
    reward: {
      gdpBonus: 0.8,
      unemploymentBonus: 0.7,
      legacyPoints: 5,
      structuralBonus: { humanCapitalBoost: 8, corruptionReduction: 3 },
      policyUnlock: {
        description: 'Unlocks "Digital Economy" priority sector',
        unlockedOptions: { prioritySector: ['digital'] },
      },
      crossTreeSynergies: [
        {
          beneficiaryTree: 'developmental_state',
          targetMissionId: 'dev_t3_msc',
          requirementReduction: 0.15,
          description: 'Startup ecosystem generates the demand for MSC-corridor innovation infrastructure.',
        },
      ],
      flavourText: 'The Bangsar South office market fills with tech companies. Grab, AirAsia Digital, and Carsome emerge as proof that Malaysian founders can build regionally competitive companies.',
    },
  },

  // ══════════════ TIER 3 — ADVANCED MARKET (7 missions) ══════════════

  {
    id: 'lib_t3_asian_financial_hub',
    treeId: 'liberal_open_economy',
    tier: 3,
    category: 'economic',
    icon: '🌆',
    name: 'Asian Financial Hub',
    description: 'Position KL as a regional financial centre: expand the offshore financial centre in Labuan, develop the Islamic capital market globally, attract major international banks and fund managers, and create a Malaysian sovereign wealth advisory role.',
    durationMonths: 40,
    prerequisiteIds: ['lib_t2_privatisation', 'lib_t2_fdi_zones'],
    requirements: {
      description: 'Low corruption, open trade, high human capital.',
      maxCorruption: 30,
      requiredPolicy: { openTrade: true },
      minHumanCapital: 54,
    },
    reward: {
      gdpBonus: 2.3,
      budgetBonus: 175,
      inflationModifier: 0.3,
      approvalBonus: 10,
      legacyPoints: 10,
      populationGrowthBonuses: [{ ethnicity: 'all', bonus: 0.0007 }],
      structuralBonus: { corruptionReduction: 11, humanCapitalBoost: 13 },
      policyUnlock: {
        description: 'Unlocks "Offshore Financial Centre" tax structuring',
        unlockedOptions: { taxRate: ['offshore'] },
      },
      flavourText: 'Banks from London and Tokyo open KL offices. Islamic finance makes Malaysia the global standard-setter for sukuk. Financial hubs attract capital and money laundering in equal measure — the regulation that prevents both is the challenge.',
      historicalNote: 'Labuan IBFC established 1990. Malaysia became the world\'s largest sukuk market. KL ranked 32nd in the Global Financial Centres Index by 2021 — ahead of Mumbai but behind Singapore (6th) and further behind Hong Kong.',
    },
  },

  {
    id: 'lib_t3_meritocracy',
    treeId: 'liberal_open_economy',
    tier: 3,
    category: 'social',
    icon: '🎓',
    name: 'Meritocracy Initiative',
    description: 'Phase out ethnic quotas in public sector hiring, university admissions, and government contracts. Replace with transparent, universal merit criteria and a parallel needs-based disadvantage programme that benefits low-income Malaysians of all ethnicities.',
    durationMonths: 36,
    prerequisiteIds: ['lib_t2_plural_rights', 'lib_t2_labour_market_flex'],
    requirements: {
      description: 'High approval and low corruption — trust is the precondition.',
      minApproval: 57,
      maxCorruption: 33,
    },
    reward: {
      gdpBonus: 0.9,
      unemploymentBonus: 0.85,
      approvalBonus: 11,
      legacyPoints: 10,
      populationGrowthBonuses: [{ ethnicity: 'Chinese', bonus: 0.0008 }, { ethnicity: 'Indian', bonus: 0.0007 }, { ethnicity: 'Malay', bonus: 0.0003 }],
      structuralBonus: { humanCapitalBoost: 11, corruptionReduction: 8, inequalityReduction: -0.022 },
      flavourText: 'The best and brightest stay. Brain drain reverses as opportunities open to all. The political reaction from Malay nationalist groups is fierce, sustained, and ultimately testifies to the reform\'s reach.',
    },
  },

  {
    id: 'lib_t3_ecotourism',
    treeId: 'liberal_open_economy',
    tier: 3,
    category: 'economic',
    icon: '🌴',
    name: 'Tourism & Services Economy',
    description: 'Develop a comprehensive services economy: ecotourism certification scheme, medical tourism excellence programme (Penang and KL), creative industries tax incentives, and a Malaysia Premium Brand programme to move up the value chain in services exports.',
    durationMonths: 26,
    prerequisiteIds: ['lib_t2_fdi_zones', 'lib_t2_plural_rights'],
    requirements: {
      description: 'Services priority and adequate infrastructure.',
      requiredPolicy: { prioritySector: 'services' },
      minInfrastructure: 48,
    },
    reward: {
      gdpBonus: 1.25,
      unemploymentBonus: 0.95,
      inflationModifier: -0.2,
      budgetBonus: 85,
      legacyPoints: 6,
      populationGrowthBonuses: [{ ethnicity: 'all', bonus: 0.0005 }],
      structuralBonus: { infrastructureBoost: 11 },
      flavourText: '"Malaysia Truly Asia" becomes both a slogan and an economic reality. Medical tourism grows to 1.2 million patients annually. The rainforest that elsewhere is cleared for palm oil here generates higher per-hectare economic value from conservation.',
      historicalNote: 'Malaysia attracted 26 million tourists in 2019. Medical tourism generated RM1.9 billion by 2018. COVID-19 devastated the tourism sector in 2020-21; recovery was slower than manufacturing.',
    },
  },

  {
    id: 'lib_t3_pension_reform',
    treeId: 'liberal_open_economy',
    tier: 3,
    category: 'social',
    icon: '👴',
    name: 'Pension and Retirement Reform',
    description: 'Reform the EPF: allow voluntary contributions above the mandatory ceiling, introduce a third account for critical expenses (healthcare, education), create a private pension market with tax incentives, and establish a Retirement Age Flexibility Act.',
    durationMonths: 22,
    prerequisiteIds: ['lib_t2_financial_inclusion', 'lib_t2_labour_market_flex'],
    requirements: {
      description: 'Moderate welfare and adequate budget.',
      requiredPolicy: { welfareLevel: 'moderate' },
      minBudgetBalance: -180,
    },
    reward: {
      gdpBonus: 0.55,
      budgetBonus: 110,
      legacyPoints: 6,
      structuralBonus: { humanCapitalBoost: 5, inequalityReduction: -0.018 },
      policyUnlock: {
        description: 'Unlocks "Private Pension Market" — new savings vehicles',
        unlockedOptions: {},
      },
      flavourText: 'Malaysians save more, retire later, and consume more in old age. The financial services sector expands. The actuarial problem of the EPF — 50% of members have less than RM10,000 at retirement — is addressed partially, unevenly, gradually.',
      historicalNote: 'The EPF\'s 2020 COVID-19 special withdrawal revealed that millions of Malaysians had inadequate retirement savings. The policy debate around mandatory versus voluntary contributions intensified significantly.',
    },
  },

  {
    id: 'lib_t3_data_economy',
    treeId: 'liberal_open_economy',
    tier: 3,
    category: 'economic',
    icon: '🔢',
    name: 'Data Economy Framework',
    description: 'Enact a Personal Data Protection Act with teeth, establish a Data Commissioner, create a Data Marketplace for anonymised government datasets, and negotiate data-sharing agreements with Singapore and Japan to build a regional data economy.',
    durationMonths: 20,
    prerequisiteIds: ['lib_t2_startup_ecosystem', 'lib_t1_competition_law'],
    requirements: {
      description: 'High human capital and digital-ready institutions.',
      minHumanCapital: 52,
      maxCorruption: 40,
    },
    reward: {
      gdpBonus: 0.85,
      unemploymentBonus: 0.7,
      legacyPoints: 6,
      structuralBonus: { humanCapitalBoost: 9, corruptionReduction: 5 },
      crossTreeSynergies: [
        {
          beneficiaryTree: 'developmental_state',
          targetMissionId: 'dev_t4_5g_digital',
          requirementReduction: 0.2,
          description: 'Data economy framework creates the regulatory environment for 5G-enabled data services.',
        },
      ],
      flavourText: 'Data becomes a traded commodity. Malaysian companies that were information-rich but insight-poor learn to extract value from their customer data. The privacy concerns are real — the Data Commissioner is the checkpoint.',
    },
  },

  {
    id: 'lib_t3_human_capital_fund',
    treeId: 'liberal_open_economy',
    tier: 3,
    category: 'social',
    icon: '🎯',
    name: 'Human Capital Development Fund',
    description: 'Establish a National Human Capital Development Fund providing income-contingent loans for reskilling, a skills recognition framework for informal learners, and partnerships with community colleges, polytechnics, and online learning platforms.',
    durationMonths: 18,
    prerequisiteIds: ['lib_t2_labour_market_flex', 'lib_t2_startup_ecosystem'],
    requirements: {
      description: 'Adequate budget and human capital baseline.',
      minHumanCapital: 48,
      minBudgetBalance: -200,
    },
    reward: {
      unemploymentBonus: 1.1,
      legacyPoints: 6,
      structuralBonus: { humanCapitalBoost: 11, inequalityReduction: -0.016 },
      populationGrowthBonuses: [{ ethnicity: 'all', bonus: 0.0006 }],
      flavourText: 'Workers who lost jobs to automation find a path to new ones. Not every path leads upward — but the alternative of structural unemployment is worse for everyone.',
    },
  },

  {
    id: 'lib_t3_trade_facilitation',
    treeId: 'liberal_open_economy',
    tier: 3,
    category: 'external',
    icon: '📦',
    name: 'Trade Facilitation & Customs Reform',
    description: 'Digitalise the entire customs clearance system, introduce trusted trader programmes reducing inspection rates for compliant companies, adopt the WTO Trade Facilitation Agreement in full, and establish ASEAN customs interoperability.',
    durationMonths: 16,
    prerequisiteIds: ['lib_t1_free_trade', 'lib_t2_fdi_zones'],
    requirements: {
      description: 'Open trade and infrastructure.',
      requiredPolicy: { openTrade: true },
      minInfrastructure: 45,
    },
    reward: {
      gdpBonus: 0.9,
      budgetBonus: 75,
      inflationModifier: -0.3,
      legacyPoints: 4,
      structuralBonus: { corruptionReduction: 6, infrastructureBoost: 4 },
      crossTreeSynergies: [
        {
          beneficiaryTree: 'export_tiger',
          targetMissionId: 'tiger_t2_asean_integration',
          requirementReduction: 0.25,
          description: 'Customs harmonisation directly enables ASEAN economic integration.',
        },
      ],
      flavourText: 'Customs clearance falls from days to hours. Perishable exports that previously missed global markets can now compete. The digital customs system also eliminates the brown envelope — a systemic change.',
    },
  },

  // ══════════════ TIER 4 — HIGH INCOME APPROACH (6 missions) ══════════════

  {
    id: 'lib_t4_high_income_society',
    treeId: 'liberal_open_economy',
    tier: 4,
    category: 'legacy',
    icon: '⭐',
    name: 'High-Income Nation Transition',
    description: 'Complete all prerequisites for the World Bank high-income threshold: structural labour market reform, productivity-driven growth, world-class social infrastructure ensuring gains are broadly shared, and an ageing population managed through robust pension reform.',
    durationMonths: 54,
    prerequisiteIds: ['lib_t3_asian_financial_hub', 'lib_t3_meritocracy'],
    requirements: {
      description: 'Sustained growth, high human capital, institutional quality.',
      minGdpGrowth: 5.5,
      minHumanCapital: 70,
      maxCorruption: 25,
      requiredPolicy: { openTrade: true },
      minApproval: 55,
    },
    reward: {
      gdpBonus: 3.0,
      unemploymentBonus: 2.0,
      inflationModifier: -0.5,
      budgetBonus: 220,
      approvalBonus: 12,
      legacyPoints: 30,
      populationGrowthBonuses: [{ ethnicity: 'all', bonus: 0.0012 }],
      structuralBonus: { humanCapitalBoost: 22, infrastructureBoost: 14, corruptionReduction: 18, inequalityReduction: -0.055 },
      policyUnlock: {
        description: 'Unlocks "High-Income Labour Standards"',
        unlockedOptions: { welfareLevel: ['high_income_standards'] },
      },
      flavourText: 'Malaysia joins the high-income club — or it doesn\'t, because the institutions were reformed in name only. This is the fork in the road.',
    },
  },

  {
    id: 'lib_t4_creative_economy',
    treeId: 'liberal_open_economy',
    tier: 4,
    category: 'economic',
    icon: '🎨',
    name: 'Creative Industries Economy',
    description: 'Develop Malaysia\'s creative economy into a regional centre: film production incentives, animation and game development clusters, music industry export support, and design-led manufacturing. Position Malaysia as the creative hub of ASEAN.',
    durationMonths: 28,
    prerequisiteIds: ['lib_t3_ecotourism', 'lib_t3_data_economy'],
    requirements: {
      description: 'Strong services and human capital.',
      requiredPolicy: { prioritySector: 'services' },
      minHumanCapital: 58,
    },
    reward: {
      gdpBonus: 1.1,
      unemploymentBonus: 0.9,
      legacyPoints: 8,
      structuralBonus: { humanCapitalBoost: 10, inequalityReduction: -0.016 },
      populationGrowthBonuses: [{ ethnicity: 'all', bonus: 0.0007 }],
      flavourText: 'Malaysian animation studios win international commissions. KL fashion designers export to Paris. The ringgit value generated per creative worker is ten times that of a factory worker. The transformation is aesthetic as well as economic.',
    },
  },

  {
    id: 'lib_t4_climate_economy',
    treeId: 'liberal_open_economy',
    tier: 4,
    category: 'economic',
    icon: '🌊',
    name: 'Carbon Market and Climate Finance',
    description: 'Establish a voluntary carbon market, issue green sukuk for climate infrastructure, create a biodiversity credit scheme for forest conservation, and develop Malaysia as the ASEAN hub for climate finance and blended finance.',
    durationMonths: 30,
    prerequisiteIds: ['lib_t3_ecotourism', 'lib_t3_asian_financial_hub'],
    requirements: {
      description: 'Strong financial markets and open economy.',
      minHumanCapital: 55,
      requiredPolicy: { openTrade: true },
      maxCorruption: 35,
    },
    reward: {
      gdpBonus: 1.0,
      budgetBonus: 140,
      legacyPoints: 7,
      structuralBonus: { corruptionReduction: 7, humanCapitalBoost: 8 },
      crossTreeSynergies: [
        {
          beneficiaryTree: 'socialist_welfare',
          targetMissionId: 'soc_t4_just_transition',
          requirementReduction: 0.2,
          description: 'Climate finance infrastructure enables just transition funding.',
        },
      ],
      flavourText: 'Malaysia\'s rainforest, rather than being cleared for palm oil, generates carbon credits that rival palm oil revenues per hectare. The economics of deforestation are turned upside down.',
    },
  },

  {
    id: 'lib_t4_education_market',
    treeId: 'liberal_open_economy',
    tier: 4,
    category: 'social',
    icon: '🎓',
    name: 'Education Market Reform',
    description: 'Transform Malaysia into a regional education hub: allow private universities to award medical and law degrees, reform the student loan system, attract three QS top-100 universities to establish branch campuses, and implement outcome-based university funding.',
    durationMonths: 26,
    prerequisiteIds: ['lib_t3_meritocracy', 'lib_t3_human_capital_fund'],
    requirements: {
      description: 'High human capital and open institutional framework.',
      minHumanCapital: 60,
      maxCorruption: 32,
    },
    reward: {
      unemploymentBonus: 1.2,
      budgetBonus: 80,
      legacyPoints: 8,
      structuralBonus: { humanCapitalBoost: 14, inequalityReduction: -0.02 },
      populationGrowthBonuses: [{ ethnicity: 'all', bonus: 0.0009 }],
      flavourText: 'Universities compete for students on the basis of outcomes, not prestige. Monash, Nottingham, and Heriot-Watt branch campuses become genuine contributors to Malaysian research. The brain drain slows, then reverses.',
    },
  },

  {
    id: 'lib_t4_social_safety_net',
    treeId: 'liberal_open_economy',
    tier: 4,
    category: 'social',
    icon: '🛡️',
    name: 'Universal Social Safety Net',
    description: 'Establish a comprehensive safety net that is universal rather than means-tested: universal child benefit, unemployment insurance replacing Bantuan Sara Hidup, a negative income tax for working poor, and a Minimum Income Guarantee.',
    durationMonths: 32,
    prerequisiteIds: ['lib_t3_pension_reform', 'lib_t2_financial_inclusion'],
    requirements: {
      description: 'High income and adequate budget for universal provision.',
      minGdpGrowth: 4.0,
      minBudgetBalance: -150,
      requiredPolicy: { welfareLevel: 'moderate' },
    },
    reward: {
      approvalBonus: 13,
      budgetBonus: -100,
      legacyPoints: 10,
      populationGrowthBonuses: [{ ethnicity: 'all', bonus: 0.001 }],
      structuralBonus: { inequalityReduction: -0.038, humanCapitalBoost: 9 },
      flavourText: 'The social contract is upgraded. Malaysians who fall through the cracks of the economy now have a floor to land on. The fiscal cost is real; so is the human dignity preserved.',
    },
  },

  // ══════════════ TIER 5 — LIBERAL ENDGAME (7 missions) ══════════════

  {
    id: 'lib_t5_singapore_plus',
    treeId: 'liberal_open_economy',
    tier: 5,
    category: 'legacy',
    icon: '🌟',
    name: 'Malaysia: The Other Singapore',
    description: 'Position Malaysia as Singapore\'s peer — and in some dimensions, its superior: larger land area, more diverse economy, richer natural resources, and lower cost of living for equivalent quality of life. Attract Singapore-based regional headquarters with competitive package.',
    durationMonths: 40,
    prerequisiteIds: ['lib_t4_high_income_society', 'lib_t4_creative_economy'],
    requirements: {
      description: 'Achieved high-income status with strong institutions.',
      minGdpGrowth: 5.0,
      minHumanCapital: 74,
      maxCorruption: 22,
      minApproval: 58,
    },
    reward: {
      gdpBonus: 2.5,
      unemploymentBonus: 1.8,
      budgetBonus: 220,
      approvalBonus: 15,
      legacyPoints: 30,
      populationGrowthBonuses: [{ ethnicity: 'all', bonus: 0.0015 }],
      structuralBonus: { humanCapitalBoost: 20, infrastructureBoost: 16, corruptionReduction: 18, inequalityReduction: -0.055 },
      flavourText: 'For the first time, Malaysia is spoken of in the same breath as Singapore in international boardrooms. The compliment has a barb — Singapore\'s success was always the implicit critique of Malaysia\'s shortfalls. Now the mirror does not judge.',
    },
  },

  {
    id: 'lib_t5_constitutional_rights',
    treeId: 'liberal_open_economy',
    tier: 5,
    category: 'institutional',
    icon: '📜',
    name: 'Constitutional Rights Guarantee',
    description: 'Enshrine a comprehensive Bill of Rights in the Constitution: equal protection regardless of ethnicity, freedom of expression with clear and narrow limitations, an independent human rights commission with enforcement powers, and constitutional review by the Federal Court.',
    durationMonths: 36,
    prerequisiteIds: ['lib_t4_education_market', 'lib_t3_meritocracy'],
    requirements: {
      description: 'Strong democratic mandate and institutions.',
      maxCorruption: 28,
      minApproval: 60,
      minLegacyPoints: 55,
    },
    reward: {
      approvalBonus: 16,
      legacyPoints: 22,
      populationGrowthBonuses: [{ ethnicity: 'all', bonus: 0.0011 }],
      structuralBonus: { corruptionReduction: 16, humanCapitalBoost: 10, inequalityReduction: -0.03 },
      crossTreeSynergies: [
        {
          beneficiaryTree: 'federal_pluralism',
          targetMissionId: 'fed_t4_national_reconciliation',
          requirementReduction: 0.3,
          description: 'Constitutional rights framework is the bedrock for national reconciliation.',
        },
      ],
      flavourText: 'The Federal Constitution is amended to speak to the Malaysia of 2030, not the Malaysia of 1957. The process is contested, messy, and democratic. It is the most legitimate piece of legislation in Malaysian history.',
    },
  },

  {
    id: 'lib_t5_regional_integration',
    treeId: 'liberal_open_economy',
    tier: 5,
    category: 'external',
    icon: '🌏',
    name: 'ASEAN Economic Governance',
    description: 'Lead the creation of an ASEAN economic governance framework: a common tariff, a shared competition authority, mutual recognition of professional qualifications, and the ASEAN Dollar — a regional reserve currency for trade settlement.',
    durationMonths: 48,
    prerequisiteIds: ['lib_t4_high_income_society', 'lib_t3_trade_facilitation'],
    requirements: {
      description: 'Regional leadership position and strong economy.',
      minGdpGrowth: 4.5,
      requiredPolicy: { openTrade: true },
      minHumanCapital: 70,
      maxCorruption: 25,
    },
    reward: {
      gdpBonus: 2.2,
      budgetBonus: 190,
      legacyPoints: 25,
      populationGrowthBonuses: [{ ethnicity: 'all', bonus: 0.001 }],
      structuralBonus: { humanCapitalBoost: 14, infrastructureBoost: 10, corruptionReduction: 12, inequalityReduction: -0.03 },
      flavourText: 'ASEAN moves from aspiration to architecture. Malaysia leads the negotiation of the framework that makes Southeast Asia a genuine economic bloc. The achievement will be written about long after the politicians who negotiated it are forgotten.',
    },
  },

  {
    id: 'lib_t5_pension_crisis',
    treeId: 'liberal_open_economy',
    tier: 5,
    category: 'crisis',
    icon: '⚠️',
    name: 'Ageing Population Crisis',
    description: 'Malaysia\'s rapid demographic transition to an ageing society exceeds the capacity of the EPF and public pension systems. A reform crisis demands immediate action: extending working ages, increasing contributions, or managing expectations.',
    durationMonths: 20,
    prerequisiteIds: ['lib_t3_pension_reform'],
    requirements: {
      description: 'Triggered by demographic pressure and insufficient pension reserves.',
      crisisTrigger: { unemploymentAbove: 6, inflationAbove: 0 },
    },
    reward: {
      budgetBonus: -150,
      approvalBonus: -8,
      legacyPoints: -5,
      structuralBonus: { humanCapitalBoost: 5, inequalityReduction: -0.02 },
      policyUnlock: {
        description: 'Unlocks "Mandatory Retirement Age Extension" — workforce retention',
        unlockedOptions: {},
      },
      flavourText: 'Demography is destiny and its bill has arrived. Malaysia ages faster than it became rich — the opposite of Europe\'s trajectory. The next generation of workers will carry a heavy load of retired dependents.',
    },
  },

  {
    id: 'lib_t5_innovation_society',
    treeId: 'liberal_open_economy',
    tier: 5,
    category: 'legacy',
    icon: '🔭',
    name: 'Innovation Society',
    description: 'Achieve the innovation-led growth society: R&D at 3% of GDP, Malaysian patents registered internationally, three Malaysian companies in the global Fortune 500, and a Malaysian university in the QS top 50.',
    durationMonths: 54,
    prerequisiteIds: ['lib_t5_singapore_plus', 'lib_t4_education_market'],
    requirements: {
      description: 'Full high-income innovation ecosystem.',
      minGdpGrowth: 4.5,
      minHumanCapital: 76,
      maxCorruption: 20,
    },
    reward: {
      gdpBonus: 3.5,
      unemploymentBonus: 2.5,
      approvalBonus: 15,
      legacyPoints: 40,
      populationGrowthBonuses: [{ ethnicity: 'all', bonus: 0.0018 }],
      structuralBonus: { humanCapitalBoost: 25, infrastructureBoost: 18, corruptionReduction: 20, inequalityReduction: -0.065 },
      flavourText: 'A Malaysian scientist wins the Nobel Prize for Chemistry. A Malaysian tech company IPOs on NASDAQ. A Malaysian university places 48th in QS. These are not the intended metrics — they are the emergent properties of getting everything else right.',
    },
  },

  {
    id: 'lib_t5_welfare_correction',
    treeId: 'liberal_open_economy',
    tier: 5,
    category: 'crisis',
    icon: '🔔',
    name: 'Inequality Correction',
    description: 'Despite high growth, the Gini coefficient has risen and urban-rural inequality widened. A wave of popular discontent demands redistribution — the market has delivered growth but not equity. Respond with targeted redistribution or face electoral consequences.',
    durationMonths: 18,
    prerequisiteIds: ['lib_t4_social_safety_net'],
    requirements: {
      description: 'Triggered when inequality remains high despite growth.',
      crisisTrigger: { inflationAbove: 5, unemploymentAbove: 0 },
    },
    reward: {
      approvalBonus: 8,
      budgetBonus: -120,
      legacyPoints: 3,
      structuralBonus: { inequalityReduction: -0.025 },
      flavourText: 'The liberal growth model faces its fundamental test: does the rising tide lift all boats, or does it swamp the smallest ones? The answer depends on whether redistribution is an afterthought or an integral part of the design.',
    },
  },
];

export { LIBERAL_MISSIONS };
