// ─────────────────────────────────────────────────────────────
// TREE 5: EXPORT TIGER — 35 MISSIONS, 5 TIERS
// ─────────────────────────────────────────────────────────────

const EXPORT_TIGER_MISSIONS = [
  // ══════════════ TIER 1 — COMMODITY FOUNDATION (7 missions) ══════════════

  {
    id: 'tiger_t1_rubber_modernisation',
    treeId: 'export_tiger',
    tier: 1,
    category: 'economic',
    icon: '🌿',
    name: 'Rubber Industry Modernisation',
    description: 'Replace smallholder rubber with RRIM600 high-yield clones via RISDA grants. Establish the Malaysian Rubber Board with export pricing authority. Build the KL Commodity Exchange. Create a downstream rubber goods manufacturing incentive — gloves, tyres, engineering goods.',
    durationMonths: 14,
    prerequisiteIds: [],
    requirements: {
      description: 'Commodity prices above baseline.',
      minCommodityIndex: 88,
    },
    reward: {
      gdpBonus: 0.55,
      budgetBonus: 55,
      legacyPoints: 3,
      populationGrowthBonuses: [{ ethnicity: 'Malay', bonus: 0.0005 }],
      structuralBonus: { humanCapitalBoost: 3 },
      crossTreeSynergies: [
        {
          beneficiaryTree: 'bumiputera_agenda',
          targetMissionId: 'bumi_t1_felda_pioneer',
          requirementReduction: 0.15,
          description: 'Rubber modernisation proves the viability of smallholder plantation development.',
        },
      ],
      flavourText: 'Malaysian rubber sets the world benchmark for yield per hectare. RISDA\'s extension services transform subsistence tappers into commercial producers. The downstream glove industry is an unexpected dividend.',
      historicalNote: 'Malaysia was the world\'s largest rubber producer until the 1990s. The RRIM developed high-yield clones that doubled output per hectare. Malaysia became the global leader in rubber gloves, supplying 67% of world demand.',
    },
  },

  {
    id: 'tiger_t1_tin_boom',
    treeId: 'export_tiger',
    tier: 1,
    category: 'economic',
    icon: '⛏️',
    name: 'Tin Export Capitalisation',
    description: 'Leverage high global tin prices through the Minerals Development Act and state marketing boards. Invest surplus in downstream smelting capacity. Establish the Kuala Lumpur Tin Market as the global price-setting venue. Diversify tin revenues into infrastructure.',
    durationMonths: 11,
    prerequisiteIds: [],
    requirements: {
      description: 'High commodity price index.',
      minCommodityIndex: 108,
    },
    reward: {
      gdpBonus: 0.75,
      budgetBonus: 115,
      legacyPoints: 3,
      populationGrowthBonuses: [{ ethnicity: 'Chinese', bonus: 0.0006 }],
      structuralBonus: { infrastructureBoost: 4 },
      flavourText: 'Taiping and Ipoh prosper. Tin revenues fill the treasury. But the global tin cartel collapses in 1985 — and the lesson about commodity dependence is learned catastrophically rather than theoretically.',
      historicalNote: 'Malaysia supplied 40% of world tin output in 1970. The 1985 tin market collapse wiped out the International Tin Council and devastated Perak. Ipoh never fully recovered its pre-collapse prosperity.',
    },
  },

  {
    id: 'tiger_t1_port_development',
    treeId: 'export_tiger',
    tier: 1,
    category: 'economic',
    icon: '⚓',
    name: 'Port Klang Expansion',
    description: 'Expand Port Klang from a colonial riverside facility to a modern container terminal handling 10 million TEUs annually. Build deepwater berths accommodating Post-Panamax vessels. Establish 24/7 operations with digitalised cargo tracking.',
    durationMonths: 18,
    prerequisiteIds: [],
    requirements: {
      description: 'Open trade and basic infrastructure.',
      requiredPolicy: { openTrade: true },
      minInfrastructure: 23,
    },
    reward: {
      gdpBonus: 0.65,
      budgetBonus: 75,
      legacyPoints: 4,
      structuralBonus: { infrastructureBoost: 11 },
      flavourText: 'Container ships queue in the Strait of Malacca. Malaysia becomes an indispensable node in global supply chains — and every supply chain disruption, from Suez to COVID, reminds the world.',
      historicalNote: 'Port Klang became the 12th busiest port globally by 2019, handling 13.2 million TEUs. The PKFZ scandal (2007) cost RM12 billion — illustrating that infrastructure governance and physical infrastructure are separate challenges.',
    },
  },

  {
    id: 'tiger_t1_malaysia_airlines',
    treeId: 'export_tiger',
    tier: 1,
    category: 'external',
    icon: '✈️',
    name: 'MAS Flag Carrier Expansion',
    description: 'Build Malaysia Airlines into a regional flag carrier: expand the long-haul network to Europe, Australia, and North America, acquire widebody aircraft, establish a MRO (Maintenance, Repair, Overhaul) facility in Subang generating high-skilled jobs.',
    durationMonths: 20,
    prerequisiteIds: [],
    requirements: {
      description: 'Open trade and adequate infrastructure.',
      requiredPolicy: { openTrade: true },
      minInfrastructure: 25,
    },
    reward: {
      gdpBonus: 0.6,
      unemploymentBonus: 0.4,
      legacyPoints: 3,
      structuralBonus: { humanCapitalBoost: 4, infrastructureBoost: 5 },
      crossTreeSynergies: [
        {
          beneficiaryTree: 'liberal_open_economy',
          targetMissionId: 'lib_t3_ecotourism',
          requirementReduction: 0.2,
          description: 'Expanded airline connectivity is a prerequisite for competitive tourism development.',
        },
      ],
      flavourText: 'Malaysia Airlines becomes the pride of the fleet and the pride of the nation. The long-haul routes open Malaysia to the world — tourists, investors, and diaspora returning home. The subsequent MH370 and MH17 tragedies are a future grief.',
      historicalNote: 'MAS operated profitably through the 1990s before political interference and cost mismanagement pushed it into repeated cycles of loss and restructuring. AirAsia\'s emergence in 2001 transformed the Malaysian aviation landscape.',
    },
  },

  {
    id: 'tiger_t1_airasia_lcl',
    treeId: 'export_tiger',
    tier: 1,
    category: 'external',
    icon: '🛫',
    name: 'Low-Cost Carrier Revolution',
    description: 'License and support a low-cost carrier market: deregulate domestic aviation, build KLIA2 as a dedicated LCC terminal, negotiate open skies agreements across ASEAN. Make air travel accessible to the Malaysian middle class and inbound budget tourists.',
    durationMonths: 14,
    prerequisiteIds: ['tiger_t1_malaysia_airlines'],
    requirements: {
      description: 'Open trade and deregulation orientation.',
      requiredPolicy: { openTrade: true, taxRate: 'low' },
    },
    reward: {
      gdpBonus: 0.55,
      unemploymentBonus: 0.4,
      inflationModifier: -0.2,
      legacyPoints: 4,
      structuralBonus: { humanCapitalBoost: 3, infrastructureBoost: 5 },
      crossTreeSynergies: [
        {
          beneficiaryTree: 'liberal_open_economy',
          targetMissionId: 'lib_t2_fdi_zones',
          requirementReduction: 0.1,
          description: 'Low-cost connectivity reduces the barrier to FDI-attracted talent mobility.',
        },
      ],
      flavourText: 'AirAsia takes off. "Now everyone can fly" is not just a slogan — it is a social transformation. A Kedah farmer\'s son can visit Bangkok for less than a bus ticket. Geography is no longer destiny.',
      historicalNote: 'AirAsia was relaunched in 2001 by Tony Fernandes, who purchased the debt-laden airline from the DRB-HICOM group for RM1. It grew to carry 75 million passengers annually, making ASEAN\'s middle class mobile.',
    },
  },

  {
    id: 'tiger_t1_telco_liberalisation',
    treeId: 'export_tiger',
    tier: 1,
    category: 'economic',
    icon: '📱',
    name: 'Telecoms Liberalisation',
    description: 'End Telekom Malaysia\'s monopoly. License three competing mobile networks. Allow foreign ownership up to 49% in telecoms. Mandate spectrum sharing for rural coverage. Build a universal service obligation fund ensuring coverage in all populated areas.',
    durationMonths: 12,
    prerequisiteIds: [],
    requirements: {
      description: 'Open trade and low tax orientation.',
      requiredPolicy: { openTrade: true },
    },
    reward: {
      gdpBonus: 0.5,
      inflationModifier: -0.3,
      legacyPoints: 3,
      structuralBonus: { humanCapitalBoost: 4, infrastructureBoost: 5, corruptionReduction: 3 },
      crossTreeSynergies: [
        {
          beneficiaryTree: 'developmental_state',
          targetMissionId: 'dev_t3_msc',
          requirementReduction: 0.1,
          description: 'Competitive telecoms market provides the infrastructure base for the MSC.',
        },
      ],
      flavourText: 'Mobile phone prices fall 60% in two years. Coverage reaches the most remote kampungs. The fishermen of Sabah check weather forecasts on smartphones. Productivity gains in every sector are immediate and compounding.',
    },
  },

  {
    id: 'tiger_t1_forex_liberalisation',
    treeId: 'export_tiger',
    tier: 1,
    category: 'external',
    icon: '💱',
    name: 'Foreign Exchange Market Development',
    description: 'Develop a deep and liquid ringgit foreign exchange market. Allow forward hedging instruments for exporters. Build Bank Negara\'s reserves to 9 months of import cover. Establish the Kuala Lumpur Offshore Financial Centre in Labuan.',
    durationMonths: 15,
    prerequisiteIds: ['tiger_t1_port_development'],
    requirements: {
      description: 'Open trade and stable monetary policy.',
      requiredPolicy: { openTrade: true },
      maxInflation: 6.0,
    },
    reward: {
      gdpBonus: 0.4,
      budgetBonus: 55,
      inflationModifier: -0.25,
      legacyPoints: 3,
      structuralBonus: { corruptionReduction: 3 },
      crossTreeSynergies: [
        {
          beneficiaryTree: 'liberal_open_economy',
          targetMissionId: 'lib_t3_asian_financial_hub',
          requirementReduction: 0.15,
          description: 'Deep FX market is a prerequisite for regional financial hub ambitions.',
        },
      ],
      flavourText: 'Exporters can hedge their ringgit exposure. Foreign investors can manage currency risk. The financial plumbing, unglamorous but essential, starts to work. The ringgit becomes a real currency with real market depth.',
    },
  },

  // ══════════════ TIER 2 — EXPORT ENGINES (8 missions) ══════════════

  {
    id: 'tiger_t2_palm_oil',
    treeId: 'export_tiger',
    tier: 2,
    category: 'economic',
    icon: '🌴',
    name: 'Palm Oil Revolution',
    description: 'Convert secondary jungle and cleared land to palm oil at scale via RISDA and private agribusiness. Build MPOB (Malaysian Palm Oil Board) as the world\'s premier oil palm research institution. Mandate downstream refining — no crude CPO exports, only value-added products.',
    durationMonths: 22,
    prerequisiteIds: ['tiger_t1_rubber_modernisation'],
    requirements: {
      description: 'Agriculture priority with open trade.',
      requiredPolicy: { openTrade: true, prioritySector: 'agriculture' },
    },
    reward: {
      gdpBonus: 1.35,
      budgetBonus: 145,
      inflationModifier: -0.28,
      legacyPoints: 6,
      populationGrowthBonuses: [{ ethnicity: 'Malay', bonus: 0.0008 }, { ethnicity: 'Bumiputera Sabah (Non-Muslim)', bonus: 0.0004 }, { ethnicity: 'Bumiputera Sarawak (Non-Muslim)', bonus: 0.0004 }, { ethnicity: 'Orang Asli', bonus: 0.0004 }, { ethnicity: 'Others', bonus: 0.0004 }],
      structuralBonus: { inequalityReduction: -0.009, infrastructureBoost: 5 },
      flavourText: 'Malaysia overtakes Nigeria as the world\'s top palm oil producer. The price: 2 million hectares of forest, a carbon debt measured in centuries, and an EU-Malaysia trade war that proves unexpectedly costly.',
      historicalNote: 'Malaysia\'s palm oil grew from 0.6M tonnes (1975) to 19.5M tonnes (2019). Malaysia and Indonesia supply 85% of global palm oil. The EU Renewable Energy Directive controversy (2019) cost Malaysia RM3 billion/year in export value.',
    },
  },

  {
    id: 'tiger_t2_electronics_export',
    treeId: 'export_tiger',
    tier: 2,
    category: 'economic',
    icon: '💻',
    name: 'Electronics Export Drive',
    description: 'Target global semiconductor supply chains: attract wafer fabrication alongside assembly. Negotiate technology transfer agreements requiring Malaysian engineers in product design. Create the National Semiconductor R&D Centre in Penang.',
    durationMonths: 26,
    prerequisiteIds: ['tiger_t1_port_development'],
    requirements: {
      description: 'Industry priority, open trade, and human capital.',
      requiredPolicy: { openTrade: true, prioritySector: 'industry' },
      minHumanCapital: 33,
    },
    reward: {
      gdpBonus: 1.55,
      unemploymentBonus: 1.3,
      budgetBonus: 95,
      legacyPoints: 7,
      populationGrowthBonuses: [{ ethnicity: 'Chinese', bonus: 0.0007 }, { ethnicity: 'Indian', bonus: 0.0004 }],
      structuralBonus: { humanCapitalBoost: 9, infrastructureBoost: 5 },
      flavourText: 'Penang is nicknamed "Silicon Island." Intel, AMD, and Infineon run day-and-night shifts. Most R&D still happens in Austin and Munich — but slowly, by design, some of it moves to Penang.',
      historicalNote: 'Electronics became Malaysia\'s largest export category by the 1990s. Intel Penang moved into advanced packaging by 2020 — a genuine step up the value chain after decades of assembly-only work.',
    },
  },

  {
    id: 'tiger_t2_asean_integration',
    treeId: 'export_tiger',
    tier: 2,
    category: 'external',
    icon: '🌏',
    name: 'ASEAN Economic Integration',
    description: 'Champion AFTA tariff elimination and the ASEAN Investment Area. Position Malaysia as the hub of ASEAN financial and logistics flows. Host the ASEAN Secretariat satellite office. Negotiate the ASEAN Plus Three financial cooperation framework.',
    durationMonths: 20,
    prerequisiteIds: ['tiger_t1_tin_boom', 'tiger_t1_port_development'],
    requirements: {
      description: 'Open trade and moderate approval.',
      requiredPolicy: { openTrade: true },
      minApproval: 43,
    },
    reward: {
      gdpBonus: 1.15,
      inflationModifier: -0.38,
      budgetBonus: 85,
      legacyPoints: 6,
      structuralBonus: { corruptionReduction: 4, infrastructureBoost: 7 },
      crossTreeSynergies: [
        {
          beneficiaryTree: 'liberal_open_economy',
          targetMissionId: 'lib_t3_trade_facilitation',
          requirementReduction: 0.2,
          description: 'ASEAN framework creates institutional pressure for national customs modernisation.',
        },
      ],
      flavourText: 'Malaysia chairs ASEAN for the year and turns aspiration into architecture. AFTA reduces intra-ASEAN tariffs to 0-5%. The pan-ASEAN economic corridor flows through Kuala Lumpur.',
      historicalNote: 'Malaysia was a founding ASEAN member (1967) and helped establish AFTA in 1992. Malaysia chaired ASEAN in 2015, pushing the ASEAN Economic Community (AEC) forward.',
    },
  },

  {
    id: 'tiger_t2_halal_industry',
    treeId: 'export_tiger',
    tier: 2,
    category: 'economic',
    icon: '☪️',
    name: 'Global Halal Industry Hub',
    description: 'Establish Malaysia as the world standard-setter for halal certification. Create the Halal Industry Development Corporation (HDC). Build the Malaysia International Halal Showcase (MIHAS). Attract 200 multinational companies to use KL as their global halal headquarters.',
    durationMonths: 18,
    prerequisiteIds: ['tiger_t1_malaysia_airlines', 'tiger_t1_telco_liberalisation'],
    requirements: {
      description: 'Open trade and moderate governance.',
      requiredPolicy: { openTrade: true },
      minApproval: 42,
    },
    reward: {
      gdpBonus: 1.0,
      budgetBonus: 90,
      legacyPoints: 5,
      structuralBonus: { humanCapitalBoost: 5, corruptionReduction: 3 },
      crossTreeSynergies: [
        {
          beneficiaryTree: 'bumiputera_agenda',
          targetMissionId: 'bumi_t2_islamic_finance_seed',
          requirementReduction: 0.2,
          description: 'Halal industry hub creates synergies with Islamic finance development.',
        },
      ],
      flavourText: 'Malaysia captures the US$3 trillion global halal market. Malaysian certification becomes the international gold standard. Multinationals that want to serve Muslim-majority markets route their halal compliance through Kuala Lumpur.',
      historicalNote: 'Malaysia\'s HDC was established 2006. MIHAS became the world\'s largest halal trade fair. Malaysia ranks consistently in the top 3 of the Global Islamic Economy Indicator.',
    },
  },

  {
    id: 'tiger_t2_glc_reform',
    treeId: 'export_tiger',
    tier: 2,
    category: 'institutional',
    icon: '🏢',
    name: 'GLC Transformation Programme',
    description: 'Reform Government-Linked Companies (GLCs): mandate independent boards, transparent remuneration, clear commercial mandates separate from social obligations, and performance targets benchmarked against regional competitors. Privatise loss-making GLCs.',
    durationMonths: 22,
    prerequisiteIds: ['tiger_t1_forex_liberalisation'],
    requirements: {
      description: 'Low corruption and institutional capacity.',
      maxCorruption: 48,
      minApproval: 42,
    },
    reward: {
      gdpBonus: 0.8,
      budgetBonus: 130,
      legacyPoints: 5,
      structuralBonus: { corruptionReduction: 9, humanCapitalBoost: 5 },
      policyUnlock: {
        description: 'Unlocks "GLC Performance Framework" — commercial mandate for state companies',
        unlockedOptions: {},
      },
      crossTreeSynergies: [
        {
          beneficiaryTree: 'developmental_state',
          targetMissionId: 'dev_t2_civil_service_reform',
          requirementReduction: 0.15,
          description: 'GLC reform requires and builds the same institutional capacity as civil service reform.',
        },
      ],
      flavourText: 'GLCs that were loss-making become profitable within three years of governance reform. The lesson applies broadly: most Malaysian state enterprises were underperforming because of governance, not because state ownership is inherently inefficient.',
      historicalNote: 'The Putrajaya GLC Transformation Programme (2004) managed by PCG improved GLC performance metrics significantly. The challenge of separating commercial from political mandates remained perpetual.',
    },
  },

  {
    id: 'tiger_t2_bioeconomy',
    treeId: 'export_tiger',
    tier: 2,
    category: 'economic',
    icon: '🧬',
    name: 'Bioeconomy Initiative',
    description: 'Build a bioeconomy cluster: pharmaceutical manufacturing, medical devices, biotechnology, and agricultural biotech. Establish Biotech Corporation, create a BioNexus Partner Company status with fiscal incentives, and develop the BioValley industrial park in Selangor.',
    durationMonths: 24,
    prerequisiteIds: ['tiger_t2_electronics_export'],
    requirements: {
      description: 'High human capital and R&D capability.',
      minHumanCapital: 45,
      requiredPolicy: { openTrade: true },
    },
    reward: {
      gdpBonus: 1.1,
      unemploymentBonus: 0.9,
      legacyPoints: 6,
      structuralBonus: { humanCapitalBoost: 10, infrastructureBoost: 6, corruptionReduction: 3 },
      crossTreeSynergies: [
        {
          beneficiaryTree: 'socialist_welfare',
          targetMissionId: 'soc_t1_universal_health',
          requirementReduction: 0.15,
          description: 'Domestic pharmaceutical manufacturing reduces medicine import costs for the public health system.',
        },
      ],
      flavourText: 'Malaysian biotech graduates stop emigrating because the jobs are here. COVID-19 vaccine manufacturing capability, built during this period, proves its worth during the pandemic — and commands a geopolitical premium.',
    },
  },

  {
    id: 'tiger_t2_digital_exports',
    treeId: 'export_tiger',
    tier: 2,
    category: 'economic',
    icon: '💾',
    name: 'Digital Services Export',
    description: 'Position Malaysia as an outsourced digital services hub: shared services centres, IT-enabled services, cybersecurity, and data analytics. Target the largest 50 multinationals globally for their APAC back-office functions with a competitive package.',
    durationMonths: 16,
    prerequisiteIds: ['tiger_t1_telco_liberalisation', 'tiger_t1_airasia_lcl'],
    requirements: {
      description: 'Open trade, human capital, and digital infrastructure.',
      requiredPolicy: { openTrade: true },
      minHumanCapital: 38,
    },
    reward: {
      gdpBonus: 0.85,
      unemploymentBonus: 0.9,
      budgetBonus: 70,
      legacyPoints: 4,
      structuralBonus: { humanCapitalBoost: 7, corruptionReduction: 4 },
      flavourText: 'Shell, IBM, and HSBC establish their APAC shared services centres in KL. English-speaking graduates with tech skills find well-paying jobs without emigrating. The digital diaspora starts looking homeward.',
    },
  },

  {
    id: 'tiger_t2_commodity_exchange',
    treeId: 'export_tiger',
    tier: 2,
    category: 'external',
    icon: '📊',
    name: 'Global Commodity Pricing Centre',
    description: 'Establish Bursa Malaysia Derivatives (BMD) as the global benchmark for palm oil and rubber futures. Attract commodity traders, analysts, and investors to base APAC operations in KL. Develop the Malaysian Commodity Price Index as an international reference rate.',
    durationMonths: 18,
    prerequisiteIds: ['tiger_t2_palm_oil', 'tiger_t1_forex_liberalisation'],
    requirements: {
      description: 'High commodity trade and market depth.',
      minCommodityIndex: 105,
      maxCorruption: 42,
    },
    reward: {
      gdpBonus: 0.7,
      budgetBonus: 95,
      legacyPoints: 5,
      structuralBonus: { humanCapitalBoost: 5, corruptionReduction: 5 },
      crossTreeSynergies: [
        {
          beneficiaryTree: 'liberal_open_economy',
          targetMissionId: 'lib_t3_asian_financial_hub',
          requirementReduction: 0.2,
          description: 'Commodity derivatives exchange deepens the capital market ecosystem needed for a financial hub.',
        },
      ],
      flavourText: 'The palm oil price is set in Kuala Lumpur. Malaysia moves from price-taker to price-maker in its primary commodity. The trading floor of BMD becomes the most consequential room in Malaysian commercial life.',
    },
  },

  // ══════════════ TIER 3 — TIGER ASCENT (7 missions) ══════════════

  {
    id: 'tiger_t3_tiger_economy',
    treeId: 'export_tiger',
    tier: 3,
    category: 'legacy',
    icon: '🐯',
    name: 'Asian Tiger Status',
    description: 'Achieve sustained 8%+ GDP growth for a decade — the threshold for "Asian Tiger" designation alongside South Korea, and Taiwan. Build the institutional credibility to sustain the growth trajectory beyond the commodity and FDI-driven phase.',
    durationMonths: 42,
    prerequisiteIds: ['tiger_t2_palm_oil', 'tiger_t2_electronics_export'],
    requirements: {
      description: 'High sustained growth with strong fundamentals.',
      minGdpGrowth: 6.0,
      maxUnemployment: 5.5,
      requiredPolicy: { openTrade: true },
      minInfrastructure: 58,
      minHumanCapital: 53,
    },
    reward: {
      gdpBonus: 2.55,
      unemploymentBonus: 1.55,
      inflationModifier: 0.4,
      budgetBonus: 195,
      approvalBonus: 14,
      legacyPoints: 14,
      populationGrowthBonuses: [{ ethnicity: 'all', bonus: 0.001 }],
      structuralBonus: { humanCapitalBoost: 14, infrastructureBoost: 12, corruptionReduction: 8, inequalityReduction: -0.019 },
      flavourText: 'Economists list Malaysia alongside South Korea, Hong Kong, and Taiwan. The Miracle is real. But it rests on commodity exports and FDI-driven manufacturing — a base that cannot sustain double-digit growth forever.',
      historicalNote: 'Malaysia averaged 8.9% annual growth 1988-1996. The 1997 Asian Financial Crisis interrupted the trajectory; Malaysia never regained that growth rate. GDP per capita stagnated at ~US$10-12,000 from 2010-2020.',
    },
  },

  {
    id: 'tiger_t3_fintech',
    treeId: 'export_tiger',
    tier: 3,
    category: 'economic',
    icon: '🏦',
    name: 'Islamic Fintech & Finance Hub',
    description: 'Develop Islamic finance instruments globally: sukuk, takaful, Islamic REITs, digital banking licences, and a fintech regulatory sandbox. Position Malaysia to serve the 1.8 billion-person global Muslim financial market through Bank Negara\'s comprehensive Islamic finance framework.',
    durationMonths: 30,
    prerequisiteIds: ['tiger_t2_asean_integration', 'tiger_t2_halal_industry'],
    requirements: {
      description: 'Low corruption, open trade, human capital.',
      maxCorruption: 33,
      requiredPolicy: { openTrade: true },
      minHumanCapital: 48,
    },
    reward: {
      gdpBonus: 1.75,
      budgetBonus: 155,
      inflationModifier: -0.22,
      approvalBonus: 8,
      legacyPoints: 9,
      structuralBonus: { corruptionReduction: 9, humanCapitalBoost: 11 },
      policyUnlock: {
        description: 'Unlocks "Islamic Finance Window" — sukuk development financing',
        unlockedOptions: {},
      },
      flavourText: 'Kuala Lumpur becomes the global capital of Islamic finance. Malaysian sukuk bonds circle the world. The distinction between Islamic and conventional finance becomes thinner with each innovation — which is precisely the point.',
      historicalNote: 'Malaysia issues ~50% of global sukuk. Bank Negara\'s Islamic finance liberalisation (2009) established KL as the leading sukuk centre. Maybank Islamic is the world\'s largest Islamic bank by assets.',
    },
  },

  {
    id: 'tiger_t3_commodity_diversification',
    treeId: 'export_tiger',
    tier: 3,
    category: 'economic',
    icon: '🔄',
    name: 'Commodity Diversification',
    description: 'Break dependence on price-volatile primary commodities through downstream processing: palm oleochemicals, rubber gloves and engineering goods, timber furniture, and pharmaceutical raw materials. Mandate 60% value-added before export across all commodity sectors.',
    durationMonths: 32,
    prerequisiteIds: ['tiger_t2_palm_oil', 'tiger_t2_asean_integration'],
    requirements: {
      description: 'Balanced sector focus, open trade, and human capital.',
      requiredPolicy: { openTrade: true, prioritySector: 'balanced' },
      minHumanCapital: 40,
    },
    reward: {
      gdpBonus: 1.15,
      inflationModifier: -0.48,
      budgetBonus: 125,
      legacyPoints: 7,
      structuralBonus: { infrastructureBoost: 10, inequalityReduction: -0.016 },
      populationGrowthBonuses: [{ ethnicity: 'all', bonus: 0.0005 }],
      flavourText: 'Commodity price shocks no longer determine elections. Malaysia\'s rubber glove industry emerges as a global monopoly. The oleochemical complex in Pasir Gudang becomes the most profitable square kilometre in Malaysia.',
      historicalNote: 'Malaysia produces 67% of world rubber gloves. The COVID-19 pandemic created a temporary boom (2020-21) followed by a bust. Oleochemical exports exceeded RM30 billion by 2020.',
    },
  },

  {
    id: 'tiger_t3_semiconductor_design',
    treeId: 'export_tiger',
    tier: 3,
    category: 'economic',
    icon: '🔬',
    name: 'Semiconductor Design Centre',
    description: 'Move Malaysia up the semiconductor value chain from assembly/test to chip design. Establish Design Malaysia, attract fabless design companies, create a PhD programme in microelectronics at UTM and UM, and negotiate technology transfer agreements with ARM and Qualcomm.',
    durationMonths: 36,
    prerequisiteIds: ['tiger_t2_electronics_export', 'tiger_t2_digital_exports'],
    requirements: {
      description: 'High human capital and research capability.',
      minHumanCapital: 58,
      requiredPolicy: { openTrade: true },
      minInfrastructure: 60,
    },
    reward: {
      gdpBonus: 1.8,
      unemploymentBonus: 1.2,
      legacyPoints: 10,
      structuralBonus: { humanCapitalBoost: 14, corruptionReduction: 6, infrastructureBoost: 8 },
      policyUnlock: {
        description: 'Unlocks "Deep Tech Economy" — high-value technology industry policy',
        unlockedOptions: { prioritySector: ['deep_tech'] },
      },
      flavourText: 'Malaysian engineers design chips that end up in Apple iPhones, Tesla cars, and Siemens medical equipment. The value creation happens in Penang now, not just the soldering.',
    },
  },

  {
    id: 'tiger_t3_logistics_hub',
    treeId: 'export_tiger',
    tier: 3,
    category: 'economic',
    icon: '🚛',
    name: 'Regional Logistics Hub',
    description: 'Build Malaysia\'s logistics supremacy: digital free trade zones under Alibaba\'s eHub model, cold chain infrastructure for halal and pharmaceutical exports, autonomous port equipment, and a single ASEAN logistics corridor management system.',
    durationMonths: 28,
    prerequisiteIds: ['tiger_t1_port_development', 'tiger_t2_asean_integration'],
    requirements: {
      description: 'Strong infrastructure and open trade.',
      minInfrastructure: 62,
      requiredPolicy: { openTrade: true },
    },
    reward: {
      gdpBonus: 1.3,
      unemploymentBonus: 0.9,
      budgetBonus: 115,
      legacyPoints: 7,
      structuralBonus: { infrastructureBoost: 15, corruptionReduction: 5 },
      crossTreeSynergies: [
        {
          beneficiaryTree: 'developmental_state',
          targetMissionId: 'dev_t4_sme_digitalisation',
          requirementReduction: 0.2,
          description: 'Logistics digitisation provides the B2B platform for SME e-commerce integration.',
        },
      ],
      flavourText: 'ASEAN e-commerce routes its packages through Malaysian fulfilment centres. Lazada\'s regional headquarters is in KL. The logistics sector employs more workers than manufacturing — and pays better.',
    },
  },

  {
    id: 'tiger_t3_energy_export',
    treeId: 'export_tiger',
    tier: 3,
    category: 'economic',
    icon: '⚡',
    name: 'Energy Export Strategy',
    description: 'Build Malaysia\'s energy export capacity: MLNG expansion, undersea power cables to Thailand and Sumatra, a regional hydrogen export programme, and Malaysia\'s entry into the global LNG spot market as a flexible supplier.',
    durationMonths: 32,
    prerequisiteIds: ['tiger_t3_tiger_economy', 'tiger_t2_glc_reform'],
    requirements: {
      description: 'High commodity production and infrastructure.',
      minCommodityIndex: 110,
      minInfrastructure: 65,
    },
    reward: {
      gdpBonus: 1.5,
      budgetBonus: 190,
      legacyPoints: 8,
      structuralBonus: { infrastructureBoost: 13, corruptionReduction: -3 },
      policyUnlock: {
        description: 'Unlocks "Energy Exporter" strategic export option',
        unlockedOptions: {},
      },
      flavourText: 'Malaysia powers the region. MLNG expansions make Bintulu the LNG capital of Asia. The energy export revenue diversifies what was once purely a commodity price story into a geopolitical one.',
      historicalNote: 'Malaysia is one of the world\'s top 10 LNG exporters. MLNG in Bintulu, Sarawak, was one of Asia\'s first and largest LNG facilities. Sarawak\'s energy export revenues triggered a decades-long dispute with Putrajaya over royalty sharing.',
    },
  },

  {
    id: 'tiger_t3_medical_tourism',
    treeId: 'export_tiger',
    tier: 3,
    category: 'economic',
    icon: '🏥',
    name: 'Medical Tourism Cluster',
    description: 'Position Penang and KL as ASEAN medical tourism destinations: Joint Commission International accreditation for all major hospitals, English-language medical coordination, health screening packages, and direct airline partnerships with source markets.',
    durationMonths: 22,
    prerequisiteIds: ['tiger_t1_malaysia_airlines', 'tiger_t2_digital_exports'],
    requirements: {
      description: 'Services priority and adequate infrastructure.',
      requiredPolicy: { prioritySector: 'services' },
      minHumanCapital: 50,
    },
    reward: {
      gdpBonus: 0.9,
      unemploymentBonus: 0.7,
      budgetBonus: 75,
      legacyPoints: 5,
      structuralBonus: { humanCapitalBoost: 7, infrastructureBoost: 5 },
      flavourText: '1.5 million medical tourists arrive annually. Penang\'s hospitals compete globally on quality and price. Indonesian and Middle Eastern patients who previously flew to Bangkok now fly to Penang. The economic multiplier through hotels, transport, and food is substantial.',
      historicalNote: 'Malaysia attracted 1 million+ medical tourists annually by 2018. Penang\'s Gleneagles and Penang General Hospital became regional benchmarks. Revenue from medical tourism exceeded RM1.9 billion.',
    },
  },

  // ══════════════ TIER 4 — TIGER CONSOLIDATION (6 missions) ══════════════

  {
    id: 'tiger_t4_asean_champion',
    treeId: 'export_tiger',
    tier: 4,
    category: 'legacy',
    icon: '🏆',
    name: 'ASEAN Economic Champion',
    description: 'Cement Malaysia\'s position as ASEAN\'s most diversified and productive economy: high-income status, world-class logistics, global Islamic finance standard, and institutional quality to sustain it. Lead the ASEAN digital single market.',
    durationMonths: 54,
    prerequisiteIds: ['tiger_t3_tiger_economy', 'tiger_t3_fintech', 'tiger_t3_commodity_diversification'],
    requirements: {
      description: 'All economic fundamentals in order.',
      minGdpGrowth: 5.5,
      maxUnemployment: 4.5,
      maxCorruption: 25,
      requiredPolicy: { openTrade: true, prioritySector: 'balanced' },
      minHumanCapital: 68,
      minInfrastructure: 72,
    },
    reward: {
      gdpBonus: 3.2,
      unemploymentBonus: 2.2,
      inflationModifier: -0.55,
      budgetBonus: 250,
      approvalBonus: 14,
      legacyPoints: 32,
      populationGrowthBonuses: [{ ethnicity: 'all', bonus: 0.0014 }],
      structuralBonus: { humanCapitalBoost: 25, infrastructureBoost: 18, corruptionReduction: 20, inequalityReduction: -0.06 },
      flavourText: 'Malaysia achieves what few developing countries have: a diversified, productive, high-income economy. The question is whether it can remain there, or whether middle-income complacency slowly reasserts itself.',
    },
  },

  {
    id: 'tiger_t4_space_industry',
    treeId: 'export_tiger',
    tier: 4,
    category: 'economic',
    icon: '🚀',
    name: 'Space Industry Development',
    description: 'Build Malaysia\'s space industry: satellite manufacturing in Cyberjaya, a ground station network, remote sensing data services, and partnerships with Airbus, Boeing, and SpaceX. Revive the angkasawan programme with a Malaysian on the ISS by 2030.',
    durationMonths: 36,
    prerequisiteIds: ['tiger_t3_semiconductor_design', 'tiger_t3_logistics_hub'],
    requirements: {
      description: 'High human capital and technology capability.',
      minHumanCapital: 65,
      minInfrastructure: 68,
      requiredPolicy: { openTrade: true },
    },
    reward: {
      gdpBonus: 1.2,
      unemploymentBonus: 0.8,
      legacyPoints: 10,
      structuralBonus: { humanCapitalBoost: 13, infrastructureBoost: 8 },
      flavourText: 'Malaysia\'s second angkasawan orbits the ISS while below, the satellite factory in Cyberjaya produces its third commercial satellite for ASEAN governments. Space becomes Malaysia\'s newest export sector.',
      historicalNote: 'Malaysia sent Dr Sheikh Muszaphar Shukor to the ISS in 2007 aboard a Russian Soyuz. The RazakSAT satellite was launched 2009. Malaysia\'s space industry remained small but aspirational.',
    },
  },

  {
    id: 'tiger_t4_water_technology',
    treeId: 'export_tiger',
    tier: 4,
    category: 'economic',
    icon: '💧',
    name: 'Water Technology Export',
    description: 'Develop Malaysia into a global water technology exporter: desalination technology for MENA countries, membrane filtration manufacturing, tropical water treatment expertise, and a Water Technology Centre serving developing countries.',
    durationMonths: 26,
    prerequisiteIds: ['tiger_t3_bioeconomy', 'tiger_t2_glc_reform'],
    requirements: {
      description: 'Technology capability and infrastructure.',
      minHumanCapital: 60,
      minInfrastructure: 64,
    },
    reward: {
      gdpBonus: 0.9,
      budgetBonus: 100,
      legacyPoints: 7,
      structuralBonus: { humanCapitalBoost: 9, infrastructureBoost: 7, corruptionReduction: 5 },
      flavourText: 'Malaysian water technology companies win contracts in Saudi Arabia, India, and East Africa. An industry born of Malaysia\'s own infrastructure challenges turns out to be globally competitive.',
    },
  },

  {
    id: 'tiger_t4_commodity_crash_crisis',
    treeId: 'export_tiger',
    tier: 4,
    category: 'crisis',
    icon: '📉',
    name: 'Commodity Price Collapse',
    description: 'Global commodity prices collapse: palm oil falls 40%, rubber falls 50%, LNG contracts expire. The export revenue that funded development is suddenly unavailable. Crisis management determines whether the tiger economy survives or stalls.',
    durationMonths: 20,
    prerequisiteIds: ['tiger_t3_tiger_economy'],
    requirements: {
      description: 'Triggered by commodity price collapse.',
      crisisTrigger: { gdpBelow: 1.0 },
    },
    reward: {
      gdpBonus: 0.8,
      budgetBonus: -180,
      legacyPoints: -6,
      structuralBonus: { corruptionReduction: -4, humanCapitalBoost: 4 },
      policyUnlock: {
        description: 'Unlocks "Counter-Cyclical Reserve Fund" — sovereign wealth buffer',
        unlockedOptions: { spendingLevel: ['counter_cyclical'] },
      },
      flavourText: 'The commodity cycle has turned against Malaysia. The question is whether twenty years of growth built institutions capable of managing an adverse external shock — or whether the growth was only ever the boom part of a boom-bust cycle.',
    },
  },

  {
    id: 'tiger_t4_net_zero',
    treeId: 'export_tiger',
    tier: 4,
    category: 'economic',
    icon: '🌱',
    name: 'Net Zero Economy Transition',
    description: 'Commit to net zero by 2050, earlier than most regional peers. Develop Malaysia as the ASEAN green bond market centre. Mandate ESG reporting. Issue sovereign green sukuk to fund transition. Create a carbon border adjustment mechanism for Malaysian exports.',
    durationMonths: 38,
    prerequisiteIds: ['tiger_t3_energy_export', 'tiger_t3_commodity_diversification'],
    requirements: {
      description: 'Mature export economy and open trade.',
      minGdpGrowth: 4.0,
      requiredPolicy: { openTrade: true },
      maxCorruption: 35,
    },
    reward: {
      gdpBonus: 1.2,
      budgetBonus: 160,
      legacyPoints: 11,
      structuralBonus: { humanCapitalBoost: 10, infrastructureBoost: 9, corruptionReduction: 7, inequalityReduction: -0.016 },
      flavourText: 'Malaysia becomes the first middle-income tropical country to credibly commit to net zero. The EU drops its tariff threat on Malaysian palm oil. Green finance becomes a competitive advantage rather than a regulatory burden.',
    },
  },

  {
    id: 'tiger_t4_regional_currency',
    treeId: 'export_tiger',
    tier: 4,
    category: 'external',
    icon: '💲',
    name: 'ASEAN Currency Cooperation',
    description: 'Lead the creation of an Asian Currency Unit (ACU) for intra-ASEAN trade settlement. Negotiate a Chiang Mai Initiative Multilateralisation increase. Develop the ringgit as a reserve currency for ASEAN trade, reducing dollar dependency.',
    durationMonths: 30,
    prerequisiteIds: ['tiger_t3_fintech', 'tiger_t2_asean_integration'],
    requirements: {
      description: 'Strong financial markets and regional leadership.',
      minGdpGrowth: 4.5,
      maxCorruption: 30,
      requiredPolicy: { openTrade: true },
    },
    reward: {
      gdpBonus: 1.0,
      budgetBonus: 140,
      inflationModifier: -0.3,
      legacyPoints: 9,
      structuralBonus: { corruptionReduction: 6, humanCapitalBoost: 7 },
      crossTreeSynergies: [
        {
          beneficiaryTree: 'liberal_open_economy',
          targetMissionId: 'lib_t5_regional_integration',
          requirementReduction: 0.25,
          description: 'ASEAN currency cooperation is the financial cornerstone of full economic integration.',
        },
      ],
      flavourText: 'ASEAN trade begins to settle in a basket of regional currencies. Dollar dependency falls from 85% to 55% of intra-ASEAN trade within a decade. Malaysia as the intellectual architect claims a geopolitical dividend.',
    },
  },

  // ══════════════ TIER 5 — TIGER ENDGAME (7 missions) ══════════════

  {
    id: 'tiger_t5_asean_silicon_valley',
    treeId: 'export_tiger',
    tier: 5,
    category: 'legacy',
    icon: '💻',
    name: 'ASEAN Tech Capital',
    description: 'Cement Kuala Lumpur as the technology capital of Southeast Asia: the address of choice for regional tech unicorns, the headquarters of 3+ ASEAN tech giants, and the global centre for Islamic digital finance.',
    durationMonths: 48,
    prerequisiteIds: ['tiger_t4_asean_champion', 'tiger_t3_semiconductor_design'],
    requirements: {
      description: 'Full tech ecosystem and high-income status.',
      minGdpGrowth: 5.0,
      minHumanCapital: 74,
      maxCorruption: 22,
    },
    reward: {
      gdpBonus: 3.0,
      unemploymentBonus: 2.0,
      budgetBonus: 240,
      approvalBonus: 15,
      legacyPoints: 35,
      populationGrowthBonuses: [{ ethnicity: 'all', bonus: 0.0016 }],
      structuralBonus: { humanCapitalBoost: 22, infrastructureBoost: 15, corruptionReduction: 18, inequalityReduction: -0.05 },
      flavourText: 'ASEAN\'s next generation of tech billionaires builds their companies in KL. Penang\'s semiconductor cluster is compared to Taiwan\'s Hsinchu. The tiger economy has grown into something new: a knowledge economy with tiger-era work ethic.',
    },
  },

  {
    id: 'tiger_t5_sovereign_wealth_maturity',
    treeId: 'export_tiger',
    tier: 5,
    category: 'economic',
    icon: '🏦',
    name: 'World-Class Sovereign Wealth Fund',
    description: 'Develop Malaysia\'s sovereign wealth assets into a globally respected fund on par with Norway\'s GPFG: professionalised management, transparent reporting, counter-cyclical investment mandate, and a public-facing annual report.',
    durationMonths: 36,
    prerequisiteIds: ['tiger_t4_net_zero', 'tiger_t4_asean_champion'],
    requirements: {
      description: 'Mature, clean financial institutions.',
      maxCorruption: 22,
      minGdpGrowth: 4.5,
      minBudgetBalance: -100,
    },
    reward: {
      gdpBonus: 1.5,
      budgetBonus: 280,
      legacyPoints: 20,
      structuralBonus: { corruptionReduction: 14, humanCapitalBoost: 10, inequalityReduction: -0.025 },
      flavourText: 'Malaysia\'s sovereign wealth fund publishes its annual report and nobody is surprised by it. That alone is the achievement. Transparency and competence have replaced the secrecy and patronage of 1MDB-era state finance.',
    },
  },

  {
    id: 'tiger_t5_food_tech_revolution',
    treeId: 'export_tiger',
    tier: 5,
    category: 'economic',
    icon: '🌾',
    name: 'AgriFood Technology Revolution',
    description: 'Replace palm oil monoculture with precision agriculture, vertical farming, and alternative protein exports. Malaysia leads the global halal alternative protein market, exporting lab-grown meat certified as halal — the intersection of technology, religion, and food security.',
    durationMonths: 40,
    prerequisiteIds: ['tiger_t4_net_zero', 'tiger_t2_bioeconomy'],
    requirements: {
      description: 'Biotech capability and sustainability transition underway.',
      minHumanCapital: 68,
      requiredPolicy: { openTrade: true, prioritySector: 'balanced' },
    },
    reward: {
      gdpBonus: 1.8,
      inflationModifier: -0.6,
      budgetBonus: 180,
      legacyPoints: 18,
      structuralBonus: { humanCapitalBoost: 14, infrastructureBoost: 10, inequalityReduction: -0.025 },
      flavourText: 'The Impossible Burger of Southeast Asia is made in Penang. Malaysian lab-grown chicken receives global halal certification. The MPOB pivot from palm oil lobbying to precision agriculture advocacy takes a decade — and changes everything.',
    },
  },

  {
    id: 'tiger_t5_demographic_dividend',
    treeId: 'export_tiger',
    tier: 5,
    category: 'social',
    icon: '📊',
    name: 'Demographic Dividend Capture',
    description: 'Maximise Malaysia\'s remaining demographic dividend: invest heavily in youth skills, attract skilled diaspora return, manage the ageing transition proactively, and build a migration policy that maintains workforce growth without compromising wages.',
    durationMonths: 28,
    prerequisiteIds: ['tiger_t5_asean_silicon_valley'],
    requirements: {
      description: 'Strong economy and institutional management.',
      minGdpGrowth: 4.5,
      minHumanCapital: 72,
      maxUnemployment: 5.0,
    },
    reward: {
      gdpBonus: 1.5,
      unemploymentBonus: 1.8,
      legacyPoints: 16,
      populationGrowthBonuses: [{ ethnicity: 'all', bonus: 0.002 }],
      structuralBonus: { humanCapitalBoost: 16, inequalityReduction: -0.03 },
      flavourText: 'The Malaysian diaspora comes home. Not because Malaysia got richer — because it got better. The quality of governance, the rule of law, the dynamism of the economy — these are the magnets for talent.',
    },
  },

  {
    id: 'tiger_t5_external_shock',
    treeId: 'export_tiger',
    tier: 5,
    category: 'crisis',
    icon: '⚠️',
    name: 'Global Supply Chain Disruption',
    description: 'A major geopolitical disruption — US-China decoupling, a pandemic, or a shipping crisis — dislocates the global supply chains that Malaysia depends on. The export model faces its deepest test.',
    durationMonths: 18,
    prerequisiteIds: ['tiger_t3_tiger_economy'],
    requirements: {
      description: 'Triggered by severe external economic shock.',
      crisisTrigger: { gdpBelow: -2.0, unemploymentAbove: 7.0 },
    },
    reward: {
      gdpBonus: 1.0,
      budgetBonus: -140,
      legacyPoints: -4,
      structuralBonus: { humanCapitalBoost: 6, infrastructureBoost: 4 },
      policyUnlock: {
        description: 'Unlocks "Supply Chain Resilience Fund" — domestic manufacturing incentive',
        unlockedOptions: {},
      },
      flavourText: 'The disruption tests every assumption of the export model. Malaysia\'s diversified economy is more resilient than Thailand\'s; less resilient than Taiwan\'s. The result is mixed — which is a kind of success.',
    },
  },

  {
    id: 'tiger_t5_creative_export',
    treeId: 'export_tiger',
    tier: 5,
    category: 'economic',
    icon: '🎨',
    name: 'Cultural and Creative Exports',
    description: 'Develop Malaysian cultural exports: film and animation for Islamic markets globally, Malaysian cuisine as a global food brand, fashion and design exports, and architecture consultancy in the Middle East.',
    durationMonths: 30,
    prerequisiteIds: ['tiger_t5_asean_silicon_valley'],
    requirements: {
      description: 'High-income society with cultural confidence.',
      minHumanCapital: 70,
      minApproval: 55,
    },
    reward: {
      gdpBonus: 0.8,
      approvalBonus: 10,
      legacyPoints: 14,
      populationGrowthBonuses: [{ ethnicity: 'all', bonus: 0.001 }],
      structuralBonus: { humanCapitalBoost: 10, inequalityReduction: -0.018 },
      flavourText: 'Malaysian nasi lemak is cooked in restaurant chains in 40 countries. Upin & Ipin is watched in Indonesia, Turkey, and Nigeria. Malaysian architects design mosques in Dubai. Culture turns out to be an export industry.',
    },
  },
];

export { EXPORT_TIGER_MISSIONS };
