// ─────────────────────────────────────────────────────────────
// TREE 4: SOCIALIST WELFARE STATE — 35 MISSIONS, 5 TIERS
// ─────────────────────────────────────────────────────────────

const SOCIALIST_MISSIONS = [
  // ══════════════ TIER 1 — WELFARE FOUNDATIONS (7 missions) ══════════════

  {
    id: 'soc_t1_universal_health',
    treeId: 'socialist_welfare',
    tier: 1,
    category: 'social',
    icon: '🏥',
    name: 'Universal Healthcare',
    description: 'Expand public hospitals and rural health clinics to guarantee subsidised healthcare for all citizens. Build 200 new KLINIK KESIHATAN in underserved areas. Mandate a 1:5,000 doctor-to-population ratio nationwide within 10 years. Prioritise estate Indian and Orang Asli communities with mobile clinic services.',
    durationMonths: 16,
    prerequisiteIds: [],
    requirements: {
      description: 'Generous welfare commitment.',
      requiredPolicy: { welfareLevel: 'generous' },
    },
    reward: {
      approvalBonus: 8,
      unemploymentBonus: 0.3,
      legacyPoints: 5,
      populationGrowthBonuses: [{ ethnicity: 'all', bonus: 0.001 }, { ethnicity: 'Indian', bonus: 0.0006 }],
      structuralBonus: { humanCapitalBoost: 7, inequalityReduction: -0.014 },
      flavourText: 'Clinics open in estates and squatter settlements. Maternal mortality falls 40% in five years. The political return on public health investment is enormous — healthy workers are productive workers.',
      historicalNote: 'Malaysia\'s public health system is exceptional for its income level. Specialist care at government hospitals costs RM1 (subsidised). This was a deliberate development choice from independence, representing genuine state investment in human capital.',
    },
  },

  {
    id: 'soc_t1_labour_rights',
    treeId: 'socialist_welfare',
    tier: 1,
    category: 'social',
    icon: '✊',
    name: 'Labour Rights Act',
    description: 'Legalise independent trade unions in all private sectors including electronics. Set a national minimum wage at RM1,500/month. Mandate safe working conditions with independent factory inspections. Restrict child labour and implement the ILO core conventions. Extend the Industrial Relations Act to all workers regardless of nationality.',
    durationMonths: 12,
    prerequisiteIds: [],
    requirements: {
      description: 'Generous welfare and moderate or high taxes.',
      requiredPolicy: { welfareLevel: 'generous' },
    },
    reward: {
      unemploymentBonus: 0.45,
      inflationModifier: 0.35,
      approvalBonus: 6,
      legacyPoints: 4,
      populationGrowthBonuses: [{ ethnicity: 'Indian', bonus: 0.0009 }, { ethnicity: 'Chinese', bonus: 0.0004 }],
      structuralBonus: { inequalityReduction: -0.019 },
      crossTreeSynergies: [
        {
          beneficiaryTree: 'federal_pluralism',
          targetMissionId: 'fed_t2_interethnic_accord',
          requirementReduction: 0.1,
          description: 'Labour rights create a cross-ethnic working-class solidarity that supports ethnic economic accords.',
        },
      ],
      flavourText: 'Workers march through Kuala Lumpur. The minimum wage is law. Businesses warn of job losses; most do not materialise. Estate workers who had lived under a feudal wage structure finally enter the Malaysian labour market on equal terms.',
      historicalNote: 'Malaysia\'s Industrial Relations Act 1967 severely restricted union rights. A national minimum wage was only introduced in 2013 at RM900/month. The 2022 increase to RM1,500 was decades overdue.',
    },
  },

  {
    id: 'soc_t1_land_nationalisation',
    treeId: 'socialist_welfare',
    tier: 1,
    category: 'economic',
    icon: '🌿',
    name: 'Plantation Nationalisation',
    description: 'Bring colonial rubber and palm oil estates into public or worker cooperative ownership through a Compulsory Purchase and Compensation scheme. Redistribute profits to workers who have laboured on the land for generations. Retain estate managers as employees rather than absentee owners.',
    durationMonths: 20,
    prerequisiteIds: [],
    requirements: {
      description: 'High taxes and expansionary spending.',
      requiredPolicy: { taxRate: 'high', spendingLevel: 'expansionary' },
    },
    reward: {
      gdpBonus: 0.28,
      budgetBonus: 75,
      legacyPoints: 4,
      populationGrowthBonuses: [{ ethnicity: 'Indian', bonus: 0.001 }, { ethnicity: 'Malay', bonus: 0.0006 }],
      structuralBonus: { inequalityReduction: -0.024 },
      crossTreeSynergies: [
        {
          beneficiaryTree: 'bumiputera_agenda',
          targetMissionId: 'bumi_t1_land_reform',
          requirementReduction: 0.15,
          description: 'Nationalisation provides the state land bank that facilitates Bumiputera land redistribution.',
        },
      ],
      flavourText: 'Generations of Tamil estate workers finally own a share of the land they work. Foreign plantation companies receive compensation and mostly reinvest in Indonesia instead. The production quality stays the same. The dignity changes everything.',
    },
  },

  {
    id: 'soc_t1_free_public_transport',
    treeId: 'socialist_welfare',
    tier: 1,
    category: 'social',
    icon: '🚌',
    name: 'Free Public Transport Initiative',
    description: 'Introduce free public transport for students, senior citizens, and disabled persons on all Rapid KL and Rapid Penang services. Subsidise a 50% reduction in commuter rail fares. Build the first integrated bus network in Klang Valley with real-time tracking.',
    durationMonths: 10,
    prerequisiteIds: [],
    requirements: {
      description: 'Generous welfare and adequate budget.',
      requiredPolicy: { welfareLevel: 'generous' },
      minBudgetBalance: -200,
    },
    reward: {
      approvalBonus: 7,
      legacyPoints: 3,
      structuralBonus: { inequalityReduction: -0.01, humanCapitalBoost: 2 },
      populationGrowthBonuses: [{ ethnicity: 'all', bonus: 0.0003 }],
      flavourText: 'Students who could not afford transport to school can now go every day. Senior citizens reclaim mobility. The bus network, neglected for decades in favour of highway construction, is suddenly treated as serious infrastructure.',
    },
  },

  {
    id: 'soc_t1_living_wage',
    treeId: 'socialist_welfare',
    tier: 1,
    category: 'social',
    icon: '💵',
    name: 'Living Wage Standard',
    description: 'Establish a Living Wage Commission to calculate the true cost of living in different regions. Mandate Living Wage certification for all government contractors. Introduce tax credits for employers who pay Living Wage to full-time workers.',
    durationMonths: 13,
    prerequisiteIds: ['soc_t1_labour_rights'],
    requirements: {
      description: 'Labour rights foundation and moderate governance.',
      minApproval: 38,
    },
    reward: {
      gdpBonus: 0.35,
      unemploymentBonus: 0.3,
      approvalBonus: 5,
      legacyPoints: 3,
      structuralBonus: { inequalityReduction: -0.016, humanCapitalBoost: 3 },
      flavourText: 'The Living Wage standard reveals what workers always knew: the minimum wage is below the minimum needed to live. The gap between the two is a policy choice — and now a named one.',
    },
  },

  {
    id: 'soc_t1_food_security',
    treeId: 'socialist_welfare',
    tier: 1,
    category: 'social',
    icon: '🍚',
    name: 'National Food Security Programme',
    description: 'Establish a National Food Security Council. Introduce food price stabilisation for rice, cooking oil, sugar, and flour. Build strategic food reserves of six months. Support community gardens and urban farming in low-income neighbourhoods.',
    durationMonths: 11,
    prerequisiteIds: [],
    requirements: {
      description: 'Adequate budget and agricultural priority.',
      minBudgetBalance: -250,
    },
    reward: {
      inflationModifier: -0.5,
      approvalBonus: 6,
      legacyPoints: 2,
      populationGrowthBonuses: [{ ethnicity: 'all', bonus: 0.0004 }],
      structuralBonus: { inequalityReduction: -0.009 },
      flavourText: 'Food prices stabilise. The poorest Malaysian households — who spend 40% of income on food — experience a genuine improvement in living standards. The strategic reserve is the insurance policy that markets never provide.',
    },
  },

  {
    id: 'soc_t1_social_housing_first',
    treeId: 'socialist_welfare',
    tier: 1,
    category: 'social',
    icon: '🏠',
    name: 'Housing First Programme',
    description: 'Adopt the Housing First approach to homelessness: provide unconditional housing before requiring treatment, sobriety, or employment. Partner with NGOs for support services. Convert unused government buildings into transitional housing within 90 days.',
    durationMonths: 9,
    prerequisiteIds: ['soc_t1_universal_health'],
    requirements: {
      description: 'Generous welfare and social commitment.',
      requiredPolicy: { welfareLevel: 'generous' },
    },
    reward: {
      approvalBonus: 4,
      legacyPoints: 2,
      structuralBonus: { inequalityReduction: -0.008, humanCapitalBoost: 2 },
      populationGrowthBonuses: [{ ethnicity: 'all', bonus: 0.0003 }],
      crossTreeSynergies: [
        {
          beneficiaryTree: 'federal_pluralism',
          targetMissionId: 'fed_t2_regional_development',
          requirementReduction: 0.1,
          description: 'Housing first approach creates a model for regional housing-led development.',
        },
      ],
      flavourText: 'Malaysia becomes the first country in Southeast Asia to adopt Housing First. The evidence is clear: stable housing reduces healthcare costs, criminal justice costs, and lost productivity. It is cheaper than homelessness.',
    },
  },

  // ══════════════ TIER 2 — WELFARE STATE CONSTRUCTION (8 missions) ══════════════

  {
    id: 'soc_t2_public_housing',
    treeId: 'socialist_welfare',
    tier: 2,
    category: 'social',
    icon: '🏘️',
    name: 'Mass Public Housing',
    description: 'State-led construction of 500,000 affordable PPR (Projek Perumahan Rakyat) units at subsidised rents. Build integrated communities with schools, clinics, and parks. Apply a mixed-income model — 30% private units cross-subsidise 70% affordable — to avoid social housing stigma.',
    durationMonths: 28,
    prerequisiteIds: ['soc_t1_universal_health', 'soc_t1_social_housing_first'],
    requirements: {
      description: 'Expansionary spending and infrastructure foundation.',
      requiredPolicy: { spendingLevel: 'expansionary' },
      minInfrastructure: 28,
    },
    reward: {
      gdpBonus: 0.65,
      unemploymentBonus: 0.8,
      approvalBonus: 10,
      legacyPoints: 6,
      populationGrowthBonuses: [{ ethnicity: 'all', bonus: 0.0007 }, { ethnicity: 'Malay', bonus: 0.0006 }],
      structuralBonus: { infrastructureBoost: 9, inequalityReduction: -0.019 },
      flavourText: 'Tower blocks rise around Kuala Lumpur. Families leave tin-roofed squatter settlements for permanent homes. The new flats create their own social issues, but having a roof over your head is not optional.',
      historicalNote: 'Malaysia built over 100,000 PPR units between 1998 and 2010 at rents of RM124-RM250/month. The units were heavily oversubscribed. Maintenance funding remained a perpetual challenge.',
    },
  },

  {
    id: 'soc_t2_cooperatives',
    treeId: 'socialist_welfare',
    tier: 2,
    category: 'economic',
    icon: '🌾',
    name: 'Cooperative Economy',
    description: 'Establish 500 new worker and agricultural cooperatives with startup grants, tax exemptions, and technical assistance. Create a Cooperative Development Bank. Mandate that government food procurement prioritises cooperatives over commercial suppliers.',
    durationMonths: 22,
    prerequisiteIds: ['soc_t1_labour_rights', 'soc_t1_land_nationalisation'],
    requirements: {
      description: 'Generous welfare and human capital.',
      requiredPolicy: { welfareLevel: 'generous' },
      minHumanCapital: 28,
    },
    reward: {
      gdpBonus: 0.55,
      unemploymentBonus: 1.0,
      legacyPoints: 5,
      structuralBonus: { inequalityReduction: -0.028, humanCapitalBoost: 5 },
      policyUnlock: {
        description: 'Unlocks "Cooperative Priority" sector focus',
        unlockedOptions: { prioritySector: ['cooperative'] },
      },
      flavourText: 'FELDA villages become self-governing cooperatives. The cooperative retail network cuts the cost of living for rural households. The model is not as spectacular as state capitalism — and considerably less corrupt.',
    },
  },

  {
    id: 'soc_t2_free_education',
    treeId: 'socialist_welfare',
    tier: 2,
    category: 'social',
    icon: '📚',
    name: 'Free Universal Education',
    description: 'Abolish all school fees from kindergarten through Form 5. Provide free meals, uniforms, textbooks, and transport. Build 300 new schools in underserved rural and estate communities. Raise teacher salaries to match civil service grade 41.',
    durationMonths: 18,
    prerequisiteIds: ['soc_t1_land_nationalisation'],
    requirements: {
      description: 'High taxes to fund universalism.',
      requiredPolicy: { taxRate: 'high' },
    },
    reward: {
      unemploymentBonus: 0.65,
      budgetBonus: -120,
      legacyPoints: 6,
      populationGrowthBonuses: [{ ethnicity: 'all', bonus: 0.001 }, { ethnicity: 'Indian', bonus: 0.0008 }],
      structuralBonus: { humanCapitalBoost: 12, inequalityReduction: -0.019 },
      crossTreeSynergies: [
        {
          beneficiaryTree: 'federal_pluralism',
          targetMissionId: 'fed_t2_language_rights',
          requirementReduction: 0.15,
          description: 'Universal education funding creates the fiscal space for multilingual schooling.',
        },
      ],
      flavourText: 'No child goes without schooling. Literacy climbs past 97%. The quality gap between urban and estate schools remains vast — but it narrows for the first time in a generation.',
    },
  },

  {
    id: 'soc_t2_mental_health',
    treeId: 'socialist_welfare',
    tier: 2,
    category: 'social',
    icon: '🧠',
    name: 'National Mental Health Programme',
    description: 'Establish community mental health centres in every parliamentary constituency. Train 2,000 counsellors for school deployment. Launch a national destigmatisation campaign. Provide free psychiatric medication under the national formulary. Create a Mental Health Act replacing the outdated 1952 ordinance.',
    durationMonths: 14,
    prerequisiteIds: ['soc_t1_universal_health'],
    requirements: {
      description: 'Adequate healthcare budget.',
      requiredPolicy: { welfareLevel: 'generous' },
      minBudgetBalance: -220,
    },
    reward: {
      approvalBonus: 6,
      unemploymentBonus: 0.4,
      legacyPoints: 4,
      populationGrowthBonuses: [{ ethnicity: 'all', bonus: 0.0005 }],
      structuralBonus: { humanCapitalBoost: 6, inequalityReduction: -0.01 },
      flavourText: 'Mental illness is treated as illness. The suicide rate falls. Worker productivity in industries with EAP programmes rises 12%. The invisible burden of untreated mental suffering, always expensive in the end, becomes visible — and addressed.',
    },
  },

  {
    id: 'soc_t2_disability_rights',
    treeId: 'socialist_welfare',
    tier: 2,
    category: 'social',
    icon: '♿',
    name: 'Persons with Disabilities Act',
    description: 'Enact a comprehensive Persons with Disabilities Act with enforcement: mandatory accessibility in all new buildings, a 1% employment quota for large employers, disability-inclusive education as a right, and an Independent Living Fund managed by disabled people.',
    durationMonths: 12,
    prerequisiteIds: ['soc_t1_labour_rights'],
    requirements: {
      description: 'Moderate welfare and governance.',
      minApproval: 38,
    },
    reward: {
      approvalBonus: 5,
      unemploymentBonus: 0.25,
      legacyPoints: 3,
      structuralBonus: { humanCapitalBoost: 4, inequalityReduction: -0.008 },
      flavourText: '500,000 Malaysians with disabilities enter the formal economy for the first time. The productivity gain is real; so is the dignity. Ramps appear on every government building within three years.',
    },
  },

  {
    id: 'soc_t2_nationalised_utilities',
    treeId: 'socialist_welfare',
    tier: 2,
    category: 'economic',
    icon: '💡',
    name: 'Public Utilities Nationalisation',
    description: 'Renationalise privatised water and electricity utilities into public ownership under a statutory authority model. Freeze tariffs for low-income households. Mandate 100% rural electrification and piped water access within 5 years.',
    durationMonths: 20,
    prerequisiteIds: ['soc_t1_land_nationalisation'],
    requirements: {
      description: 'High taxes and expansionary spending.',
      requiredPolicy: { taxRate: 'high', spendingLevel: 'expansionary' },
      minBudgetBalance: -350,
    },
    reward: {
      gdpBonus: 0.4,
      approvalBonus: 8,
      budgetBonus: -100,
      legacyPoints: 5,
      structuralBonus: { infrastructureBoost: 11, inequalityReduction: -0.015 },
      policyUnlock: {
        description: 'Unlocks "Public Utility Pricing" — cost-of-service tariff setting',
        unlockedOptions: {},
      },
      flavourText: 'Water and electricity become public goods once more. Tariff shocks that devastated low-income households end. The efficiency gains of privatisation were real; so were the distributional costs. The balance shifts.',
      historicalNote: 'Malaysia\'s water privatisation in the 1990s led to tariff increases and service disruptions. The Selangor water crisis of 2014 forced a costly renationalisation. Utilities privatisation created as many problems as it solved.',
    },
  },

  {
    id: 'soc_t2_migrant_worker_rights',
    treeId: 'socialist_welfare',
    tier: 2,
    category: 'social',
    icon: '🧑‍🤝‍🧑',
    name: 'Migrant Worker Protection',
    description: 'Extend full labour rights to the 2+ million migrant workers: end the employer-tied permit system, mandate free workers\' accommodation, create a Migrant Worker Tribunal, and ratify the UN International Convention on the Rights of Migrant Workers.',
    durationMonths: 16,
    prerequisiteIds: ['soc_t1_labour_rights', 'soc_t1_living_wage'],
    requirements: {
      description: 'Genuine labour rights commitment.',
      requiredPolicy: { welfareLevel: 'generous' },
      minApproval: 40,
    },
    reward: {
      gdpBonus: 0.3,
      approvalBonus: 4,
      inflationModifier: 0.25,
      legacyPoints: 5,
      structuralBonus: { humanCapitalBoost: 3, inequalityReduction: -0.014, corruptionReduction: 5 },
      flavourText: 'Two million migrant workers gain legal protection they never had. Some employers raise prices; others invest in automation. The moral clarity of treating all workers as workers regardless of nationality has an economic logic.',
      historicalNote: 'Malaysia has 2-4 million documented migrant workers and an unknown number of undocumented. Documented abuses include passport confiscation, wage theft, and sexual exploitation. Reforms have been promised by successive governments; enforcement remains weak.',
    },
  },

  {
    id: 'soc_t2_childcare_expansion',
    treeId: 'socialist_welfare',
    tier: 2,
    category: 'social',
    icon: '👶',
    name: 'Universal Childcare',
    description: 'Establish 1,000 government subsidised childcare centres (TASKA) in every town. Mandate workplace creches for companies over 100 employees. Provide free childcare for children of single parents and low-income households.',
    durationMonths: 15,
    prerequisiteIds: ['soc_t1_universal_health', 'soc_t1_living_wage'],
    requirements: {
      description: 'Generous welfare commitment.',
      requiredPolicy: { welfareLevel: 'generous' },
      minBudgetBalance: -180,
    },
    reward: {
      unemploymentBonus: 0.6,
      approvalBonus: 7,
      legacyPoints: 4,
      populationGrowthBonuses: [{ ethnicity: 'all', bonus: 0.0008 }],
      structuralBonus: { humanCapitalBoost: 7, inequalityReduction: -0.016 },
      flavourText: 'Women\'s labour force participation rises from 55% to 65%. The GDP effect of this single policy exceeds all the projections. Childcare turns out to be the most efficient investment in human capital Malaysia has ever made.',
    },
  },

  // ══════════════ TIER 3 — COMPREHENSIVE WELFARE (7 missions) ══════════════

  {
    id: 'soc_t3_peoples_economy',
    treeId: 'socialist_welfare',
    tier: 3,
    category: 'economic',
    icon: '⚙️',
    name: "People's Economy",
    description: 'Complete the democratic socialist transformation: state enterprises in strategic sectors, co-determination (worker board representation), 40% top income tax rate, wealth tax on assets over RM5 million, and comprehensive Worker Investment Funds.',
    durationMonths: 40,
    prerequisiteIds: ['soc_t2_public_housing', 'soc_t2_cooperatives'],
    requirements: {
      description: 'High approval with strong welfare and high taxes.',
      minApproval: 54,
      requiredPolicy: { welfareLevel: 'generous', taxRate: 'high' },
    },
    reward: {
      gdpBonus: 0.85,
      unemploymentBonus: 1.75,
      inflationModifier: 0.55,
      approvalBonus: 13,
      legacyPoints: 12,
      populationGrowthBonuses: [{ ethnicity: 'all', bonus: 0.0011 }, { ethnicity: 'Indian', bonus: 0.001 }],
      structuralBonus: { inequalityReduction: -0.048, humanCapitalBoost: 11, infrastructureBoost: 9 },
      flavourText: 'Malaysia becomes one of the most equal societies in Asia. Poverty is no longer a mass condition. But capital flight abroad accelerates — the enduring tension of redistribution in a small open economy.',
    },
  },

  {
    id: 'soc_t3_rainforest_protection',
    treeId: 'socialist_welfare',
    tier: 3,
    category: 'social',
    icon: '🌳',
    name: 'Rainforest Protection Act',
    description: 'Halt commercial deforestation above 50% forest cover floor. Recognise Orang Asli and indigenous Borneo customary land rights under the National Land Code. Create a Sustainable Forestry Concession system. Establish a RM2 billion Green Fund for conservation and ecotourism.',
    durationMonths: 26,
    prerequisiteIds: ['soc_t2_cooperatives', 'soc_t2_free_education'],
    requirements: {
      description: 'Human capital and cooperative economy foundation.',
      minHumanCapital: 47,
    },
    reward: {
      gdpBonus: 0.35,
      inflationModifier: -0.28,
      budgetBonus: 55,
      approvalBonus: 8,
      legacyPoints: 7,
      populationGrowthBonuses: [{ ethnicity: 'Bumiputera Sabah (Non-Muslim)', bonus: 0.0011 }, { ethnicity: 'Bumiputera Sarawak (Non-Muslim)', bonus: 0.0011 }, { ethnicity: 'Orang Asli', bonus: 0.0011 }, { ethnicity: 'Others', bonus: 0.0011 }, { ethnicity: 'Bumiputera Sabah (Non-Muslim)', bonus: 0.001 }, { ethnicity: 'Bumiputera Sarawak (Non-Muslim)', bonus: 0.001 }],
      structuralBonus: { inequalityReduction: -0.018, corruptionReduction: 5 },
      crossTreeSynergies: [
        {
          beneficiaryTree: 'federal_pluralism',
          targetMissionId: 'fed_t2_borneo_rights',
          requirementReduction: 0.25,
          description: 'Indigenous land rights recognition creates a legal template for Borneo customary territory.',
        },
      ],
      flavourText: 'The jungle stays. Orang Asli titles are recognised for the first time in Malaysian legal history. Carbon credit and ecotourism revenues open new income streams. The forest turns out to be more valuable standing than felled.',
      historicalNote: 'Peninsular Malaysia retains ~54% forest cover but faces plantation pressure. Sarawak lost over 30% of primary forest between 1990-2010. Orang Asli customary land rights remain legally unresolved despite decades of activism.',
    },
  },

  {
    id: 'soc_t3_full_employment',
    treeId: 'socialist_welfare',
    tier: 3,
    category: 'economic',
    icon: '👷',
    name: 'Full Employment Guarantee',
    description: 'Establish a Job Guarantee programme: anyone who wants to work gets a job at the living wage building public goods — green infrastructure, ecological restoration, schools, and elder care. Financed through a Financial Transaction Tax and progressive income tax.',
    durationMonths: 34,
    prerequisiteIds: ['soc_t2_public_housing', 'soc_t2_free_education'],
    requirements: {
      description: 'Expansionary spending with manageable deficit.',
      requiredPolicy: { spendingLevel: 'expansionary' },
      minBudgetBalance: -550,
    },
    reward: {
      unemploymentBonus: 3.2,
      inflationModifier: 1.1,
      approvalBonus: 12,
      budgetBonus: -165,
      legacyPoints: 8,
      populationGrowthBonuses: [{ ethnicity: 'all', bonus: 0.001 }],
      structuralBonus: { infrastructureBoost: 13, humanCapitalBoost: 9 },
      flavourText: 'No one who wants to work goes without. Roads, schools, and clinics get built. Inflation rises and the fiscal position deteriorates — the central tension of the demand-managed welfare state is now lived rather than theorised.',
    },
  },

  {
    id: 'soc_t3_social_insurance',
    treeId: 'socialist_welfare',
    tier: 3,
    category: 'social',
    icon: '🛡️',
    name: 'Comprehensive Social Insurance',
    description: 'Create a unified National Social Insurance system replacing fragmented schemes: unemployment insurance (6 months), sickness benefit, maternity pay (6 months at full pay), disability pension, and a carer\'s allowance for informal caregivers.',
    durationMonths: 24,
    prerequisiteIds: ['soc_t2_mental_health', 'soc_t2_childcare_expansion'],
    requirements: {
      description: 'Generous welfare and high taxes.',
      requiredPolicy: { welfareLevel: 'generous', taxRate: 'high' },
      minApproval: 48,
    },
    reward: {
      gdpBonus: 0.5,
      approvalBonus: 10,
      legacyPoints: 8,
      budgetBonus: -90,
      populationGrowthBonuses: [{ ethnicity: 'all', bonus: 0.0009 }],
      structuralBonus: { humanCapitalBoost: 8, inequalityReduction: -0.022 },
      flavourText: 'Illness, disability, and parenthood no longer threaten financial ruin. The social insurance system is the invisible infrastructure of a confident workforce — people take productive risks because failure doesn\'t mean catastrophe.',
    },
  },

  {
    id: 'soc_t3_wealth_redistribution',
    treeId: 'socialist_welfare',
    tier: 3,
    category: 'economic',
    icon: '⚖️',
    name: 'Wealth Redistribution Tax',
    description: 'Introduce a progressive wealth tax on assets above RM1 million, an inheritance tax above RM3 million, and a land value tax on undeveloped urban land. Ring-fence proceeds for a Universal Basic Investment Fund giving every citizen RM10,000 at age 21.',
    durationMonths: 22,
    prerequisiteIds: ['soc_t3_peoples_economy'],
    requirements: {
      description: 'Strong redistributive mandate.',
      minApproval: 50,
      requiredPolicy: { taxRate: 'high' },
    },
    reward: {
      gdpBonus: 0.4,
      budgetBonus: 180,
      approvalBonus: 7,
      legacyPoints: 9,
      structuralBonus: { inequalityReduction: -0.038, corruptionReduction: 3 },
      flavourText: 'Every Malaysian turns 21 with RM10,000 in their Universal Investment Account. The dynastic concentration of wealth that was quietly entrenching itself begins to erode. The intergenerational equity debate is won by demonstration.',
    },
  },

  {
    id: 'soc_t3_gender_equality',
    treeId: 'socialist_welfare',
    tier: 3,
    category: 'social',
    icon: '⚤',
    name: 'Gender Equality Act',
    description: 'Enact a comprehensive Gender Equality Act: mandatory gender pay gap reporting, 30% minimum female representation on all public company boards and government agencies, criminalize gender discrimination in hiring, and a National Action Plan on Gender-Based Violence.',
    durationMonths: 18,
    prerequisiteIds: ['soc_t2_childcare_expansion', 'soc_t2_disability_rights'],
    requirements: {
      description: 'Moderate approval and welfare commitment.',
      minApproval: 44,
      requiredPolicy: { welfareLevel: 'generous' },
    },
    reward: {
      gdpBonus: 0.45,
      unemploymentBonus: 0.5,
      approvalBonus: 8,
      legacyPoints: 6,
      populationGrowthBonuses: [{ ethnicity: 'all', bonus: 0.0007 }],
      structuralBonus: { humanCapitalBoost: 8, inequalityReduction: -0.02 },
      flavourText: 'Women\'s participation in the formal economy and public life changes what is possible. The GDP effect is the least interesting thing about it.',
    },
  },

  {
    id: 'soc_t3_prison_reform',
    treeId: 'socialist_welfare',
    tier: 3,
    category: 'social',
    icon: '🔓',
    name: 'Criminal Justice Reform',
    description: 'Replace mandatory minimum sentences with judicial discretion. Abolish the death penalty for drug offences. Create a Restorative Justice programme. Build reintegration facilities to reduce recidivism by 50%. Decriminalise minor drug possession for personal use.',
    durationMonths: 20,
    prerequisiteIds: ['soc_t2_mental_health', 'soc_t1_universal_health'],
    requirements: {
      description: 'Reform mandate and moderate approval.',
      minApproval: 46,
      maxCorruption: 48,
    },
    reward: {
      approvalBonus: 5,
      legacyPoints: 5,
      structuralBonus: { humanCapitalBoost: 6, corruptionReduction: 4, inequalityReduction: -0.012 },
      flavourText: 'The prison population falls by 30%. Recidivism halves. The fiscal saving on incarceration exceeds the cost of reintegration programmes by a factor of four. Justice and economics align, briefly, on the same side.',
    },
  },

  // ══════════════ TIER 4 — MATURE WELFARE STATE (6 missions) ══════════════

  {
    id: 'soc_t4_just_transition',
    treeId: 'socialist_welfare',
    tier: 4,
    category: 'legacy',
    icon: '🌱',
    name: 'Just Green Transition',
    description: 'Phase out palm oil monoculture, transition to a bioeconomy, introduce carbon pricing at RM50/tonne, and invest green infrastructure revenues in worker retraining. A planned decarbonisation that protects livelihoods throughout the transition.',
    durationMonths: 60,
    prerequisiteIds: ['soc_t3_peoples_economy', 'soc_t3_rainforest_protection'],
    requirements: {
      description: 'Strong human capital, low inequality, stable governance.',
      minHumanCapital: 58,
      minApproval: 56,
      requiredPolicy: { welfareLevel: 'generous' },
    },
    reward: {
      gdpBonus: 1.1,
      unemploymentBonus: 1.2,
      inflationModifier: -0.6,
      budgetBonus: 140,
      approvalBonus: 10,
      legacyPoints: 25,
      populationGrowthBonuses: [{ ethnicity: 'all', bonus: 0.001 }],
      structuralBonus: { humanCapitalBoost: 16, infrastructureBoost: 14, inequalityReduction: -0.06, corruptionReduction: 10 },
      flavourText: 'Malaysia becomes a model for how developing countries decarbonise without sacrificing equity. The transition is neither painless nor perfect — but it is managed, planned, and humane.',
    },
  },

  {
    id: 'soc_t4_ubi',
    treeId: 'socialist_welfare',
    tier: 4,
    category: 'social',
    icon: '💰',
    name: 'Universal Basic Income Pilot',
    description: 'Launch a RM800/month Universal Basic Income pilot in 10 parliamentary constituencies over 3 years. Measure effects on employment, health, education, and mental wellbeing. Design the fiscal pathway for nationwide rollout funded by wealth taxes and carbon pricing.',
    durationMonths: 36,
    prerequisiteIds: ['soc_t3_social_insurance', 'soc_t3_wealth_redistribution'],
    requirements: {
      description: 'Strong welfare state and fiscal capacity.',
      requiredPolicy: { welfareLevel: 'generous', taxRate: 'high' },
      minBudgetBalance: -200,
      minApproval: 52,
    },
    reward: {
      gdpBonus: 0.6,
      approvalBonus: 12,
      legacyPoints: 10,
      populationGrowthBonuses: [{ ethnicity: 'all', bonus: 0.0011 }],
      structuralBonus: { inequalityReduction: -0.03, humanCapitalBoost: 9 },
      policyUnlock: {
        description: 'Unlocks "Universal Basic Income" — transformative welfare option',
        unlockedOptions: { welfareLevel: ['universal_basic_income'] },
      },
      flavourText: 'The pilot data shows what the theory predicted: people work more when their basic needs are secure, not less. Entrepreneurship rates rise 15% in pilot areas. The case for nationwide rollout is now empirical, not ideological.',
    },
  },

  {
    id: 'soc_t4_education_equality',
    treeId: 'socialist_welfare',
    tier: 4,
    category: 'social',
    icon: '📖',
    name: 'Educational Equality Programme',
    description: 'Close the quality gap between elite urban schools and rural kampung sekolah: redistribute experienced teachers to underperforming schools through a Teacher Deployment Incentive, equalize per-pupil spending across all states, and introduce a National Curriculum Equity Review.',
    durationMonths: 28,
    prerequisiteIds: ['soc_t2_free_education', 'soc_t3_gender_equality'],
    requirements: {
      description: 'Strong human capital investment and high taxes.',
      requiredPolicy: { taxRate: 'high' },
      minHumanCapital: 52,
    },
    reward: {
      unemploymentBonus: 1.0,
      legacyPoints: 9,
      populationGrowthBonuses: [{ ethnicity: 'all', bonus: 0.001 }],
      structuralBonus: { humanCapitalBoost: 14, inequalityReduction: -0.028 },
      flavourText: 'Pupils in Kelantan receive the same quality education as pupils in Petaling Jaya. The talent pool Malaysia draws from to fill its workforce doubles in a generation. Equal education is the longest-term economic investment available.',
    },
  },

  {
    id: 'soc_t4_workers_state',
    treeId: 'socialist_welfare',
    tier: 4,
    category: 'institutional',
    icon: '🔨',
    name: 'Workers State Charter',
    description: 'Constitutionally entrench workers\' rights: the right to organise, the right to strike, co-determination rights in all companies over 50 employees, and a Worker Commissioner with constitutional independence.',
    durationMonths: 30,
    prerequisiteIds: ['soc_t3_peoples_economy', 'soc_t3_full_employment'],
    requirements: {
      description: 'Strong labour movement and democratic mandate.',
      minApproval: 55,
      maxCorruption: 38,
    },
    reward: {
      approvalBonus: 11,
      legacyPoints: 12,
      structuralBonus: { inequalityReduction: -0.034, humanCapitalBoost: 8, corruptionReduction: 6 },
      policyUnlock: {
        description: 'Unlocks "Co-determination Model" — worker board representation',
        unlockedOptions: {},
      },
      flavourText: 'Workers gain constitutional standing for the first time. The political economy shifts. Wage bargaining becomes a genuine negotiation rather than a performance. Investment patterns change; so does the quality of work.',
    },
  },

  {
    id: 'soc_t4_decommodify_housing',
    treeId: 'socialist_welfare',
    tier: 4,
    category: 'social',
    icon: '🏗️',
    name: 'Housing Decommodification',
    description: 'Remove speculative investment from the housing market: a 30% vacancy tax on second homes, mandatory rental licensing, a National Housing Bank providing mortgages at cost price, and a constitutional right to adequate housing.',
    durationMonths: 24,
    prerequisiteIds: ['soc_t2_public_housing', 'soc_t3_wealth_redistribution'],
    requirements: {
      description: 'Strong welfare mandate and political will.',
      requiredPolicy: { taxRate: 'high', welfareLevel: 'generous' },
      minApproval: 50,
    },
    reward: {
      gdpBonus: 0.35,
      approvalBonus: 9,
      legacyPoints: 8,
      structuralBonus: { inequalityReduction: -0.028, humanCapitalBoost: 5 },
      flavourText: 'Homes are for living in, not investing in. House prices stabilise. The generational divide in housing access — homeowners vs perpetual renters — begins to close. Many investors are furious. Significantly more non-investors are quietly relieved.',
    },
  },

  {
    id: 'soc_t4_worker_ownership',
    treeId: 'socialist_welfare',
    tier: 4,
    category: 'economic',
    icon: '🏭',
    name: 'Worker Ownership Fund',
    description: 'Mandate that all companies with over 200 employees annually issue 5% equity to a Worker Ownership Fund. Over 20 years, workers collectively own 50% of major Malaysian corporations. The model follows Sweden\'s Meidner Plan, adapted for Malaysia.',
    durationMonths: 36,
    prerequisiteIds: ['soc_t4_workers_state', 'soc_t3_wealth_redistribution'],
    mutuallyExclusiveWith: ['soc_t5_state_capitalism'],
    requirements: {
      description: 'Full workers state and redistributive capacity.',
      minApproval: 54,
      requiredPolicy: { taxRate: 'high', welfareLevel: 'generous' },
      maxCorruption: 35,
    },
    reward: {
      gdpBonus: 0.7,
      legacyPoints: 14,
      budgetBonus: 110,
      structuralBonus: { inequalityReduction: -0.045, humanCapitalBoost: 10, corruptionReduction: 8 },
      flavourText: 'Within fifteen years, Malaysian workers own a significant stake in the economy they built. The quarterly dividend announcement is no longer Amanah Saham — it is the worker fund report. The political economy has been transformed from below.',
    },
  },

  // ══════════════ TIER 5 — SOCIALIST ENDGAME (7 missions) ══════════════

  {
    id: 'soc_t5_nordic_model',
    treeId: 'socialist_welfare',
    tier: 5,
    category: 'legacy',
    icon: '🏆',
    name: 'The Malaysian Nordic Model',
    description: 'Complete the transition: comprehensive welfare from cradle to grave, worker co-ownership of the economy, universal services of world-class quality, and a democratic political culture that makes rollback impossible. The Malaysian model becomes a reference for the Global South.',
    durationMonths: 54,
    prerequisiteIds: ['soc_t4_just_transition', 'soc_t4_ubi', 'soc_t4_worker_ownership'],
    requirements: {
      description: 'All welfare conditions met at high standard.',
      minHumanCapital: 68,
      maxCorruption: 25,
      minApproval: 62,
      minGdpGrowth: 3.5,
      minLegacyPoints: 60,
    },
    reward: {
      gdpBonus: 2.2,
      unemploymentBonus: 2.0,
      inflationModifier: -0.5,
      budgetBonus: 200,
      approvalBonus: 18,
      legacyPoints: 40,
      populationGrowthBonuses: [{ ethnicity: 'all', bonus: 0.0018 }],
      structuralBonus: { humanCapitalBoost: 24, inequalityReduction: -0.07, corruptionReduction: 20, infrastructureBoost: 16 },
      policyUnlock: {
        description: 'Unlocks "Social Democracy" — full suite of Nordic-model policy options',
        unlockedOptions: { welfareLevel: ['social_democracy'] },
      },
      flavourText: 'Malaysia is frequently cited as the most equal high-income country in Asia. The combination of tropical diversity, Islamic values, and Nordic-inspired welfare state is called the Malaysian Model. It is studied in universities on six continents.',
    },
  },

  {
    id: 'soc_t5_state_capitalism',
    treeId: 'socialist_welfare',
    tier: 5,
    category: 'institutional',
    icon: '🏛️',
    name: 'State Capitalism Consolidation',
    description: 'Consolidate state ownership of the commanding heights: nationalise the five largest banks, GLCs manage 60%+ of the corporate sector, and a National Planning Commission coordinates investment across the entire economy.',
    durationMonths: 36,
    prerequisiteIds: ['soc_t4_workers_state', 'soc_t2_nationalised_utilities'],
    mutuallyExclusiveWith: ['soc_t4_worker_ownership'],
    requirements: {
      description: 'Strong state and high approval.',
      minApproval: 52,
      requiredPolicy: { taxRate: 'high', spendingLevel: 'expansionary' },
    },
    reward: {
      gdpBonus: 0.9,
      budgetBonus: 250,
      legacyPoints: 10,
      structuralBonus: { corruptionReduction: -10, humanCapitalBoost: 5, infrastructureBoost: 8 },
      flavourText: 'The state controls the economy. Planning is coherent. Patronage is entrenched. The difference between state socialism and state capitalism depends entirely on whether the state serves the people or the people who run the state.',
    },
  },

  {
    id: 'soc_t5_economic_democracy',
    treeId: 'socialist_welfare',
    tier: 5,
    category: 'economic',
    icon: '🗳️',
    name: 'Economic Democracy',
    description: 'Extend democratic principles to the economy: workers vote on corporate strategy through mandatory works councils, consumers have statutory representation on utility boards, and a Citizens Economic Assembly reviews all major state investment decisions.',
    durationMonths: 42,
    prerequisiteIds: ['soc_t4_worker_ownership'],
    requirements: {
      description: 'Full workers state and democratic institutions.',
      maxCorruption: 28,
      minApproval: 56,
      minHumanCapital: 65,
    },
    reward: {
      approvalBonus: 14,
      gdpBonus: 0.8,
      legacyPoints: 20,
      structuralBonus: { corruptionReduction: 14, humanCapitalBoost: 12, inequalityReduction: -0.042 },
      flavourText: 'Democracy finally reaches the economy. Works councils debate production targets with the same passion that town councils debate zoning. The result is messier, slower, and more legitimate than anything decided in an executive boardroom.',
    },
  },

  {
    id: 'soc_t5_reparations',
    treeId: 'socialist_welfare',
    tier: 5,
    category: 'social',
    icon: '⚖️',
    name: 'Colonial Reparations & Justice',
    description: 'Establish a Commission on Colonial Economic Harm to document and calculate reparations owed to Malaysian workers and communities for colonial extraction. Negotiate with Britain for a voluntary reparations fund. Redistribute proceeds to descendants of estate workers and Orang Asli.',
    durationMonths: 30,
    prerequisiteIds: ['soc_t5_nordic_model'],
    requirements: {
      description: 'Strong democratic mandate and social justice commitment.',
      minApproval: 58,
      maxCorruption: 25,
      minLegacyPoints: 65,
    },
    reward: {
      approvalBonus: 12,
      legacyPoints: 16,
      populationGrowthBonuses: [{ ethnicity: 'Indian', bonus: 0.0012 }, { ethnicity: 'Bumiputera Sabah (Non-Muslim)', bonus: 0.001 }, { ethnicity: 'Bumiputera Sarawak (Non-Muslim)', bonus: 0.001 }, { ethnicity: 'Orang Asli', bonus: 0.001 }, { ethnicity: 'Others', bonus: 0.001 }],
      structuralBonus: { inequalityReduction: -0.04, humanCapitalBoost: 8 },
      flavourText: 'The reparations commission findings read like the history Malaysia was never taught in school. The British government declines formal reparations but establishes a voluntary development fund. It is small, symbolic, and profoundly meaningful.',
    },
  },

  {
    id: 'soc_t5_refugee_integration',
    treeId: 'socialist_welfare',
    tier: 5,
    category: 'social',
    icon: '🤲',
    name: 'Refugee Integration Programme',
    description: 'Sign the 1951 Refugee Convention. Grant work permits and access to public services for the 100,000+ UNHCR-registered refugees. Establish a 5-year pathway to permanent residency. Create a Refugee Entrepreneurship Fund to support business creation.',
    durationMonths: 20,
    prerequisiteIds: ['soc_t3_peoples_economy'],
    requirements: {
      description: 'Generous welfare mandate and high approval.',
      requiredPolicy: { welfareLevel: 'generous' },
      minApproval: 54,
    },
    reward: {
      gdpBonus: 0.4,
      unemploymentBonus: 0.3,
      approvalBonus: 6,
      legacyPoints: 8,
      populationGrowthBonuses: [{ ethnicity: 'all', bonus: 0.0008 }],
      structuralBonus: { humanCapitalBoost: 7, corruptionReduction: 5 },
      flavourText: 'Malaysia becomes the first Southeast Asian country to grant refugees the right to work. The economic contribution of 100,000 productive workers exceeds the cost of integration within three years. The humanitarian and economic cases turn out to be the same case.',
      historicalNote: 'Malaysia hosts over 170,000 UNHCR-registered refugees, primarily Rohingya. They have no legal right to work, education, or healthcare. Malaysia has never signed the 1951 Refugee Convention.',
    },
  },

  {
    id: 'soc_t5_fiscal_crisis',
    treeId: 'socialist_welfare',
    tier: 5,
    category: 'crisis',
    icon: '💸',
    name: 'Welfare State Fiscal Crisis',
    description: 'The generous welfare state faces a fiscal reckoning: revenue growth has not kept pace with spending commitments. Bond markets are demanding higher yields. Choose: austerity that breaks the social contract, or a wealth tax and capital flight risk.',
    durationMonths: 18,
    prerequisiteIds: ['soc_t3_peoples_economy'],
    requirements: {
      description: 'Triggered by large deficit and high spending.',
      crisisTrigger: { budgetDeficitAbove: 500, gdpBelow: 2.0 },
    },
    reward: {
      budgetBonus: -200,
      approvalBonus: -10,
      legacyPoints: -6,
      structuralBonus: { corruptionReduction: 5 },
      policyUnlock: {
        description: 'Unlocks "Emergency Wealth Tax" — one-off levy on top 1%',
        unlockedOptions: { taxRate: ['emergency_wealth'] },
      },
      flavourText: 'The welfare state is solvent on paper but cash-flow-constrained in practice. The fiscal crisis is real — and it is also manufactured by those who prefer a smaller state. The politics of austerity have arrived. The question is whether the left can answer them.',
    },
  },
];

export { SOCIALIST_MISSIONS };
