// ─────────────────────────────────────────────────────────────
// TREE 6: FEDERAL PLURALISM — 35 MISSIONS, 5 TIERS
// ─────────────────────────────────────────────────────────────

const FEDERAL_PLURALISM_MISSIONS = [
  // ══════════════ TIER 1 — DEVOLUTION FOUNDATION (7 missions) ══════════════

  {
    id: 'fed_t1_decentralisation',
    treeId: 'federal_pluralism',
    tier: 1,
    category: 'institutional',
    icon: '🗺️',
    name: 'State Fiscal Autonomy',
    description: 'Devolve a share of federal revenue to state governments through block grants and formula-based transfers. Restore state government borrowing rights. Grant states authority over land, housing, and local infrastructure development without federal approval.',
    durationMonths: 12,
    prerequisiteIds: [],
    requirements: {
      description: 'Manageable budget deficit.',
      minBudgetBalance: -280,
    },
    reward: {
      gdpBonus: 0.38,
      approvalBonus: 5,
      legacyPoints: 3,
      structuralBonus: { corruptionReduction: 3, inequalityReduction: -0.009 },
      policyUnlock: {
        description: 'Enables "State Development Block Grant" direct funding',
        unlockedOptions: { spendingLevel: ['block_grant'] },
      },
      flavourText: 'Kelantan and Sabah control their own development budgets for the first time since the Emergency. Local needs get local answers. Local governments also acquire local corruption — the devolution bargain.',
      historicalNote: 'Malaysia\'s fiscal centralisation is extreme: the federal government controls ~90% of revenue. State governments depend on federal transfers. Kelantan\'s oil royalty dispute with Putrajaya has been constitutionally unresolved for decades.',
    },
  },

  {
    id: 'fed_t1_borneo_rights',
    treeId: 'federal_pluralism',
    tier: 1,
    category: 'social',
    icon: '🦧',
    name: 'Restore Borneo Special Rights',
    description: 'Honour the 1963 Malaysia Agreement: restore Sabah and Sarawak\'s immigration autonomy, increase oil royalties from 5% to 20%, protect native customary land (NCR) through a constitutional amendment, and implement the 18-Point and 20-Point agreements in full.',
    durationMonths: 14,
    prerequisiteIds: [],
    requirements: {
      description: 'Multiracial government with moderate approval.',
      minApproval: 38,
    },
    reward: {
      approvalBonus: 9,
      legacyPoints: 5,
      populationGrowthBonuses: [
        { ethnicity: 'Bumiputera Sabah (Muslim)', bonus: 0.0011 }, { ethnicity: 'Bumiputera Sabah (Non-Muslim)', bonus: 0.0014 },
        { ethnicity: 'Bumiputera Sarawak (Muslim)', bonus: 0.0011 }, { ethnicity: 'Bumiputera Sarawak (Non-Muslim)', bonus: 0.0014 },
      ],
      structuralBonus: { inequalityReduction: -0.014 },
      flavourText: 'East Malaysians feel Malaysian again. The unresolved 1963 promises are finally kept. Peninsular politicians warn of a slippery slope; East Malaysians point out the constitution already promised this sixty years ago.',
      historicalNote: 'Sarawak\'s oil royalty battle (2018-2020) led to an increase from 5% to the still-contested demand for 20%. Sabah\'s immigration autonomy remains the most sensitive point — the Philippines\' Sulu claim complicates it.',
    },
  },

  {
    id: 'fed_t1_local_elections',
    treeId: 'federal_pluralism',
    tier: 1,
    category: 'institutional',
    icon: '🗳️',
    name: 'Restore Local Elections',
    description: 'Reintroduce elected local councils suspended since 1965. Give communities direct democratic control over municipal affairs, development approvals, and local spending. Pilot in three states before nationwide implementation.',
    durationMonths: 9,
    prerequisiteIds: [],
    requirements: {
      description: 'Moderate public approval.',
      minApproval: 40,
    },
    reward: {
      approvalBonus: 7,
      legacyPoints: 4,
      structuralBonus: { corruptionReduction: 7, humanCapitalBoost: 3 },
      populationGrowthBonuses: [{ ethnicity: 'Chinese', bonus: 0.0006 }],
      crossTreeSynergies: [
        {
          beneficiaryTree: 'liberal_open_economy',
          targetMissionId: 'lib_t1_property_rights',
          requirementReduction: 0.15,
          description: 'Elected local councils create accountable land use decision-making.',
        },
      ],
      flavourText: 'George Town elects its own mayor. Local government becomes accountable again — and the battles over development approvals begin in earnest. Democracy at its most unglamorous and most necessary.',
      historicalNote: 'Local elections were suspended in 1965 following the Indonesia-Malaysia Confrontation. The Athi Nahappan Report (1968) recommended restoration but it never happened. Pakatan Harapan promised restoration in 2018; it was not delivered by 2020.',
    },
  },

  {
    id: 'fed_t1_judiciary_independence',
    treeId: 'federal_pluralism',
    tier: 1,
    category: 'institutional',
    icon: '⚖️',
    name: 'Judicial Independence Reform',
    description: 'Establish a Judicial Appointments Commission insulated from executive interference. Restore the Federal Court\'s power to review constitutional legislation. Create an anti-corruption court with expedited procedures. Repeal the Judicial Appointments Commission Act and replace with a constitutional provision.',
    durationMonths: 14,
    prerequisiteIds: [],
    requirements: {
      description: 'Low corruption and stable governance.',
      maxCorruption: 50,
      minApproval: 38,
    },
    reward: {
      legacyPoints: 5,
      structuralBonus: { corruptionReduction: 9, humanCapitalBoost: 4 },
      crossTreeSynergies: [
        {
          beneficiaryTree: 'liberal_open_economy',
          targetMissionId: 'lib_t3_asian_financial_hub',
          requirementReduction: 0.2,
          description: 'Judicial independence is the rule-of-law prerequisite for deep financial markets.',
        },
      ],
      flavourText: 'The courts begin to operate as courts. Judges find against the government in cases involving government interests. This is supposed to be unremarkable. In Malaysia in this period, it is revolutionary.',
      historicalNote: 'The 1988 judicial crisis — in which Lord President Salleh Abbas was dismissed — was Malaysia\'s defining constitutional low point. The Judicial Appointments Commission established 2009 was criticised as cosmetic. Real independence remains contested.',
    },
  },

  {
    id: 'fed_t1_orang_asli_land',
    treeId: 'federal_pluralism',
    tier: 1,
    category: 'social',
    icon: '🌳',
    name: 'Orang Asli Land Rights',
    description: 'Constitutionally recognise Orang Asli customary land territories. Create a National Orang Asli Land Title Programme. Establish a Free, Prior, and Informed Consent requirement for any development on customary land. Give Orang Asli communities veto rights over their territories.',
    durationMonths: 12,
    prerequisiteIds: [],
    requirements: {
      description: 'Rights-based governance commitment.',
      minApproval: 38,
    },
    reward: {
      approvalBonus: 4,
      legacyPoints: 4,
      populationGrowthBonuses: [{ ethnicity: 'Bumiputera Sabah (Non-Muslim)', bonus: 0.0014 }, { ethnicity: 'Bumiputera Sarawak (Non-Muslim)', bonus: 0.0014 }, { ethnicity: 'Orang Asli', bonus: 0.0014 }, { ethnicity: 'Others', bonus: 0.0014 }],
      structuralBonus: { corruptionReduction: 4, inequalityReduction: -0.011 },
      crossTreeSynergies: [
        {
          beneficiaryTree: 'socialist_welfare',
          targetMissionId: 'soc_t3_rainforest_protection',
          requirementReduction: 0.25,
          description: 'Orang Asli land rights recognition creates the legal architecture for forest conservation.',
        },
      ],
      flavourText: 'Orang Asli communities for the first time have legal standing to defend their forests in court. The first test cases take years. The precedents, once set, cannot be unset.',
      historicalNote: 'The Adong Kuwau case (1997) and Sagong Tasi case (2002) established common law recognition of Orang Asli native customary rights, but implementation has been slow and contested across state jurisdictions.',
    },
  },

  {
    id: 'fed_t1_freedom_info',
    treeId: 'federal_pluralism',
    tier: 1,
    category: 'institutional',
    icon: '📰',
    name: 'Freedom of Information Act',
    description: 'Replace the Official Secrets Act with a Freedom of Information Act: any citizen can request any government document, refusals must be justified, and an Information Commissioner adjudicates disputes. Repeal the Printing Presses and Publications Act.',
    durationMonths: 10,
    prerequisiteIds: ['fed_t1_judiciary_independence'],
    requirements: {
      description: 'Reform mandate and judicial foundation.',
      maxCorruption: 48,
      minApproval: 40,
    },
    reward: {
      approvalBonus: 6,
      legacyPoints: 4,
      structuralBonus: { corruptionReduction: 10, humanCapitalBoost: 3 },
      crossTreeSynergies: [
        {
          beneficiaryTree: 'liberal_open_economy',
          targetMissionId: 'lib_t1_competition_law',
          requirementReduction: 0.15,
          description: 'Information access allows civil society to monitor competition law enforcement.',
        },
      ],
      flavourText: 'Journalists request government contracts and receive them. Civil society discovers exactly how public money was spent. The journalism that follows is inconvenient for many officials. This is precisely what the Act was designed to achieve.',
      historicalNote: 'Malaysia\'s Official Secrets Act (OSA) was used aggressively to suppress journalism. Selangor became the first state to pass a Freedom of Information Enactment in 2011, though implementation was limited.',
    },
  },

  {
    id: 'fed_t1_civil_liberties',
    treeId: 'federal_pluralism',
    tier: 1,
    category: 'institutional',
    icon: '🕊️',
    name: 'Civil Liberties Restoration',
    description: 'Repeal the Sedition Act, the Communications and Multimedia Act\'s censorship provisions, and the Prevention of Crime Act. Replace with a narrowly-defined Public Order Act focused on incitement to violence. Establish SUHAKAM (Human Rights Commission) with enforcement powers.',
    durationMonths: 13,
    prerequisiteIds: ['fed_t1_freedom_info'],
    requirements: {
      description: 'Democratic mandate for reform.',
      minApproval: 44,
      maxCorruption: 45,
    },
    reward: {
      approvalBonus: 8,
      legacyPoints: 4,
      structuralBonus: { corruptionReduction: 8, humanCapitalBoost: 4 },
      populationGrowthBonuses: [{ ethnicity: 'Chinese', bonus: 0.0007 }, { ethnicity: 'Indian', bonus: 0.0006 }],
      crossTreeSynergies: [
        {
          beneficiaryTree: 'federal_pluralism',
          targetMissionId: 'fed_t3_true_federation',
          requirementReduction: 0.15,
          description: 'Civil liberties restoration is the prerequisite for meaningful constitutional reform.',
        },
      ],
      flavourText: 'Malaysians can criticise their government without fear of arrest for the first time in decades. The first year produces a cacophony of public discourse. This is healthy. Democracy is loud.',
      historicalNote: 'The Sedition Act (1948), Communications Act (1998), and Emergency Ordinances were used extensively to suppress political opposition and investigative journalism. Their repeal was promised by multiple governments.',
    },
  },

  // ══════════════ TIER 2 — PLURALIST INSTITUTIONS (8 missions) ══════════════

  {
    id: 'fed_t2_interethnic_accord',
    treeId: 'federal_pluralism',
    tier: 2,
    category: 'social',
    icon: '🤝',
    name: 'National Interethnic Accord',
    description: 'Negotiate a comprehensive National Compact between ethnic community organisations, business chambers, religious bodies, and government. Agree on economic rights, investment sharing, reformed quota systems, and a monitored implementation timeline.',
    durationMonths: 20,
    prerequisiteIds: ['fed_t1_local_elections', 'fed_t1_judiciary_independence'],
    requirements: {
      description: 'Multiracial coalition and manageable corruption.',
      minApproval: 46,
      maxCorruption: 50,
    },
    reward: {
      gdpBonus: 0.65,
      approvalBonus: 11,
      legacyPoints: 7,
      populationGrowthBonuses: [{ ethnicity: 'all', bonus: 0.0008 }],
      structuralBonus: { inequalityReduction: -0.028, humanCapitalBoost: 5 },
      crossTreeSynergies: [
        {
          beneficiaryTree: 'bumiputera_agenda',
          targetMissionId: 'bumi_t4_nem',
          requirementReduction: 0.2,
          description: 'The Accord creates political space for Bumiputera policy reform by securing cross-ethnic guarantees.',
        },
        {
          beneficiaryTree: 'liberal_open_economy',
          targetMissionId: 'lib_t3_meritocracy',
          requirementReduction: 0.2,
          description: 'Negotiated compact gives meritocracy reform the multiracial legitimacy it needs.',
        },
      ],
      flavourText: 'Business leaders of all backgrounds sign the Accord on the steps of Parliament. Investment flows where talent lives. The next decade\'s politics will determine whether signatures translate into substance.',
    },
  },

  {
    id: 'fed_t2_regional_development',
    treeId: 'federal_pluralism',
    tier: 2,
    category: 'economic',
    icon: '🏙️',
    name: 'Regional Development Corridors',
    description: 'Establish development zones with devolved spending: ECER (East Coast), SCORE (Sarawak), SEDIA (Sabah), and NCER (Northern Corridor). Give corridor authorities genuine fiscal autonomy and private sector partnership rights without federal micromanagement.',
    durationMonths: 26,
    prerequisiteIds: ['fed_t1_decentralisation', 'fed_t1_borneo_rights'],
    requirements: {
      description: 'Open trade and infrastructure foundation.',
      requiredPolicy: { openTrade: true },
      minInfrastructure: 33,
    },
    reward: {
      gdpBonus: 0.95,
      unemploymentBonus: 1.1,
      budgetBonus: 38,
      legacyPoints: 7,
      populationGrowthBonuses: [
        { ethnicity: 'Malay', bonus: 0.0007 }, { ethnicity: 'Bumiputera Sabah (Muslim)', bonus: 0.001 },
        { ethnicity: 'Bumiputera Sabah (Non-Muslim)', bonus: 0.0009 }, { ethnicity: 'Bumiputera Sarawak (Non-Muslim)', bonus: 0.0009 },
      ],
      structuralBonus: { infrastructureBoost: 11, inequalityReduction: -0.019 },
      flavourText: 'The Eastern Corridor reduces the income gap between coasts. Rural Sabah industrialises. The corridor governance model — with genuine devolution — achieves more in five years than centralised planning achieved in twenty.',
      historicalNote: 'Malaysia\'s five economic corridors were established 2006-2009. SCORE in Sarawak attracted aluminium smelters using hydroelectric power from the controversial Bakun dam. Land rights and labour conditions generated ongoing disputes.',
    },
  },

  {
    id: 'fed_t2_language_rights',
    treeId: 'federal_pluralism',
    tier: 2,
    category: 'social',
    icon: '📚',
    name: 'Multilingual Education Policy',
    description: 'Formally recognise and fund Chinese (SJKC), Tamil (SJKT), and Iban-medium schooling alongside national Bahasa Malaysia schools. Guarantee financial parity. Allow vernacular schools to co-locate with national schools. Teach all three languages in government schools.',
    durationMonths: 16,
    prerequisiteIds: ['fed_t1_local_elections', 'fed_t1_civil_liberties'],
    requirements: {
      description: 'Moderate approval and human capital.',
      minApproval: 42,
      minHumanCapital: 26,
    },
    reward: {
      approvalBonus: 9,
      legacyPoints: 6,
      structuralBonus: { humanCapitalBoost: 10, inequalityReduction: -0.014 },
      populationGrowthBonuses: [
        { ethnicity: 'Chinese', bonus: 0.001 }, { ethnicity: 'Indian', bonus: 0.0009 },
        { ethnicity: 'Bumiputera Sarawak (Non-Muslim)', bonus: 0.0007 }, { ethnicity: 'Bumiputera Sabah (Non-Muslim)', bonus: 0.0007 },
      ],
      flavourText: 'Vernacular schools receive equal funding. Mother-tongue education is no longer a political battleground — at least until the next election, when someone will use it again. But the legal foundation has changed.',
      historicalNote: 'Chinese and Tamil schools (established colonial era) educate ~25% of Malaysian students. They are perpetually underfunded and dependent on community fundraising. SJKC schools are the backbone of Chinese Malaysian cultural preservation.',
    },
  },

  {
    id: 'fed_t2_senate_reform',
    treeId: 'federal_pluralism',
    tier: 2,
    category: 'institutional',
    icon: '🏛️',
    name: 'Senate Reform and State Representation',
    description: 'Reform the Dewan Negara (Senate): replace ministerial nominees with elected state representatives, give the Senate genuine review powers (90-day delay, not mere rubber stamp), and create a Senate Committee with investigative authority over federal-state disputes.',
    durationMonths: 18,
    prerequisiteIds: ['fed_t1_local_elections', 'fed_t1_judiciary_independence'],
    requirements: {
      description: 'Democratic reform mandate.',
      minApproval: 44,
      maxCorruption: 46,
    },
    reward: {
      approvalBonus: 7,
      legacyPoints: 5,
      structuralBonus: { corruptionReduction: 8, humanCapitalBoost: 3 },
      policyUnlock: {
        description: 'Unlocks "Asymmetric Federalism" special governance arrangements',
        unlockedOptions: {},
      },
      crossTreeSynergies: [
        {
          beneficiaryTree: 'federal_pluralism',
          targetMissionId: 'fed_t3_true_federation',
          requirementReduction: 0.2,
          description: 'Senate reform creates the institutional architecture for genuine constitutional devolution.',
        },
      ],
      flavourText: 'The Senate debates federal-state finance for the first time with senators who have a mandate from their states. The quality of legislation improves. Ministers face genuine scrutiny. They adapt — and become better ministers.',
    },
  },

  {
    id: 'fed_t2_electoral_reform',
    treeId: 'federal_pluralism',
    tier: 2,
    category: 'institutional',
    icon: '🗳️',
    name: 'Electoral Integrity Act',
    description: 'Establish an Independent Electoral Commission with power to draw boundaries and enforce campaign finance rules. Introduce independent boundary delimitation every 10 years. Ban gerrymandering. Mandate automatic voter registration at 21.',
    durationMonths: 14,
    prerequisiteIds: ['fed_t1_civil_liberties', 'fed_t1_freedom_info'],
    requirements: {
      description: 'Genuine democratic commitment.',
      maxCorruption: 44,
      minApproval: 42,
    },
    reward: {
      approvalBonus: 8,
      legacyPoints: 6,
      structuralBonus: { corruptionReduction: 11, humanCapitalBoost: 4 },
      crossTreeSynergies: [
        {
          beneficiaryTree: 'federal_pluralism',
          targetMissionId: 'fed_t4_national_reconciliation',
          requirementReduction: 0.15,
          description: 'Electoral integrity is the democratic foundation for reconciliation to have meaning.',
        },
      ],
      flavourText: 'The 2028 election is the first held under the new independent boundaries. The result surprises everyone — because it actually reflects what voters want, rather than what the boundaries were drawn to produce.',
      historicalNote: 'Malaysia\'s Election Commission was long criticised for partisan boundary delimitation. The 2016 redelineation increased the overrepresentation of rural constituencies and reduced urban votes\' effective weight.',
    },
  },

  {
    id: 'fed_t2_indigenous_councils',
    treeId: 'federal_pluralism',
    tier: 2,
    category: 'social',
    icon: '🪶',
    name: 'Indigenous Self-Governance Councils',
    description: 'Establish elected Native Customary Land Councils in Sabah and Sarawak with legal authority over NCR territory. Create Orang Asli Community Development Councils in Peninsular Malaysia. Devolve healthcare, education, and land administration to these councils.',
    durationMonths: 18,
    prerequisiteIds: ['fed_t1_borneo_rights', 'fed_t1_orang_asli_land'],
    requirements: {
      description: 'Indigenous rights foundation.',
      minApproval: 42,
      minHumanCapital: 30,
    },
    reward: {
      approvalBonus: 8,
      legacyPoints: 6,
      populationGrowthBonuses: [
        { ethnicity: 'Bumiputera Sabah (Non-Muslim)', bonus: 0.0016 }, { ethnicity: 'Bumiputera Sarawak (Non-Muslim)', bonus: 0.0016 },
        { ethnicity: 'Bumiputera Sabah (Non-Muslim)', bonus: 0.0012 }, { ethnicity: 'Bumiputera Sarawak (Non-Muslim)', bonus: 0.0012 }, { ethnicity: 'Orang Asli', bonus: 0.0012 }, { ethnicity: 'Others', bonus: 0.0012 },
      ],
      structuralBonus: { inequalityReduction: -0.02, humanCapitalBoost: 6 },
      flavourText: 'For the first time, the Kadazan-Dusun and Iban communities govern themselves on their own land. The development decisions made at community level are different from those made in Kuala Lumpur or Kuching — and better suited to local conditions.',
    },
  },

  {
    id: 'fed_t2_arts_culture_fund',
    treeId: 'federal_pluralism',
    tier: 2,
    category: 'social',
    icon: '🎭',
    name: 'Multicultural Arts and Heritage Fund',
    description: 'Establish a national fund supporting the arts, heritage, and cultural practices of all Malaysian communities: Chinese opera, Tamil classical dance, Kadazan harvest festivals, Iban longhouse traditions, and Malay performing arts equally. Replace the selective cultural nationalism of the past.',
    durationMonths: 10,
    prerequisiteIds: ['fed_t1_civil_liberties'],
    requirements: {
      description: 'Cultural pluralism commitment.',
      minApproval: 40,
    },
    reward: {
      approvalBonus: 6,
      legacyPoints: 3,
      populationGrowthBonuses: [{ ethnicity: 'all', bonus: 0.0005 }],
      structuralBonus: { humanCapitalBoost: 5, inequalityReduction: -0.008 },
      flavourText: 'For the first time, a Boria performance in Penang receives the same government recognition as a wayang kulit in Kelantan. The Ministry of Culture\'s budget grows; more importantly, its definition of Malaysian culture grows.',
    },
  },

  {
    id: 'fed_t2_gst_sharing',
    treeId: 'federal_pluralism',
    tier: 2,
    category: 'economic',
    icon: '💸',
    name: 'Revenue Sharing Formula Reform',
    description: 'Fundamentally reform federal-state revenue sharing: increase the state share of national taxes from 7% to 20%, create a State Equalisation Fund for poorer states, and give states the right to levy their own tourism and property taxes.',
    durationMonths: 15,
    prerequisiteIds: ['fed_t1_decentralisation', 'fed_t2_senate_reform'],
    requirements: {
      description: 'Adequate budget and political will for devolution.',
      minBudgetBalance: -200,
      minApproval: 44,
    },
    reward: {
      gdpBonus: 0.55,
      approvalBonus: 8,
      legacyPoints: 5,
      structuralBonus: { corruptionReduction: 5, inequalityReduction: -0.018 },
      policyUnlock: {
        description: 'Unlocks "State Revenue Autonomy" — independent state taxation',
        unlockedOptions: {},
      },
      flavourText: 'States that were perpetually dependent on Putrajaya\'s goodwill now have their own fiscal base. Kelantan builds roads without a federal election calculation. Sarawak invests oil royalties in education rather than waiting for a federal allocation.',
    },
  },

  // ══════════════ TIER 3 — PLURALIST CONSOLIDATION (7 missions) ══════════════

  {
    id: 'fed_t3_true_federation',
    treeId: 'federal_pluralism',
    tier: 3,
    category: 'legacy',
    icon: '📜',
    name: 'Constitutional Reform Act',
    description: 'Enshrine plural rights, judicial independence, genuine state fiscal autonomy, and an elected Senate in constitutional amendments requiring 2/3 majority. The most significant constitutional change since 1957.',
    durationMonths: 40,
    prerequisiteIds: ['fed_t2_interethnic_accord', 'fed_t2_language_rights', 'fed_t2_electoral_reform'],
    requirements: {
      description: 'High approval, low corruption, stable economy.',
      minApproval: 56,
      maxCorruption: 30,
      minGdpGrowth: 2.5,
    },
    reward: {
      approvalBonus: 16,
      gdpBonus: 0.65,
      legacyPoints: 16,
      populationGrowthBonuses: [{ ethnicity: 'all', bonus: 0.0012 }],
      structuralBonus: { corruptionReduction: 14, humanCapitalBoost: 9, inequalityReduction: -0.038 },
      policyUnlock: {
        description: 'Unlocks "Asymmetric Federalism" — special arrangements for Sabah and Sarawak',
        unlockedOptions: {},
      },
      flavourText: 'The Constitution is rewritten in good faith for the first time since 1957. The process is contested, heated, and democratic. Whether it holds depends on whether the next government respects it — which is always the question.',
    },
  },

  {
    id: 'fed_t3_east_malaysia_integration',
    treeId: 'federal_pluralism',
    tier: 3,
    category: 'social',
    icon: '🌊',
    name: 'East Malaysia Integration',
    description: 'Complete physical, economic, and social integration of Sabah and Sarawak: Pan-Borneo Highway completion, fibre cable to every district, PTPTN access parity, equal citizenship rights for stateless Sabahans, and a Borneo Development Bank.',
    durationMonths: 34,
    prerequisiteIds: ['fed_t2_regional_development', 'fed_t2_interethnic_accord'],
    requirements: {
      description: 'Strong infrastructure and approval.',
      minInfrastructure: 53,
      minApproval: 50,
    },
    reward: {
      gdpBonus: 1.35,
      unemploymentBonus: 1.0,
      budgetBonus: 75,
      approvalBonus: 10,
      legacyPoints: 10,
      populationGrowthBonuses: [
        { ethnicity: 'Bumiputera Sabah (Muslim)', bonus: 0.0016 }, { ethnicity: 'Bumiputera Sabah (Non-Muslim)', bonus: 0.002 },
        { ethnicity: 'Bumiputera Sarawak (Muslim)', bonus: 0.0016 }, { ethnicity: 'Bumiputera Sarawak (Non-Muslim)', bonus: 0.002 },
      ],
      structuralBonus: { infrastructureBoost: 15, inequalityReduction: -0.028 },
      flavourText: 'The South China Sea no longer divides Malaysia. But Sarawak and Sabah politicians remind Putrajaya that "integration" must not become "absorption" — and the constitutional reform they just secured ensures it does not.',
      historicalNote: 'The Pan-Borneo Highway (2,329 km) is Malaysia\'s largest infrastructure project. The "Project IC" stateless issue — Mahathir-era allegations of citizenship-for-votes in Sabah — remains Malaysia\'s most acute unresolved human rights issue.',
    },
  },

  {
    id: 'fed_t3_smart_city',
    treeId: 'federal_pluralism',
    tier: 3,
    category: 'economic',
    icon: '🌆',
    name: 'Distributed Smart City Network',
    description: 'Build smart city infrastructure across ALL states — not just KL — with 5G, open data platforms, digital public services, and smart grid energy management. Use technology to reduce urban-rural inequality rather than deepen it.',
    durationMonths: 40,
    prerequisiteIds: ['fed_t2_language_rights', 'fed_t2_regional_development'],
    requirements: {
      description: 'High human capital and infrastructure.',
      minHumanCapital: 53,
      minInfrastructure: 56,
    },
    reward: {
      gdpBonus: 1.55,
      unemploymentBonus: 1.2,
      inflationModifier: -0.28,
      approvalBonus: 9,
      legacyPoints: 9,
      populationGrowthBonuses: [{ ethnicity: 'all', bonus: 0.001 }],
      structuralBonus: { humanCapitalBoost: 15, infrastructureBoost: 17, corruptionReduction: 9, inequalityReduction: -0.024 },
      flavourText: 'Broadband reaches the Sarawak jungle. A Kelantan village practices e-commerce. Technology becomes the equaliser — with the caveat that the digital infrastructure is only as equitable as the policy governing it.',
    },
  },

  {
    id: 'fed_t3_anticorruption_constitution',
    treeId: 'federal_pluralism',
    tier: 3,
    category: 'institutional',
    icon: '🔍',
    name: 'Constitutional Anti-Corruption Framework',
    description: 'Constitutionally entrench the independence of MACC (Malaysian Anti-Corruption Commission): independent board appointed by Parliament, not the Prime Minister; security of tenure; and direct reporting to a Parliamentary Select Committee.',
    durationMonths: 22,
    prerequisiteIds: ['fed_t3_true_federation'],
    requirements: {
      description: 'Constitutional reform completed.',
      maxCorruption: 35,
      minApproval: 52,
    },
    reward: {
      legacyPoints: 10,
      structuralBonus: { corruptionReduction: 18, humanCapitalBoost: 6 },
      crossTreeSynergies: [
        {
          beneficiaryTree: 'developmental_state',
          targetMissionId: 'dev_t4_knowledge_economy',
          requirementReduction: 0.2,
          description: 'Constitutional anti-corruption framework creates the clean institutional environment for knowledge economy.',
        },
        {
          beneficiaryTree: 'liberal_open_economy',
          targetMissionId: 'lib_t5_constitutional_rights',
          requirementReduction: 0.25,
          description: 'MACC independence is a pillar of the constitutional rights framework.',
        },
      ],
      flavourText: 'MACC investigates the Prime Minister\'s Chief of Staff and presses charges. Everyone in the country watches to see if the charges stick. They do. This is the moment Malaysia\'s institutions grow up.',
    },
  },

  {
    id: 'fed_t3_sabah_sarawak_autonomy',
    treeId: 'federal_pluralism',
    tier: 3,
    category: 'institutional',
    icon: '🦁',
    name: 'Borneo Autonomy Charter',
    description: 'Grant Sabah and Sarawak full autonomous status within the federation: state immigration control fully restored, revenue sharing at 40%, state rights to manage their natural resources with PETRONAS as a contractor rather than owner.',
    durationMonths: 26,
    prerequisiteIds: ['fed_t3_east_malaysia_integration', 'fed_t2_senate_reform'],
    requirements: {
      description: 'East Malaysia trust and federal commitment.',
      minApproval: 52,
      maxCorruption: 38,
    },
    reward: {
      approvalBonus: 13,
      legacyPoints: 12,
      populationGrowthBonuses: [
        { ethnicity: 'Bumiputera Sabah (Muslim)', bonus: 0.002 }, { ethnicity: 'Bumiputera Sabah (Non-Muslim)', bonus: 0.0022 },
        { ethnicity: 'Bumiputera Sarawak (Muslim)', bonus: 0.002 }, { ethnicity: 'Bumiputera Sarawak (Non-Muslim)', bonus: 0.0022 },
        { ethnicity: 'Sabahan Chinese', bonus: 0.0015 }, { ethnicity: 'Sarawakian Chinese', bonus: 0.0015 },
      ],
      structuralBonus: { inequalityReduction: -0.03, corruptionReduction: 9 },
      flavourText: 'Sabah and Sarawak are, for the first time since 1969, equal partners in Malaysia. The "Malaysia Agreement 1963 Revisited" becomes the governing document. East Malaysians no longer feel like a colony of peninsular Malaysia.',
    },
  },

  {
    id: 'fed_t3_religious_harmony',
    treeId: 'federal_pluralism',
    tier: 3,
    category: 'social',
    icon: '🕌',
    name: 'Religious Harmony Council',
    description: 'Establish a National Religious Harmony Council with representatives from Islam, Christianity, Buddhism, Hinduism, Sikhism, and indigenous belief systems. Create a formal dispute resolution mechanism. Clarify the civil-syariah court jurisdictional boundary constitutionally.',
    durationMonths: 20,
    prerequisiteIds: ['fed_t2_interethnic_accord', 'fed_t1_civil_liberties'],
    requirements: {
      description: 'Interethnic trust and civil liberties foundation.',
      minApproval: 48,
      maxCorruption: 42,
    },
    reward: {
      approvalBonus: 10,
      legacyPoints: 7,
      populationGrowthBonuses: [{ ethnicity: 'all', bonus: 0.0008 }],
      structuralBonus: { corruptionReduction: 6, inequalityReduction: -0.016 },
      crossTreeSynergies: [
        {
          beneficiaryTree: 'bumiputera_agenda',
          targetMissionId: 'bumi_t5_racial_harmony_act',
          requirementReduction: 0.25,
          description: 'Religious Harmony Council provides the institutional template for racial harmony legislation.',
        },
      ],
      flavourText: 'The syariah-civil jurisdictional dispute that has generated decades of legal anguish is finally resolved. Not perfectly — the resolution satisfies no one completely. But it is workable, and workable is everything.',
      historicalNote: 'The Lina Joy case (2007), the M Indira Gandhi custody dispute (2009-2021), and the body-snatching controversies revealed deep jurisdictional conflicts between civil and syariah courts that affect non-Muslim Malaysians.',
    },
  },

  {
    id: 'fed_t3_urban_rural_rebalance',
    treeId: 'federal_pluralism',
    tier: 3,
    category: 'economic',
    icon: '🌾',
    name: 'Urban-Rural Rebalancing',
    description: 'Address Malaysia\'s structural urban-rural divide: rural broadband as a right, rural hospital parity with urban hospitals, a Young Farmers Programme with land grants, and a Rural Economic Enterprise Fund for non-agricultural rural enterprises.',
    durationMonths: 28,
    prerequisiteIds: ['fed_t2_regional_development', 'fed_t2_gst_sharing'],
    requirements: {
      description: 'Adequate fiscal capacity and welfare commitment.',
      minBudgetBalance: -220,
      requiredPolicy: { welfareLevel: 'moderate' },
    },
    reward: {
      gdpBonus: 0.75,
      unemploymentBonus: 0.9,
      approvalBonus: 8,
      legacyPoints: 6,
      populationGrowthBonuses: [{ ethnicity: 'Malay', bonus: 0.0009 }, { ethnicity: 'all', bonus: 0.0004 }],
      structuralBonus: { infrastructureBoost: 10, inequalityReduction: -0.024 },
      flavourText: 'The rural-urban income gap, which was widening for twenty years, begins to close. Rural youth who previously saw migration to KL as the only option now have reasons to stay — and reasons to return.',
    },
  },

  // ══════════════ TIER 4 — DEEP DEMOCRACY (6 missions) ══════════════

  {
    id: 'fed_t4_national_reconciliation',
    treeId: 'federal_pluralism',
    tier: 4,
    category: 'legacy',
    icon: '🤝',
    name: 'National Reconciliation Commission',
    description: 'Establish a Truth and Reconciliation Commission addressing May 13 1969, the Memali incident (1985), Operasi Lalang (1987), and the accumulated grievances of sixty years of exclusion. A formal process of acknowledgment, accountability, and forward commitment.',
    durationMonths: 60,
    prerequisiteIds: ['fed_t3_true_federation', 'fed_t3_east_malaysia_integration'],
    requirements: {
      description: 'All preconditions: approval, clean institutions, strong economy.',
      minApproval: 60,
      maxCorruption: 25,
      minHumanCapital: 62,
      minGdpGrowth: 3.0,
    },
    reward: {
      gdpBonus: 0.9,
      approvalBonus: 20,
      legacyPoints: 35,
      populationGrowthBonuses: [{ ethnicity: 'all', bonus: 0.0015 }],
      structuralBonus: { humanCapitalBoost: 18, inequalityReduction: -0.065, corruptionReduction: 22, infrastructureBoost: 10 },
      policyUnlock: {
        description: 'Unlocks "National Unity Dividend" — permanent multiracial approval modifier',
        unlockedOptions: { welfareLevel: ['national_unity_dividend'] },
      },
      crossTreeSynergies: [
        {
          beneficiaryTree: 'bumiputera_agenda',
          targetMissionId: 'bumi_t5_new_bumi_policy',
          requirementReduction: 0.3,
          description: 'Reconciliation commission creates the political trust for Bumiputera policy transformation.',
        },
        {
          beneficiaryTree: 'liberal_open_economy',
          targetMissionId: 'lib_t4_high_income_society',
          requirementReduction: 0.2,
          description: 'Social trust is the invisible prerequisite for high-income nation institutions.',
        },
      ],
      flavourText: '"A nation that will not look honestly at its past cannot build honestly towards its future." The Commission hearings last three years. What they find — and what the country does with it — determines what kind of Malaysia the next century inherits.',
      historicalNote: 'Malaysia has never conducted a formal reconciliation process over May 13 (1969), Operasi Lalang (1987), or the Memali shootings (1985). A proposed Truth Commission was mooted by Pakatan Harapan in 2018 but was never established.',
    },
  },

  {
    id: 'fed_t4_federal_charter',
    treeId: 'federal_pluralism',
    tier: 4,
    category: 'institutional',
    icon: '📜',
    name: 'New Federal Charter',
    description: 'A comprehensive Federal Charter redefining the social contract: a rights-based constitution, genuine federal-state balance of power, constitutional protection for all forms of identity expression, and a Preamble that speaks to a Malaysia still becoming itself.',
    durationMonths: 48,
    prerequisiteIds: ['fed_t4_national_reconciliation'],
    requirements: {
      description: 'Achieved reconciliation and strong democratic mandate.',
      maxCorruption: 22,
      minApproval: 62,
      minLegacyPoints: 65,
    },
    reward: {
      approvalBonus: 22,
      legacyPoints: 30,
      populationGrowthBonuses: [{ ethnicity: 'all', bonus: 0.0016 }],
      structuralBonus: { corruptionReduction: 20, humanCapitalBoost: 16, inequalityReduction: -0.055 },
      policyUnlock: {
        description: 'Unlocks "Federal Charter" — permanent constitutional stability bonus',
        unlockedOptions: {},
      },
      flavourText: 'The Federal Charter is ratified. It is not perfect — no human document is. But it is honest about what Malaysia is and aspirational about what it can become. A generation reads it and believes in it.',
    },
  },

  {
    id: 'fed_t4_direct_democracy',
    treeId: 'federal_pluralism',
    tier: 4,
    category: 'institutional',
    icon: '✋',
    name: 'Citizens Initiative & Referendum',
    description: 'Introduce citizens\' initiative (100,000 signatures forces a parliamentary vote) and binding referenda on constitutional questions. Create a Citizens Assembly mechanism for major policy decisions. Pilot participatory budgeting in all state capitals.',
    durationMonths: 24,
    prerequisiteIds: ['fed_t3_true_federation', 'fed_t2_electoral_reform'],
    requirements: {
      description: 'Strong democratic institutions.',
      maxCorruption: 28,
      minApproval: 56,
      minHumanCapital: 60,
    },
    reward: {
      approvalBonus: 12,
      legacyPoints: 10,
      structuralBonus: { corruptionReduction: 10, humanCapitalBoost: 8 },
      flavourText: 'The first citizens\' initiative — on public transport funding — forces a parliamentary vote the government does not want to hold. The government wins the vote on the merits of the argument rather than by refusing to engage. Democracy deepens.',
    },
  },

  {
    id: 'fed_t4_minority_protection',
    treeId: 'federal_pluralism',
    tier: 4,
    category: 'social',
    icon: '🌺',
    name: 'Minority Rights Constitutional Protection',
    description: 'Constitutionally entrench protections that cannot be stripped by a parliamentary majority: language rights, religious rights, cultural expression rights, and an anti-discrimination provision covering ethnicity, religion, gender, and disability.',
    durationMonths: 28,
    prerequisiteIds: ['fed_t3_anticorruption_constitution', 'fed_t3_religious_harmony'],
    requirements: {
      description: 'Constitutional reform foundation and clean institutions.',
      maxCorruption: 28,
      minApproval: 56,
    },
    reward: {
      approvalBonus: 14,
      legacyPoints: 15,
      populationGrowthBonuses: [{ ethnicity: 'Chinese', bonus: 0.0012 }, { ethnicity: 'Indian', bonus: 0.0012 }, { ethnicity: 'Bumiputera Sabah (Non-Muslim)', bonus: 0.001 }, { ethnicity: 'Bumiputera Sarawak (Non-Muslim)', bonus: 0.001 }, { ethnicity: 'Orang Asli', bonus: 0.001 }, { ethnicity: 'Others', bonus: 0.001 }],
      structuralBonus: { humanCapitalBoost: 10, inequalityReduction: -0.03, corruptionReduction: 8 },
      flavourText: 'Minority rights that existed in practice only at the sufferance of the majority now exist in law. This changes the quality of the rights, not just their quantity. Rights that require political protection are different from rights that require legal challenge to remove.',
    },
  },

  {
    id: 'fed_t4_corruption_eradication',
    treeId: 'federal_pluralism',
    tier: 4,
    category: 'institutional',
    icon: '🔒',
    name: 'Systematic Corruption Eradication',
    description: 'Launch a comprehensive 10-year anti-corruption programme: asset recovery from all 1MDB-related convictions, a whole-of-government integrity system, mandatory beneficial ownership disclosure, and whistle-blower protection with material rewards.',
    durationMonths: 40,
    prerequisiteIds: ['fed_t3_anticorruption_constitution', 'fed_t3_smart_city'],
    requirements: {
      description: 'Strong institutions and democratic mandate.',
      maxCorruption: 30,
      minApproval: 54,
    },
    reward: {
      budgetBonus: 220,
      approvalBonus: 11,
      legacyPoints: 14,
      structuralBonus: { corruptionReduction: 25, humanCapitalBoost: 8, inequalityReduction: -0.025 },
      policyUnlock: {
        description: 'Unlocks "Clean Governance Premium" — investment inflow bonus from reputation',
        unlockedOptions: {},
      },
      crossTreeSynergies: [
        {
          beneficiaryTree: 'developmental_state',
          targetMissionId: 'dev_t5_high_income_transition',
          requirementReduction: 0.2,
          description: 'Clean governance is the institutional prerequisite for high-income status.',
        },
      ],
      flavourText: 'The corruption index falls below Hong Kong. Foreign investors notice. The premium Malaysia pays on sovereign bonds — the "governance discount" priced in by markets — disappears. Clean governance has a precise ringgit value.',
    },
  },

  {
    id: 'fed_t4_federal_crisis',
    treeId: 'federal_pluralism',
    tier: 4,
    category: 'crisis',
    icon: '⚠️',
    name: 'Federal Fragmentation Crisis',
    description: 'A constitutional crisis erupts: Sabah and Sarawak simultaneously demand independence referenda. The federal compact is under the most severe strain since 1963. Crisis management will determine whether Malaysia remains a single nation.',
    durationMonths: 18,
    prerequisiteIds: ['fed_t3_true_federation'],
    requirements: {
      description: 'Triggered by inter-state constitutional tension.',
      crisisTrigger: { unemploymentAbove: 0, gdpBelow: 0 },
      maxCorruption: 150,
    },
    reward: {
      approvalBonus: -12,
      budgetBonus: -100,
      legacyPoints: -8,
      structuralBonus: { corruptionReduction: 6 },
      policyUnlock: {
        description: 'Unlocks "Federal Emergency Negotiations" — crisis constitutional mediation',
        unlockedOptions: {},
      },
      flavourText: 'The worst constitutional crisis in Malaysian history. Whether Malaysia comes through it united or fragmented depends on whether the constitutional reforms of the previous decade were genuine — or performative.',
    },
  },

  // ══════════════ TIER 5 — PLURALIST ENDGAME (7 missions) ══════════════

  {
    id: 'fed_t5_malaysia_model',
    treeId: 'federal_pluralism',
    tier: 5,
    category: 'legacy',
    icon: '🌏',
    name: 'The Malaysian Model',
    description: 'Malaysia becomes a reference case for how diverse, multi-ethnic, multi-religious societies can build democratic, pluralist institutions while maintaining economic dynamism. The Malaysian Model is studied in universities and emulated by governments globally.',
    durationMonths: 60,
    prerequisiteIds: ['fed_t4_national_reconciliation', 'fed_t4_minority_protection'],
    requirements: {
      description: 'All pluralist conditions achieved.',
      minApproval: 64,
      maxCorruption: 22,
      minHumanCapital: 66,
      minGdpGrowth: 3.5,
      minLegacyPoints: 75,
    },
    reward: {
      gdpBonus: 2.5,
      approvalBonus: 22,
      legacyPoints: 45,
      populationGrowthBonuses: [{ ethnicity: 'all', bonus: 0.002 }],
      structuralBonus: { humanCapitalBoost: 26, inequalityReduction: -0.08, corruptionReduction: 24, infrastructureBoost: 18 },
      policyUnlock: {
        description: 'Unlocks "Pluralist Democracy" — full suite of democratic governance policies',
        unlockedOptions: {},
      },
      flavourText: 'Malaysia is cited alongside Germany\'s post-war reconciliation and Rwanda\'s post-genocide reconstruction as examples of societies that chose to build rather than to remain broken. The comparison is imperfect. The achievement is real.',
    },
  },

  {
    id: 'fed_t5_pan_asean_rights',
    treeId: 'federal_pluralism',
    tier: 5,
    category: 'external',
    icon: '🌐',
    name: 'ASEAN Human Rights Framework',
    description: 'Lead the creation of a binding ASEAN Human Rights Convention — modelled on the ECHR but adapted for Southeast Asian context. Malaysia, having reformed its own institutions, becomes the credible advocate for regional human rights standards.',
    durationMonths: 44,
    prerequisiteIds: ['fed_t5_malaysia_model'],
    requirements: {
      description: 'Achieved Malaysian model status.',
      maxCorruption: 20,
      minApproval: 62,
      minLegacyPoints: 80,
    },
    reward: {
      approvalBonus: 16,
      legacyPoints: 25,
      populationGrowthBonuses: [{ ethnicity: 'all', bonus: 0.0014 }],
      structuralBonus: { corruptionReduction: 14, humanCapitalBoost: 14, inequalityReduction: -0.04 },
      flavourText: 'The ASEAN Human Rights Convention enters force with twelve ratifications. It is the most significant achievement of Malaysian diplomacy since independence. It is also the thing that makes future Malaysian governments think twice before backsliding.',
    },
  },

  {
    id: 'fed_t5_climate_justice',
    treeId: 'federal_pluralism',
    tier: 5,
    category: 'social',
    icon: '🌊',
    name: 'Climate Justice Leadership',
    description: 'Lead the G77 + China bloc in demanding Loss and Damage finance from wealthy nations. Establish Malaysia as the host of ASEAN Climate Finance Cooperation. Provide climate refugee protection domestically and advocate globally for climate-displaced communities.',
    durationMonths: 36,
    prerequisiteIds: ['fed_t4_corruption_eradication', 'fed_t3_smart_city'],
    requirements: {
      description: 'Strong institutions and environmental commitment.',
      maxCorruption: 25,
      minApproval: 56,
    },
    reward: {
      budgetBonus: 140,
      approvalBonus: 12,
      legacyPoints: 18,
      populationGrowthBonuses: [{ ethnicity: 'all', bonus: 0.0009 }],
      structuralBonus: { humanCapitalBoost: 11, inequalityReduction: -0.028, corruptionReduction: 8 },
      flavourText: 'Malaysia speaks for the Global South on climate at the UNGA. The Loss and Damage Fund pledges increase after Malaysian advocacy. The moral authority to make this case was earned by the domestic reforms of the previous decade.',
    },
  },

  {
    id: 'fed_t5_technology_rights',
    treeId: 'federal_pluralism',
    tier: 5,
    category: 'institutional',
    icon: '📡',
    name: 'Digital Rights and AI Governance',
    description: 'Establish Malaysia as the global leader in democratic AI governance: a National AI Ethics Commission, mandatory algorithmic impact assessments for all public uses of AI, a Digital Bill of Rights, and an ASEAN AI Governance Framework.',
    durationMonths: 32,
    prerequisiteIds: ['fed_t3_smart_city', 'fed_t4_direct_democracy'],
    requirements: {
      description: 'Digital society and democratic institutions.',
      minHumanCapital: 66,
      maxCorruption: 25,
      requiredPolicy: { openTrade: true },
    },
    reward: {
      gdpBonus: 1.2,
      legacyPoints: 16,
      structuralBonus: { humanCapitalBoost: 13, corruptionReduction: 11, inequalityReduction: -0.022 },
      policyUnlock: {
        description: 'Unlocks "Democratic AI Governance" — technology rights framework',
        unlockedOptions: {},
      },
      crossTreeSynergies: [
        {
          beneficiaryTree: 'developmental_state',
          targetMissionId: 'dev_t4_5g_digital',
          requirementReduction: 0.2,
          description: 'Democratic digital rights framework provides the governance layer for 5G smart infrastructure.',
        },
      ],
      flavourText: 'Malaysia\'s AI governance framework becomes the template for ten other countries. Technology companies that operate in Malaysia must comply with algorithmic accountability requirements. Some choose not to operate in Malaysia. Most adapt.',
    },
  },

  {
    id: 'fed_t5_internal_migration',
    treeId: 'federal_pluralism',
    tier: 5,
    category: 'social',
    icon: '🏙️',
    name: 'Internal Migration Equity',
    description: 'Address the consequences of six decades of urban migration: housing, voting rights, cultural infrastructure, and economic inclusion for the urban poor who were left behind by the development model that built the cities they now inhabit.',
    durationMonths: 30,
    prerequisiteIds: ['fed_t4_national_reconciliation', 'fed_t3_urban_rural_rebalance'],
    requirements: {
      description: 'Reconciliation complete and economic capacity.',
      minApproval: 58,
      minHumanCapital: 62,
    },
    reward: {
      gdpBonus: 0.7,
      approvalBonus: 10,
      legacyPoints: 14,
      populationGrowthBonuses: [{ ethnicity: 'all', bonus: 0.001 }],
      structuralBonus: { humanCapitalBoost: 9, inequalityReduction: -0.034, corruptionReduction: 7 },
      flavourText: 'The generation that moved from kampungs to Chow Kit to Puchong to Cyberjaya finally has a city that acknowledges them. The urban poor are no longer an afterthought in development planning — they are its subject.',
    },
  },

  {
    id: 'fed_t5_disintegration_risk',
    treeId: 'federal_pluralism',
    tier: 5,
    category: 'crisis',
    icon: '💥',
    name: 'Malaysian Spring: Democratic Backslide',
    description: 'A democratic backslide — through a Sheraton Move-style political crisis, a populist authoritarian winning the Prime Ministership, or a constitutional coup — threatens to reverse decades of pluralist reform. The institutions are tested.',
    durationMonths: 18,
    prerequisiteIds: ['fed_t3_true_federation'],
    requirements: {
      description: 'Triggered by severe political instability.',
      crisisTrigger: { gdpBelow: 0, unemploymentAbove: 8 },
    },
    reward: {
      approvalBonus: -15,
      legacyPoints: -10,
      structuralBonus: { corruptionReduction: -8, humanCapitalBoost: 4 },
      policyUnlock: {
        description: 'Unlocks "Constitutional Emergency Defence" — civil society counter-mobilisation',
        unlockedOptions: {},
      },
      flavourText: 'The institutions hold — just. The new Sedition Act is challenged in court and overturned. The Independent Electoral Commission refuses to delay the election. Civil society mobilises in numbers not seen since Bersih. Malaysia remembers what it was trying to build.',
      historicalNote: 'The Sheraton Move (2020) — in which Pakatan Harapan\'s government collapsed through parliamentary defections — showed the fragility of Malaysian democratic gains. No constitutional safeguard can fully prevent this.',
    },
  },

  {
    id: 'fed_t5_new_generation_compact',
    treeId: 'federal_pluralism',
    tier: 5,
    category: 'legacy',
    icon: '🌟',
    name: 'New Generation Social Compact',
    description: 'A new generation of Malaysians — born after 1998, who have never known anything but a plural, contested, democratic Malaysia — takes ownership of the social compact. They renegotiate it for the 22nd century.',
    durationMonths: 40,
    prerequisiteIds: ['fed_t5_malaysia_model'],
    requirements: {
      description: 'Mature pluralist democracy achieved.',
      minApproval: 65,
      maxCorruption: 18,
      minLegacyPoints: 90,
    },
    reward: {
      gdpBonus: 1.5,
      approvalBonus: 20,
      legacyPoints: 50,
      populationGrowthBonuses: [{ ethnicity: 'all', bonus: 0.002 }],
      structuralBonus: { humanCapitalBoost: 22, corruptionReduction: 20, inequalityReduction: -0.06, infrastructureBoost: 14 },
      flavourText: 'The question is no longer what kind of country Malaysia is trying to become. The question is what kind of country Malaysia has become — and how it plans to remain it. This is the question of a mature nation. Malaysia has earned the right to ask it.',
    },
  },
];

export { FEDERAL_PLURALISM_MISSIONS };

