// ─────────────────────────────────────────────────────────────
// TREE 2: DEVELOPMENTAL STATE — 35 MISSIONS, 5 TIERS
// ─────────────────────────────────────────────────────────────
//
// NARRATIVE ARC:
//   Tier 1 — State Capacity: Planning, Infrastructure, Data, Social Insurance
//   Tier 2 — Guided Industrialisation: EPZ, Green Revolution, Civil Service,
//             FORK: Heavy State Capitalism vs Light Electronics
//   Tier 3 — Industrial Maturity: Petronas, High-Speed Rail, MSC
//   Tier 4 — FORK: Knowledge Economy vs Resource Nationalism
//   Tier 5 — Endgame: High-Income Transition OR Asian Crisis + Recovery
// ─────────────────────────────────────────────────────────────

const DEVELOPMENTAL_STATE_MISSIONS = [
  // ══════════════ TIER 1 — STATE CAPACITY (7 missions) ══════════════

  {
    id: 'dev_t1_five_year_plan',
    treeId: 'developmental_state',
    tier: 1,
    category: 'institutional',
    icon: '📋',
    name: 'Malaysia Plan',
    description: 'Launch a centralised Five-Year Development Plan with measurable targets for growth, poverty, employment, and infrastructure. Establish the Economic Planning Unit (EPU) with direct Prime Ministerial authority, separating capital development expenditure from operating expenditure.',
    durationMonths: 7,
    prerequisiteIds: [],
    requirements: {
      description: 'Government in power for at least 6 months.',
      minMonthsInPower: 6,
    },
    reward: {
      gdpBonus: 0.25,
      legacyPoints: 2,
      structuralBonus: { humanCapitalBoost: 2, infrastructureBoost: 2 },
      policyUnlock: {
        description: 'Unlocks "Development Expenditure Budget" spending option',
        unlockedOptions: { spendingLevel: ['development_expenditure'] },
      },
      flavourText: 'The Plan is published. EPU technocrats finally have a mandate and a measuring stick. Ministers who oppose development spending now face written targets. Numbers have power.',
      historicalNote: 'Malaysia has issued 12 Five-Year Plans since 1965. The EPU became one of the most capable economic planning agencies in the developing world, renowned for its detailed sectoral targets.',
    },
  },

  {
    id: 'dev_t1_infrastructure',
    treeId: 'developmental_state',
    tier: 1,
    category: 'economic',
    icon: '🏗️',
    name: 'National Infrastructure Drive',
    description: 'Electrify rural areas, lay trunk roads connecting agricultural hinterlands to ports, expand Port Klang capacity, and construct the Kenyir and Temenggor hydroelectric dams. Establish a Highway Authority to coordinate road planning.',
    durationMonths: 22,
    prerequisiteIds: [],
    requirements: {
      description: 'Expansionary spending.',
      requiredPolicy: { spendingLevel: 'expansionary' },
    },
    reward: {
      gdpBonus: 0.55,
      unemploymentBonus: 0.7,
      legacyPoints: 4,
      structuralBonus: { infrastructureBoost: 14 },
      populationGrowthBonuses: [{ ethnicity: 'all', bonus: 0.0003 }],
      crossTreeSynergies: [
        {
          beneficiaryTree: 'export_tiger',
          targetMissionId: 'tiger_t1_port_development',
          requirementReduction: 0.25,
          description: 'National road and port investment lowers the threshold for Port Klang expansion.',
        },
      ],
      flavourText: 'New roads knit the peninsula together. Remote kampungs light up at night. The trunk roads become arteries for commerce that no one anticipated. Maps of Malaysia begin to look different.',
      historicalNote: 'The North-South Highway, Kenyir Dam, and rural electrification programmes drove Peninsular Malaysia\'s rural-urban transformation in the 1970s–80s.',
    },
  },

  {
    id: 'dev_t1_statistics_bureau',
    treeId: 'developmental_state',
    tier: 1,
    category: 'institutional',
    icon: '📊',
    name: 'Economic Statistics Bureau',
    description: 'Establish rigorous national accounts collection, household income surveys disaggregated by ethnicity and region, and a poverty measurement methodology. Publish data quarterly and allow independent researchers access to anonymised datasets.',
    durationMonths: 7,
    prerequisiteIds: [],
    requirements: { description: 'Any stable government.' },
    reward: {
      legacyPoints: 2,
      structuralBonus: { corruptionReduction: 3 },
      policyUnlock: {
        description: 'Enables "Targeted Subsidy" — replaces blanket with means-tested welfare',
        unlockedOptions: { welfareLevel: ['targeted'] },
      },
      flavourText: 'Numbers replace rumours. Policy begins to follow evidence rather than assumption — at least in principle. The data also reveals uncomfortable truths about inter-ethnic inequality that politicians would prefer to explain away.',
      historicalNote: 'The Department of Statistics Malaysia\'s household income surveys, begun in 1970, became the benchmark for tracking poverty and inequality across ethnic groups. They remain the most reliable data source on Malaysian social conditions.',
    },
  },

  {
    id: 'dev_t1_epf',
    treeId: 'developmental_state',
    tier: 1,
    category: 'social',
    icon: '👴',
    name: 'Employees Provident Fund',
    description: 'Formalise and expand mandatory pension contributions: 11% from employee, 12% from employer. Invest EPF assets in long-term infrastructure bonds and equity, creating a deep domestic capital pool. Establish a professional investment committee.',
    durationMonths: 14,
    prerequisiteIds: [],
    requirements: {
      description: 'Moderate welfare and balanced budget.',
      requiredPolicy: { welfareLevel: 'moderate' },
      minBudgetBalance: -250,
    },
    reward: {
      budgetBonus: 80,
      legacyPoints: 4,
      structuralBonus: { humanCapitalBoost: 3, inequalityReduction: -0.01 },
      policyUnlock: {
        description: 'Unlocks "EPF Infrastructure Bond" financing option',
        unlockedOptions: { spendingLevel: ['epf_infrastructure_bond'] },
      },
      flavourText: 'The EPF becomes Malaysia\'s largest institutional investor. Its domestic capital pool funds toll roads, utilities, and airports — without incurring foreign debt. The independence of its investment decisions becomes a permanent political battleground.',
      historicalNote: 'EPF (established 1951, expanded 1969) grew to manage over RM1 trillion by 2020, making Malaysia uniquely able to fund major development domestically without relying on foreign bond markets.',
    },
  },

  {
    id: 'dev_t1_technocrat_corps',
    treeId: 'developmental_state',
    tier: 1,
    category: 'institutional',
    icon: '👔',
    name: 'Technocrat Civil Service Corps',
    description: 'Establish a Senior Executives Service to attract and retain elite civil servants with private-sector-competitive salaries. Create the Malaysian Administrative Modernisation Unit (MAMPU). Send top civil servants to Harvard Kennedy School, LSE, and NUS for advanced training.',
    durationMonths: 16,
    prerequisiteIds: ['dev_t1_statistics_bureau'],
    requirements: {
      description: 'Low corruption and stable governance.',
      maxCorruption: 48,
      minApproval: 38,
    },
    reward: {
      legacyPoints: 4,
      structuralBonus: { corruptionReduction: 7, humanCapitalBoost: 8 },
      policyUnlock: {
        description: 'Unlocks "Performance-based Civil Service" governance option',
        unlockedOptions: {},
      },
      crossTreeSynergies: [
        {
          beneficiaryTree: 'bumiputera_agenda',
          targetMissionId: 'bumi_t2_nep',
          requirementReduction: 0.1,
          description: 'Professional civil service can implement complex affirmative action programmes without capture.',
        },
      ],
      flavourText: 'The best graduates now have a reason to consider government service. EPU and Treasury begin to operate with the discipline of a consulting firm. The result shows in the quality of the Malaysia Plan.',
    },
  },

  {
    id: 'dev_t1_bank_negara_independence',
    treeId: 'developmental_state',
    tier: 1,
    category: 'institutional',
    icon: '🏦',
    name: 'Central Bank Credibility Framework',
    description: 'Grant Bank Negara Malaysia operational independence in monetary policy while clarifying its development finance mandate. Establish an inflation targeting framework, build foreign reserves to 6 months of imports, and develop the ringgit bond market.',
    durationMonths: 12,
    prerequisiteIds: ['dev_t1_statistics_bureau'],
    requirements: {
      description: 'Low inflation and stable budget.',
      maxCorruption: 50,
      minBudgetBalance: -300,
    },
    reward: {
      inflationModifier: -0.8,
      budgetBonus: 45,
      legacyPoints: 4,
      structuralBonus: { corruptionReduction: 5 },
      crossTreeSynergies: [
        {
          beneficiaryTree: 'liberal_open_economy',
          targetMissionId: 'lib_t1_stock_exchange',
          requirementReduction: 0.2,
          description: 'Central bank credibility is a prerequisite for deep capital markets.',
        },
      ],
      flavourText: 'Bank Negara becomes one of Asia\'s most respected central banks. Its foreign reserves management — conservative, patient, professional — will matter enormously in 1997.',
      historicalNote: 'Bank Negara\'s Governor Jaffar Hussein (1980-1994) established its credibility. His successor Zeti Akhtar Aziz (2000-2016) was widely regarded as Asia\'s finest central banker.',
    },
  },

  {
    id: 'dev_t1_sosco',
    treeId: 'developmental_state',
    tier: 1,
    category: 'social',
    icon: '🛡️',
    name: 'Social Security Organisation',
    description: 'Establish SOCSO (Pertubuhan Keselamatan Sosial) — mandatory employment injury insurance and invalidity pension for all private sector workers. Extend coverage to self-employed workers. Create a national rehabilitation centre for workplace injury recovery.',
    durationMonths: 10,
    prerequisiteIds: ['dev_t1_epf'],
    requirements: {
      description: 'Moderate welfare commitment.',
      requiredPolicy: { welfareLevel: 'moderate' },
    },
    reward: {
      approvalBonus: 4,
      unemploymentBonus: 0.2,
      legacyPoints: 2,
      populationGrowthBonuses: [{ ethnicity: 'all', bonus: 0.0003 }],
      structuralBonus: { humanCapitalBoost: 3, inequalityReduction: -0.007 },
      flavourText: 'Workers injured at factories now receive medical treatment and income replacement rather than destitution. The safety net is thin but real — a foundation that can be built upon.',
      historicalNote: 'SOCSO was established in 1971. Coverage expanded slowly over decades. By 2020 it protected over 6 million workers, but self-employed and informal workers remained excluded until the 2020 Perlindungan Tenang scheme.',
    },
  },

  // ══════════════ TIER 2 — GUIDED INDUSTRIALISATION (8 missions) ══════════════

  {
    id: 'dev_t2_epz',
    treeId: 'developmental_state',
    tier: 2,
    category: 'economic',
    icon: '🏭',
    name: 'Export Processing Zones',
    description: 'Create Free Trade Zones in Penang (Bayan Lepas), Shah Alam, and Johor Bahru with tax holidays, duty-free imports of components, subsidised utilities, and a streamlined investment approval process through MIDA. Target Japanese, American, and Taiwanese electronics manufacturers.',
    durationMonths: 26,
    prerequisiteIds: ['dev_t1_infrastructure'],
    requirements: {
      description: 'Open trade, industry priority, adequate infrastructure.',
      requiredPolicy: { openTrade: true, prioritySector: 'industry' },
      minInfrastructure: 43,
    },
    reward: {
      gdpBonus: 1.35,
      unemploymentBonus: 1.2,
      budgetBonus: 75,
      legacyPoints: 6,
      structuralBonus: { humanCapitalBoost: 6, infrastructureBoost: 4 },
      crossTreeSynergies: [
        {
          beneficiaryTree: 'liberal_open_economy',
          targetMissionId: 'lib_t2_fdi_zones',
          requirementReduction: 0.2,
          description: 'EPZ institutional framework makes broad FDI attraction more tractable.',
        },
        {
          beneficiaryTree: 'export_tiger',
          targetMissionId: 'tiger_t2_electronics_export',
          requirementReduction: 0.2,
          description: 'EPZ infrastructure is the foundation for the electronics export drive.',
        },
      ],
      flavourText: 'Japanese and Taiwanese factories arrive in Penang and Johor, bringing component technology, wage discipline, and the work ethic of Kaizen. Malaysia\'s export profile begins the shift from raw commodities.',
      historicalNote: 'Penang\'s Bayan Lepas Free Trade Zone, established 1972, became one of the world\'s leading electronics clusters. Intel built its first overseas factory there. By 1990, Penang accounted for 25% of world semiconductor production.',
    },
  },

  {
    id: 'dev_t2_green_revolution',
    treeId: 'developmental_state',
    tier: 2,
    category: 'economic',
    icon: '🌾',
    name: 'Green Revolution Programme',
    description: 'Introduce the Muda Irrigation Scheme in Kedah-Perlis, high-yield MUDA rice varieties, and extension services reaching every kampung. Establish MADA (Muda Agricultural Development Authority). Subsidise fertiliser and mechanise harvesting.',
    durationMonths: 20,
    prerequisiteIds: ['dev_t1_five_year_plan'],
    requirements: {
      description: 'Agriculture priority and adequate human capital.',
      requiredPolicy: { prioritySector: 'agriculture' },
      minHumanCapital: 23,
    },
    reward: {
      gdpBonus: 0.7,
      inflationModifier: -0.55,
      unemploymentBonus: 0.5,
      legacyPoints: 4,
      populationGrowthBonuses: [{ ethnicity: 'Malay', bonus: 0.0007 }],
      structuralBonus: { inequalityReduction: -0.016 },
      flavourText: 'The Muda scheme transforms Kedah into Malaysia\'s rice bowl. Paddy farmers double their yields. But prices fall, and many quietly abandon the land for factories in Penang — the Green Revolution\'s bitter irony.',
      historicalNote: 'The MADA Authority, established 1970, doubled irrigated rice area. Malaysia achieved ~75% rice self-sufficiency by 1985. But rural-urban migration accelerated — the scheme\'s success undermined its own labour base.',
    },
  },

  {
    id: 'dev_t2_civil_service_reform',
    treeId: 'developmental_state',
    tier: 2,
    category: 'institutional',
    icon: '🏛️',
    name: 'Civil Service Modernisation',
    description: 'Benchmark civil service salaries against the private sector to reduce talent drain. Introduce performance appraisals linked to promotion. Reduce ministerial discretion in civil service appointments. Digitalise government services, cutting the average application processing time from months to days.',
    durationMonths: 22,
    prerequisiteIds: ['dev_t1_technocrat_corps', 'dev_t1_statistics_bureau'],
    requirements: {
      description: 'Corruption below 48.',
      maxCorruption: 48,
    },
    reward: {
      budgetBonus: 55,
      legacyPoints: 6,
      structuralBonus: { corruptionReduction: 11, humanCapitalBoost: 6 },
      policyUnlock: {
        description: 'Unlocks "Performance-based Public Service" spending multiplier',
        unlockedOptions: { spendingLevel: ['performance_based'] },
      },
      crossTreeSynergies: [
        {
          beneficiaryTree: 'liberal_open_economy',
          targetMissionId: 'lib_t2_regulatory_state',
          requirementReduction: 0.25,
          description: 'Professionalised civil service can operate independent regulatory agencies.',
        },
      ],
      flavourText: 'The public service stops leaking money at quite the same rate. Contracts more often go to the competent. But merit-based hiring creates tension with ethnic quota expectations — a contradiction the system never resolves.',
      historicalNote: 'MAMPU drove civil service reform from the 1980s. Malaysia ranked in the top 20-30 of Transparency International\'s Corruption Perceptions Index in the 1990s before declining from 2000 onward.',
    },
  },

  {
    id: 'dev_t2_heavy_industry_dev',
    treeId: 'developmental_state',
    tier: 2,
    category: 'economic',
    icon: '⚙️',
    name: 'State Heavy Industries Corporation',
    description: 'Establish HICOM as the umbrella for state-backed heavy industry: Perwaja steel, DRB-HICOM automotive, Proton, and downstream petrochemicals. Adopt the POSCO model — state ownership, professional management, export discipline.',
    durationMonths: 32,
    prerequisiteIds: ['dev_t1_infrastructure', 'dev_t1_technocrat_corps'],
    branch: 'heavy_industry',
    mutuallyExclusiveWith: ['dev_t2_light_electronics'],
    requirements: {
      description: 'Industry priority and expansionary spending.',
      requiredPolicy: { prioritySector: 'industry', spendingLevel: 'expansionary' },
      minInfrastructure: 40,
      minBudgetBalance: -400,
    },
    reward: {
      gdpBonus: 1.1,
      unemploymentBonus: 0.8,
      inflationModifier: 0.4,
      budgetBonus: -100,
      legacyPoints: 5,
      structuralBonus: { infrastructureBoost: 10, humanCapitalBoost: 4, corruptionReduction: -5 },
      policyUnlock: {
        description: 'Unlocks "National Champion Policy" — protective tariffs for strategic sectors',
        unlockedOptions: { prioritySector: ['national_champion'] },
      },
      crossTreeSynergies: [
        {
          beneficiaryTree: 'bumiputera_agenda',
          targetMissionId: 'bumi_t3_petronas_state_oil',
          requirementReduction: 0.1,
          description: 'State heavy industry capacity improves downstream petroleum processing.',
        },
      ],
      flavourText: 'Malaysia joins South Korea on the heavy industry path. The question remains whether it has the market size, the export discipline, and the institutional quality to sustain it.',
      historicalNote: 'HICOM established 1980. The Proton/Perwaja strategy mirrored POSCO/Hyundai but without South Korea\'s export markets or cold-war US support. Perwaja never became competitive; Proton needed perpetual protection.',
    },
  },

  {
    id: 'dev_t2_light_electronics',
    treeId: 'developmental_state',
    tier: 2,
    category: 'economic',
    icon: '💡',
    name: 'Electronics & Light Industry Cluster',
    description: 'Focus state investment on electronics assembly, precision engineering, and light manufacturing — leveraging comparative advantage in skilled lower-cost labour. Create technology parks with shared R&D facilities in Penang, Kulim, and Johor.',
    durationMonths: 22,
    prerequisiteIds: ['dev_t2_epz', 'dev_t1_technocrat_corps'],
    branch: 'electronics',
    mutuallyExclusiveWith: ['dev_t2_heavy_industry_dev'],
    requirements: {
      description: 'Open trade, industry priority, adequate human capital.',
      requiredPolicy: { openTrade: true, prioritySector: 'industry' },
      minHumanCapital: 32,
    },
    reward: {
      gdpBonus: 1.4,
      unemploymentBonus: 1.3,
      budgetBonus: 60,
      legacyPoints: 6,
      structuralBonus: { humanCapitalBoost: 9, infrastructureBoost: 5, corruptionReduction: 3 },
      crossTreeSynergies: [
        {
          beneficiaryTree: 'export_tiger',
          targetMissionId: 'tiger_t2_electronics_export',
          requirementReduction: 0.35,
          description: 'Electronics cluster directly provides the base for export tiger strategy.',
        },
        {
          beneficiaryTree: 'liberal_open_economy',
          targetMissionId: 'lib_t2_fdi_zones',
          requirementReduction: 0.2,
          description: 'Established cluster reduces the cost of attracting new FDI.',
        },
      ],
      flavourText: 'Penang emerges as Southeast Asia\'s electronics capital. Motorola, Intel, and Hitachi compete for the same trained workforce. Wages rise. Labour discipline tightens. A new Malaysian industrial working class is born.',
    },
  },

  {
    id: 'dev_t2_roads_highways',
    treeId: 'developmental_state',
    tier: 2,
    category: 'economic',
    icon: '🛣️',
    name: 'North-South Highway Project',
    description: 'Build the 772km North-South Expressway connecting Johor Bahru to Bukit Kayu Hitam — the spine of the Malaysian economy. Use toll revenue concessions to attract private financing while maintaining public oversight of standards and pricing.',
    durationMonths: 36,
    prerequisiteIds: ['dev_t1_infrastructure'],
    requirements: {
      description: 'Adequate infrastructure base and manageable deficit.',
      minInfrastructure: 35,
      minBudgetBalance: -350,
    },
    reward: {
      gdpBonus: 0.85,
      unemploymentBonus: 0.9,
      legacyPoints: 5,
      structuralBonus: { infrastructureBoost: 16 },
      populationGrowthBonuses: [{ ethnicity: 'all', bonus: 0.0005 }],
      crossTreeSynergies: [
        {
          beneficiaryTree: 'export_tiger',
          targetMissionId: 'tiger_t1_port_development',
          requirementReduction: 0.15,
          description: 'Highway connectivity dramatically increases port hinterland efficiency.',
        },
      ],
      flavourText: 'The Plus Highway reshapes the geography of Malaysian commerce. Journey times from Johor to Penang fall from 12 hours to 5. PLUS Berhad becomes one of Malaysia\'s most profitable concessionaires — and most politically contentious.',
      historicalNote: 'The North-South Expressway, completed 1994, was financed through a Build-Operate-Transfer concession with UEM. The toll concession became a template for Malaysian privatisation and a source of perpetual controversy about rates and terms.',
    },
  },

  {
    id: 'dev_t2_port_free_trade',
    treeId: 'developmental_state',
    tier: 2,
    category: 'external',
    icon: '⚓',
    name: 'Port Klang Free Zone',
    description: 'Develop the Port Klang Free Zone as an advanced logistics and manufacturing hub with zero-tariff importing, bonded warehousing, and a dedicated customs fast-lane. Position Malaysia as the regional logistics hub for ASEAN commodity trade.',
    durationMonths: 20,
    prerequisiteIds: ['dev_t2_roads_highways'],
    requirements: {
      description: 'Open trade and strong infrastructure.',
      requiredPolicy: { openTrade: true },
      minInfrastructure: 48,
    },
    reward: {
      gdpBonus: 0.9,
      budgetBonus: 90,
      legacyPoints: 4,
      structuralBonus: { infrastructureBoost: 8 },
      crossTreeSynergies: [
        {
          beneficiaryTree: 'export_tiger',
          targetMissionId: 'tiger_t3_tiger_economy',
          requirementReduction: 0.1,
          description: 'Free zone infrastructure reduces the logistics cost of export-led growth.',
        },
      ],
      flavourText: 'Containers from across Asia move through Port Klang. Malaysia becomes the indispensable node between East Asian manufacturers and global consumers. The PKFZ scandal — RM12 billion in losses — is a future problem.',
      historicalNote: 'Port Klang became the 12th busiest port globally by 2019. The Port Klang Free Zone scandal (2007) cost RM12 billion and resulted in multiple prosecutions — a cautionary tale about infrastructure governance.',
    },
  },

  {
    id: 'dev_t2_utm_uia',
    treeId: 'developmental_state',
    tier: 2,
    category: 'social',
    icon: '🔬',
    name: 'Technical University Network',
    description: 'Establish Universiti Teknologi Malaysia, Universiti Islam Antarabangsa, and Universiti Malaysia Sarawak to build a distributed higher education system. Mandate that 40% of graduates study STEM. Introduce the Human Resource Development Fund (HRDF) levy on large employers.',
    durationMonths: 18,
    prerequisiteIds: ['dev_t1_technocrat_corps', 'dev_t1_sosco'],
    requirements: {
      description: 'Adequate budget and human capital foundation.',
      minBudgetBalance: -200,
      minHumanCapital: 28,
    },
    reward: {
      unemploymentBonus: 0.65,
      legacyPoints: 5,
      structuralBonus: { humanCapitalBoost: 12, inequalityReduction: -0.012 },
      populationGrowthBonuses: [{ ethnicity: 'all', bonus: 0.0004 }],
      crossTreeSynergies: [
        {
          beneficiaryTree: 'bumiputera_agenda',
          targetMissionId: 'bumi_t2_education_quota',
          requirementReduction: 0.1,
          description: 'Expanded university network provides the places for quota programmes to function.',
        },
      ],
      flavourText: 'New universities multiply across the country. Graduate unemployment begins to emerge as a problem almost immediately — the quantity of graduates rises faster than the quality of economic opportunities for them.',
    },
  },

  // ══════════════ TIER 3 — INDUSTRIAL MATURITY (7 missions) ══════════════

  {
    id: 'dev_t3_petronas',
    treeId: 'developmental_state',
    tier: 3,
    category: 'economic',
    icon: '🛢️',
    name: 'National Petroleum Corporation',
    description: 'Nationalise oil and gas extraction rights under PETRONAS with a mandatory 30% participation by the state corporation. Establish the PETRONAS Carigali drilling subsidiary, the Gas Malaysia pipeline network, and the MLNG liquefied natural gas complex in Bintulu.',
    durationMonths: 26,
    prerequisiteIds: ['dev_t2_epz', 'dev_t2_green_revolution'],
    requirements: {
      description: 'High commodity prices and manageable corruption.',
      minCommodityIndex: 108,
      maxCorruption: 52,
    },
    reward: {
      gdpBonus: 1.55,
      budgetBonus: 240,
      inflationModifier: 0.3,
      legacyPoints: 9,
      structuralBonus: { infrastructureBoost: 13, corruptionReduction: -4, humanCapitalBoost: 5 },
      policyUnlock: {
        description: 'Unlocks "Petrodollar Stimulus" emergency spending option',
        unlockedOptions: { spendingLevel: ['petrodollar_stimulus'] },
      },
      crossTreeSynergies: [
        {
          beneficiaryTree: 'bumiputera_agenda',
          targetMissionId: 'bumi_t3_sovereign_wealth',
          requirementReduction: 0.2,
          description: 'PETRONAS revenues directly fund sovereign wealth fund capitalisation.',
        },
      ],
      flavourText: 'Oil revenues transform the government\'s fiscal position. The Malaysia Plan\'s development targets become realistic. PETRONAS also becomes the ultimate political patronage vehicle — its contracting decisions determining the fortunes of the UMNO business class.',
      historicalNote: 'PETRONAS established 1974. By 2019 it contributed ~24% of federal revenue. Its Sarawak operations triggered a constitutional dispute over oil royalty sharing that remains unresolved.',
    },
  },

  {
    id: 'dev_t3_msc',
    treeId: 'developmental_state',
    tier: 3,
    category: 'economic',
    icon: '💻',
    name: 'Multimedia Super Corridor',
    description: 'Designate the 50km × 15km corridor from KLCC to KLIA as a special technology zone: Cyberjaya (tech campus), Putrajaya (digital government), and an MSC-certified company status with regulatory freedoms unavailable elsewhere. Issue the "Bill of Guarantees" promising no internet censorship.',
    durationMonths: 40,
    prerequisiteIds: ['dev_t2_civil_service_reform', 'dev_t2_light_electronics'],
    requirements: {
      description: 'High human capital, infrastructure, and open trade.',
      minHumanCapital: 53,
      minInfrastructure: 58,
      requiredPolicy: { openTrade: true },
    },
    reward: {
      gdpBonus: 2.1,
      unemploymentBonus: 1.4,
      inflationModifier: 0.25,
      budgetBonus: 110,
      approvalBonus: 9,
      legacyPoints: 10,
      populationGrowthBonuses: [{ ethnicity: 'Chinese', bonus: 0.0007 }, { ethnicity: 'Indian', bonus: 0.0004 }, { ethnicity: 'all', bonus: 0.0003 }],
      structuralBonus: { humanCapitalBoost: 14, infrastructureBoost: 9, corruptionReduction: 5 },
      policyUnlock: {
        description: 'Unlocks "Digital Economy" sector option',
        unlockedOptions: { prioritySector: ['digital'] },
      },
      flavourText: 'Cyberjaya glows on the map. The Bill of Guarantees becomes Malaysia\'s most cited policy document internationally. The dotcom bust will test whether the vision was substance or spectacle.',
      historicalNote: 'MSC Malaysia launched 1996. The no-censorship guarantee lasted until 2011. By 2020 it housed 3,000+ companies but Cyberjaya remained smaller than envisioned, partly due to the 1997 crisis and 2000 dotcom bust.',
    },
  },

  {
    id: 'dev_t3_high_speed_rail',
    treeId: 'developmental_state',
    tier: 3,
    category: 'economic',
    icon: '🚄',
    name: 'Pan-Malaysia Trunk Railway',
    description: 'Electrify and double-track the KTM main line. Build the Klang Valley MRT and LRT networks. Develop the East Coast Rail Link. Plan the KL-Singapore High Speed Rail to compress economic geography and end the peninsula\'s dependency on the car.',
    durationMonths: 54,
    prerequisiteIds: ['dev_t2_civil_service_reform', 'dev_t2_heavy_industry_dev'],
    requirements: {
      description: 'Strong infrastructure base and manageable deficit.',
      minInfrastructure: 62,
      minBudgetBalance: -320,
    },
    reward: {
      gdpBonus: 1.35,
      unemploymentBonus: 0.75,
      legacyPoints: 8,
      populationGrowthBonuses: [{ ethnicity: 'all', bonus: 0.0007 }],
      structuralBonus: { infrastructureBoost: 22, inequalityReduction: -0.018 },
      flavourText: 'Kedah and Johor are three hours apart. Economic geography is redrawn overnight. But cost overruns and political delays test public confidence in state delivery — and the ECRL becomes a geopolitical football.',
      historicalNote: 'The KL-Singapore HSR was cancelled and revised multiple times. The KLMRT (2017) succeeded. The East Coast Rail Link — originally RM66 billion, renegotiated to RM44 billion with China — became a sovereignty controversy.',
    },
  },

  {
    id: 'dev_t3_industrial_policy_2',
    treeId: 'developmental_state',
    tier: 3,
    category: 'economic',
    icon: '🔩',
    name: 'Industrial Master Plan II',
    description: 'Publish IMP2: a detailed roadmap for upgrading from assembly to process industries, developing design capability, and moving Malaysia up the value chain in electronics, oleochemicals, and pharmaceuticals. Establish the SIRIM quality standards body.',
    durationMonths: 20,
    prerequisiteIds: ['dev_t2_light_electronics', 'dev_t2_civil_service_reform'],
    requirements: {
      description: 'Adequate human capital and growth momentum.',
      minHumanCapital: 45,
      minGdpGrowth: 4.0,
    },
    reward: {
      gdpBonus: 1.0,
      unemploymentBonus: 0.8,
      legacyPoints: 6,
      structuralBonus: { humanCapitalBoost: 8, corruptionReduction: 3 },
      crossTreeSynergies: [
        {
          beneficiaryTree: 'export_tiger',
          targetMissionId: 'tiger_t3_commodity_diversification',
          requirementReduction: 0.2,
          description: 'IMP2 provides the roadmap for downstream commodity processing.',
        },
      ],
      flavourText: 'Malaysian factories begin doing more than assembly. Process engineers replace production workers in some plants. The value-added per employee begins to rise — slowly, then faster.',
    },
  },

  {
    id: 'dev_t3_putrajaya',
    treeId: 'developmental_state',
    tier: 3,
    category: 'institutional',
    icon: '🏛️',
    name: 'Putrajaya: Digital Federal Capital',
    description: 'Relocate federal government ministries and agencies to Putrajaya — the purpose-built federal capital designed around e-government principles. Implement the Electronic Government Initiative: online permit applications, digital identity, and inter-agency data sharing.',
    durationMonths: 28,
    prerequisiteIds: ['dev_t3_msc', 'dev_t2_civil_service_reform'],
    requirements: {
      description: 'High human capital and clean institutions.',
      minHumanCapital: 50,
      maxCorruption: 45,
    },
    reward: {
      gdpBonus: 0.6,
      budgetBonus: 75,
      approvalBonus: 6,
      legacyPoints: 7,
      structuralBonus: { corruptionReduction: 8, humanCapitalBoost: 7, infrastructureBoost: 6 },
      policyUnlock: {
        description: 'Unlocks "E-Government" — digital public services reduce corruption friction',
        unlockedOptions: {},
      },
      flavourText: 'Putrajaya rises from palm oil plantation in a single decade. Its grand Islamic architecture impresses visiting dignitaries. Civil servants complain about the commute. The e-government systems work — imperfectly, gradually, then well.',
      historicalNote: 'Putrajaya became the federal administrative capital in 1999. The Electronic Government Initiative was one of the MSC\'s seven flagship applications. By 2020 Malaysia ranked 47th globally in e-government development.',
    },
  },

  {
    id: 'dev_t3_ringgit_liberalisation',
    treeId: 'developmental_state',
    tier: 3,
    category: 'external',
    icon: '💱',
    name: 'Ringgit Market Liberalisation',
    description: 'Phase out fixed exchange rate controls established after the 1997 crisis. Allow the ringgit to trade on managed float. Lift remaining capital account restrictions. Build foreign reserves to 9 months of imports as a buffer.',
    durationMonths: 16,
    prerequisiteIds: ['dev_t3_petronas', 'dev_t1_bank_negara_independence'],
    requirements: {
      description: 'Strong reserves and stable economy.',
      minGdpGrowth: 3.5,
      maxInflation: 5.0,
      minBudgetBalance: -200,
    },
    reward: {
      gdpBonus: 0.9,
      inflationModifier: -0.3,
      budgetBonus: 60,
      legacyPoints: 5,
      structuralBonus: { corruptionReduction: 3 },
      crossTreeSynergies: [
        {
          beneficiaryTree: 'liberal_open_economy',
          targetMissionId: 'lib_t3_asian_financial_hub',
          requirementReduction: 0.25,
          description: 'Ringgit liberalisation is a prerequisite for KL as a regional financial hub.',
        },
      ],
      flavourText: 'The ringgit peg, Mahathir\'s famous defiance of the IMF, is finally unwound. International investors return. The memories of 1997 fade slowly. Bank Negara\'s reserves tell the story of confidence rebuilt.',
      historicalNote: 'Malaysia unpegged the ringgit in July 2005, moving to a managed float. Governor Zeti oversaw the transition. The ringgit performed well until the 1MDB scandal triggered a new period of weakness in 2015.',
    },
  },

  // ══════════════ TIER 4 — CONSOLIDATION (7 missions) ══════════════

  {
    id: 'dev_t4_knowledge_economy',
    treeId: 'developmental_state',
    tier: 4,
    category: 'legacy',
    icon: '🎯',
    name: 'Knowledge Economy Transition',
    description: 'Raise R&D spending to 3% of GDP. Establish a National Innovation System linking universities, GLCs, and multinationals. Create the Malaysia Innovation Agency (MaGIC). Attract 50 world-class researchers annually through a Global Talent Programme.',
    durationMonths: 60,
    prerequisiteIds: ['dev_t3_msc', 'dev_t3_industrial_policy_2'],
    requirements: {
      description: 'All pillars: human capital, infrastructure, low corruption, open trade.',
      minHumanCapital: 68,
      minInfrastructure: 70,
      maxCorruption: 28,
      requiredPolicy: { openTrade: true },
      minGdpGrowth: 4.5,
      minApproval: 52,
    },
    reward: {
      gdpBonus: 2.8,
      unemploymentBonus: 1.8,
      inflationModifier: -0.4,
      budgetBonus: 180,
      approvalBonus: 10,
      legacyPoints: 25,
      populationGrowthBonuses: [{ ethnicity: 'all', bonus: 0.001 }],
      structuralBonus: { humanCapitalBoost: 20, infrastructureBoost: 12, corruptionReduction: 15, inequalityReduction: -0.05 },
      policyUnlock: {
        description: 'Unlocks "Innovation Economy" — full R&D, IP, and talent policy suite',
        unlockedOptions: { prioritySector: ['innovation'] },
      },
      crossTreeSynergies: [
        {
          beneficiaryTree: 'liberal_open_economy',
          targetMissionId: 'lib_t4_high_income_society',
          requirementReduction: 0.3,
          description: 'Knowledge economy foundation makes high-income transition achievable.',
        },
      ],
      flavourText: 'Malaysia escapes the middle-income trap — or it doesn\'t. Whether it does depends on whether the institutions were really reformed, or only rearranged.',
      historicalNote: 'Malaysia has been trapped at ~US$12,000 per capita GNI for over a decade. The 12th Malaysia Plan explicitly targets "high-income" status. Whether this arrives depends on education quality and governance transformation.',
    },
  },

  {
    id: 'dev_t4_resource_nationalism',
    treeId: 'developmental_state',
    tier: 4,
    category: 'economic',
    icon: '⛏️',
    name: 'Resource Nationalisation',
    description: 'Extend PETRONAS-style nationalisation to rare earth mining, palm oil processing, and rubber manufacturing. Create state champions in each strategic commodity sector with mandatory domestic processing requirements before export.',
    durationMonths: 30,
    prerequisiteIds: ['dev_t3_petronas', 'dev_t3_high_speed_rail'],
    mutuallyExclusiveWith: ['dev_t4_knowledge_economy'],
    requirements: {
      description: 'High commodity prices and strong approval.',
      minCommodityIndex: 115,
      minApproval: 50,
    },
    reward: {
      gdpBonus: 1.2,
      budgetBonus: 200,
      inflationModifier: 0.45,
      legacyPoints: 7,
      structuralBonus: { corruptionReduction: -8, infrastructureBoost: 7 },
      flavourText: 'The resource sectors are captured — and with them, the patronage networks that allocation rights create. GDP rises. Corruption rises faster. The question is who captures the surplus.',
    },
  },

  {
    id: 'dev_t4_5g_digital',
    treeId: 'developmental_state',
    tier: 4,
    category: 'economic',
    icon: '📡',
    name: '5G National Digital Infrastructure',
    description: 'Deploy 5G as a single national wholesale network operator (Digital Nasional Berhad) to avoid spectrum fragmentation, mandating shared infrastructure to reduce costs. Invest in AI research clusters and a quantum computing facility at UTM.',
    durationMonths: 32,
    prerequisiteIds: ['dev_t3_putrajaya', 'dev_t3_msc'],
    requirements: {
      description: 'High infrastructure, human capital, and tech-friendly policy.',
      minInfrastructure: 65,
      minHumanCapital: 60,
      requiredPolicy: { openTrade: true },
    },
    reward: {
      gdpBonus: 1.4,
      unemploymentBonus: 1.0,
      legacyPoints: 8,
      structuralBonus: { humanCapitalBoost: 12, infrastructureBoost: 14, corruptionReduction: 6 },
      policyUnlock: {
        description: 'Unlocks "Smart Nation" digital governance tier',
        unlockedOptions: { prioritySector: ['smart_nation'] },
      },
      crossTreeSynergies: [
        {
          beneficiaryTree: 'federal_pluralism',
          targetMissionId: 'fed_t3_smart_city',
          requirementReduction: 0.3,
          description: '5G national network is the backbone infrastructure for smart city deployment.',
        },
      ],
      flavourText: 'Malaysia\'s 5G network goes live. Rural Sarawak gets connectivity equivalent to central Kuala Lumpur. The digital divide begins to close — a decade after it was promised, but real nonetheless.',
      historicalNote: 'Digital Nasional Berhad was established 2021 to build Malaysia\'s 5G network as a single wholesale provider. The model was controversial, with telcos arguing it reduced competition.',
    },
  },

  {
    id: 'dev_t4_green_hydrogen',
    treeId: 'developmental_state',
    tier: 4,
    category: 'economic',
    icon: '⚡',
    name: 'Hydrogen Economy Initiative',
    description: 'Position Malaysia as a green hydrogen producer, leveraging hydroelectric capacity in Sabah and Sarawak and solar irradiance in the peninsula. Establish a Hydrogen Technology Centre, build pilot export facilities, and negotiate supply agreements with Japan and South Korea.',
    durationMonths: 36,
    prerequisiteIds: ['dev_t3_petronas', 'dev_t4_5g_digital'],
    requirements: {
      description: 'Strong energy infrastructure and open trade.',
      minInfrastructure: 68,
      requiredPolicy: { openTrade: true },
      minHumanCapital: 62,
    },
    reward: {
      gdpBonus: 1.5,
      budgetBonus: 160,
      legacyPoints: 9,
      structuralBonus: { humanCapitalBoost: 10, infrastructureBoost: 11, inequalityReduction: -0.012 },
      policyUnlock: {
        description: 'Unlocks "Green Economy" priority sector — decarbonisation investment',
        unlockedOptions: { prioritySector: ['green_economy'] },
      },
      flavourText: 'Malaysia enters the post-petroleum economy — while still collecting PETRONAS royalties. The transition creates new industrial clusters in Kuching and Kota Kinabalu, rebalancing the peninsula\'s economic dominance.',
    },
  },

  {
    id: 'dev_t4_sme_digitalisation',
    treeId: 'developmental_state',
    tier: 4,
    category: 'economic',
    icon: '🛒',
    name: 'SME Digital Transformation',
    description: 'Provide matching grants, technical assistance, and market linkages to help 100,000 SMEs adopt digital tools, e-commerce platforms, and cloud accounting. Establish the SME Corp digitalisation fund and a network of Digital Hub Centres in every state.',
    durationMonths: 24,
    prerequisiteIds: ['dev_t3_putrajaya', 'dev_t2_civil_service_reform'],
    requirements: {
      description: 'Adequate human capital and budget.',
      minHumanCapital: 52,
      minBudgetBalance: -180,
    },
    reward: {
      gdpBonus: 0.8,
      unemploymentBonus: 0.9,
      approvalBonus: 5,
      legacyPoints: 5,
      structuralBonus: { humanCapitalBoost: 7, inequalityReduction: -0.014 },
      flavourText: 'The kedai runcit becomes an e-commerce node. Rural hawkers accept e-wallet payments. The SME digitalisation programme is unglamorous, incremental, and genuinely transformative.',
    },
  },

  {
    id: 'dev_t4_labour_productivity',
    treeId: 'developmental_state',
    tier: 4,
    category: 'social',
    icon: '📈',
    name: 'National Productivity Blueprint',
    description: 'Shift Malaysia from wage competitiveness to productivity competitiveness: productivity-linked wage adjustments, automation co-investment grants, HRDF reform, and a National Productivity Corporation with teeth to measure and improve sector-by-sector output per worker.',
    durationMonths: 26,
    prerequisiteIds: ['dev_t3_industrial_policy_2', 'dev_t2_utm_uia'],
    requirements: {
      description: 'Strong human capital and growth momentum.',
      minHumanCapital: 58,
      minGdpGrowth: 3.5,
    },
    reward: {
      gdpBonus: 1.1,
      unemploymentBonus: 0.8,
      inflationModifier: -0.25,
      legacyPoints: 6,
      structuralBonus: { humanCapitalBoost: 10, corruptionReduction: 4, inequalityReduction: -0.018 },
      flavourText: 'Wages begin to rise without triggering inflation — the signature of genuine productivity growth. Factory managers who relied on cheap labour are forced to invest in machines. Some close; more innovate.',
      historicalNote: 'Malaysia\'s labour productivity growth averaged 3.5% annually 2000-2020. But the economy\'s dependency on low-cost migrant labour — 2+ million workers — suppressed the productivity imperative in many sectors.',
    },
  },

  // ══════════════ TIER 5 — ENDGAME (6 missions) ══════════════

  {
    id: 'dev_t5_high_income_transition',
    treeId: 'developmental_state',
    tier: 5,
    category: 'legacy',
    icon: '🏆',
    name: 'High-Income Nation Achievement',
    description: 'Cross the World Bank high-income threshold of US$13,205 GNI per capita. Complete the institutional transition: a service economy based on quality rather than cost, innovation-driven growth, and world-class social infrastructure ensuring the gains are broadly shared.',
    durationMonths: 48,
    prerequisiteIds: ['dev_t4_knowledge_economy', 'dev_t4_labour_productivity'],
    requirements: {
      description: 'All fundamental conditions for high-income status.',
      minGdpGrowth: 5.0,
      minHumanCapital: 72,
      maxCorruption: 25,
      minInfrastructure: 75,
      minApproval: 55,
    },
    reward: {
      gdpBonus: 3.2,
      unemploymentBonus: 2.2,
      inflationModifier: -0.5,
      budgetBonus: 240,
      approvalBonus: 14,
      legacyPoints: 35,
      populationGrowthBonuses: [{ ethnicity: 'all', bonus: 0.0014 }],
      structuralBonus: { humanCapitalBoost: 22, infrastructureBoost: 15, corruptionReduction: 18, inequalityReduction: -0.062 },
      policyUnlock: {
        description: 'Unlocks "High-Income Nation" — full suite of advanced economy policies',
        unlockedOptions: { welfareLevel: ['high_income_standards'] },
      },
      flavourText: 'Malaysia joins Singapore, South Korea, and Taiwan in the club of East Asian miracles. The textbooks write themselves. Whether it sustains it depends on the institutions — and they are always the variable.',
    },
  },

  {
    id: 'dev_t5_financial_crisis_response',
    treeId: 'developmental_state',
    tier: 5,
    category: 'crisis',
    icon: '📉',
    name: '1997 Asian Financial Crisis Response',
    description: 'The Asian Financial Crisis triggers capital flight, currency collapse, and a wave of corporate insolvencies. Choose: accept IMF conditionality, or impose unilateral capital controls and a ringgit peg. Both paths are painful. Both carry long-term consequences.',
    durationMonths: 18,
    prerequisiteIds: ['dev_t3_msc'],
    requirements: {
      description: 'Triggered by GDP collapse and currency crisis conditions.',
      crisisTrigger: { gdpBelow: -3.0, unemploymentAbove: 8.0 },
    },
    reward: {
      gdpBonus: 1.2,
      budgetBonus: -200,
      inflationModifier: -0.8,
      approvalBonus: 5,
      legacyPoints: 8,
      structuralBonus: { corruptionReduction: -3, humanCapitalBoost: 3 },
      policyUnlock: {
        description: 'Unlocks "Capital Control Emergency Powers"',
        unlockedOptions: { spendingLevel: ['capital_controls'] },
      },
      flavourText: 'Malaysia defies IMF orthodoxy and pegs the ringgit at 3.80. The economy stabilises faster than neighbours under IMF programmes. But the political consequences — Anwar Ibrahim\'s dismissal and imprisonment — will dominate the next two decades.',
      historicalNote: 'Malaysia\'s 1998 capital controls, imposed against IMF advice, became a case study. GDP contracted 7.4% in 1998, rebounded 6.1% in 1999. Paul Krugman\'s cautious endorsement triggered fierce academic debate.',
    },
  },

  {
    id: 'dev_t5_regional_hub',
    treeId: 'developmental_state',
    tier: 5,
    category: 'external',
    icon: '🌏',
    name: 'ASEAN Economic Hub',
    description: 'Cement Malaysia\'s position as the ASEAN region\'s premier development state: regional headquarters for multinationals, a talent magnet for Southeast Asia\'s professionals, and the institutional model for neighbouring developing economies.',
    durationMonths: 40,
    prerequisiteIds: ['dev_t5_high_income_transition'],
    requirements: {
      description: 'High-income status achieved and strong regional engagement.',
      minGdpGrowth: 4.5,
      minHumanCapital: 75,
      maxCorruption: 22,
      requiredPolicy: { openTrade: true },
    },
    reward: {
      gdpBonus: 2.0,
      unemploymentBonus: 1.5,
      budgetBonus: 200,
      approvalBonus: 12,
      legacyPoints: 25,
      populationGrowthBonuses: [{ ethnicity: 'all', bonus: 0.0012 }],
      structuralBonus: { humanCapitalBoost: 16, infrastructureBoost: 12, corruptionReduction: 14 },
      flavourText: 'Kuala Lumpur competes with Singapore for regional headquarters. Malaysian engineers are headhunted across ASEAN. The developmental state model — disciplined, capable, legitimate — has proven itself over fifty years.',
    },
  },

  {
    id: 'dev_t5_green_new_deal',
    treeId: 'developmental_state',
    tier: 5,
    category: 'economic',
    icon: '🌱',
    name: 'Green New Deal',
    description: 'A comprehensive decarbonisation programme: carbon pricing, mandatory ESG reporting for all listed companies, green sukuk to fund renewable energy, and a Just Transition Fund to retrain workers in fossil-fuel sectors.',
    durationMonths: 44,
    prerequisiteIds: ['dev_t4_hydrogen', 'dev_t4_knowledge_economy'],
    requirements: {
      description: 'Strong institutions and green economy foundation.',
      minHumanCapital: 68,
      minInfrastructure: 72,
      maxCorruption: 28,
      requiredPolicy: { openTrade: true },
    },
    reward: {
      gdpBonus: 1.4,
      inflationModifier: -0.5,
      budgetBonus: 180,
      approvalBonus: 10,
      legacyPoints: 20,
      structuralBonus: { humanCapitalBoost: 14, infrastructureBoost: 10, inequalityReduction: -0.038, corruptionReduction: 9 },
      flavourText: 'Malaysia becomes the first ASEAN country to meet its Paris Agreement targets ahead of schedule. PETRONAS transitions from oil major to energy company. The economy that was built on fossil fuels reinvents itself around clean energy.',
    },
  },

  {
    id: 'dev_t5_bumiputera_technocracy',
    treeId: 'developmental_state',
    tier: 5,
    category: 'institutional',
    icon: '⚙️',
    name: 'Bumiputera Technocratic Class',
    description: 'Complete the creation of a Bumiputera professional and technocratic class that can staff the developmental state on merit: engineers at PETRONAS, economists at EPU, technologists at SIRIM — the human capital foundation for a self-sustaining developmental state.',
    durationMonths: 36,
    prerequisiteIds: ['dev_t4_labour_productivity', 'dev_t3_putrajaya'],
    requirements: {
      description: 'High human capital and low corruption.',
      minHumanCapital: 70,
      maxCorruption: 30,
      minGdpGrowth: 4.0,
    },
    reward: {
      gdpBonus: 1.0,
      unemploymentBonus: 1.1,
      legacyPoints: 18,
      populationGrowthBonuses: [{ ethnicity: 'Malay', bonus: 0.0009 }, { ethnicity: 'all', bonus: 0.0005 }],
      structuralBonus: { humanCapitalBoost: 18, corruptionReduction: 12, inequalityReduction: -0.026 },
      crossTreeSynergies: [
        {
          beneficiaryTree: 'bumiputera_agenda',
          targetMissionId: 'bumi_t5_new_bumi_policy',
          requirementReduction: 0.2,
          description: 'Established technocratic class makes needs-based reform technically feasible.',
        },
      ],
      flavourText: 'The Malaysia Plan writes itself because the people who need to implement it also designed it. A generation of Bumiputera technocrats who are both professionally excellent and politically committed to the public good. It is a remarkable achievement.',
    },
  },
];

export { DEVELOPMENTAL_STATE_MISSIONS };
