

import { Mission } from './utils/missionTrees';

const BUMIPUTERA_MISSIONS: Mission[] = [
  // ══════════════ TIER 1 — FOUNDATION (7 missions) ══════════════

  {
    id: 'bumi_t1_land_reform',
    treeId: 'bumiputera_agenda',
    tier: 1,
    category: 'social',
    icon: '🌾',
    name: 'Land Reform Act',
    description: 'Redistribute undeveloped alienated land to Malay smallholders through the Land (Group Settlement Areas) Act. Establish a Land Bank to consolidate fragmented holdings and issue formal title deeds to previously informal occupants.',
    flavourQuote: '"Land is the foundation of our dignity." — Tun Abdul Razak',
    durationMonths: 14,
    prerequisiteIds: [],
    requirements: {
      description: 'Agriculture as priority sector with stable governance.',
      requiredPolicy: { prioritySector: 'agriculture' },
      minApproval: 38,
    },
    reward: {
      gdpBonus: 0.35,
      budgetBonus: 25,
      approvalBonus: 4,
      legacyPoints: 3,
      populationGrowthBonuses: [{ ethnicity: 'Malay', bonus: 0.0008 }],
      structuralBonus: { inequalityReduction: -0.012 },
      crossTreeSynergies: [
        {
          beneficiaryTree: 'socialist_welfare',
          targetMissionId: 'soc_t1_land_nationalisation',
          requirementReduction: 0.15,
          description: 'Land reform precedent makes plantation nationalisation politically viable.',
        },
        {
          beneficiaryTree: 'export_tiger',
          targetMissionId: 'tiger_t2_palm_oil',
          requirementReduction: 0.1,
          description: 'Formal land title enables commercial agricultural investment.',
        },
      ],
      flavourText: 'Thousands of Malay families receive title deeds. Rural electorate loyalty surges, but land titling without credit access leaves many unable to capitalise on their new assets.',
      historicalNote: 'The Group Settlement Areas Act (1960) and FELDA schemes redistributed over 900,000 hectares to Malay smallholders between 1956 and 1990.',
    },
  },

  {
    id: 'bumi_t1_rural_credit',
    treeId: 'bumiputera_agenda',
    tier: 1,
    category: 'economic',
    icon: '🏦',
    name: 'Rural Credit Scheme',
    description: 'Establish Bank Pertanian Malaysia and MARA-backed micro-loan schemes for Bumiputera entrepreneurs in agriculture, cottage industries, and petty trade. Set up credit cooperatives in each district and train 500 rural credit officers.',
    durationMonths: 10,
    prerequisiteIds: [],
    requirements: {
      description: 'Balanced or expansionary spending with moderate approval.',
      requiredPolicy: { spendingLevel: 'balanced' },
      minApproval: 33,
    },
    reward: {
      unemploymentBonus: 0.45,
      approvalBonus: 3,
      legacyPoints: 2,
      populationGrowthBonuses: [{ ethnicity: 'Malay', bonus: 0.0005 }],
      structuralBonus: { humanCapitalBoost: 3, corruptionReduction: -1 },
      flavourText: 'The rural credit scheme creates a new class of Bumiputera small business owners — and simultaneously introduces the patronage economy of politically-connected loan disbursement.',
      historicalNote: 'MARA and Bank Bumiputera provided rural credit from 1966 onward. By the 1980s, non-performing loan rates revealed the dark side of politicised credit allocation.',
    },
  },

  {
    id: 'bumi_t1_amanah',
    treeId: 'bumiputera_agenda',
    tier: 1,
    category: 'economic',
    icon: '📈',
    name: 'Amanah Investment Trust',
    description: 'Create a state investment trust on the ASN/ASB model, funnelling dividend-bearing corporate equity to Bumiputera beneficiaries. Appoint a professional investment board insulated from day-to-day political interference.',
    durationMonths: 20,
    prerequisiteIds: [],
    requirements: {
      description: 'Government budget within manageable deficit.',
      minBudgetBalance: -300,
    },
    reward: {
      gdpBonus: 0.25,
      budgetBonus: 45,
      legacyPoints: 4,
      structuralBonus: { inequalityReduction: -0.018, corruptionReduction: 1 },
      policyUnlock: {
        description: 'Unlocks "Unit Trust Promotion" welfare option',
        unlockedOptions: { welfareLevel: ['unit_trust'] },
      },
      flavourText: 'Millions of Malays receive dividend-bearing trust units. Amanah Saham becomes a household name — and the annual dividend announcement becomes a political event unto itself.',
      historicalNote: 'ASN launched 1981, ASB 1990. By 2020, ASB had over 10 million accountholders with RM90 billion under management, providing a near-risk-free savings vehicle for ordinary Malays.',
    },
  },

  {
    id: 'bumi_t1_mara_education',
    treeId: 'bumiputera_agenda',
    tier: 1,
    category: 'social',
    icon: '🎓',
    name: 'MARA Scholarship Programme',
    description: 'Fund overseas university scholarships for Bumiputera students in medicine, engineering, law, and commerce. Establish MRSM residential schools to identify and fast-track talented rural Malay students from Form 1.',
    durationMonths: 12,
    prerequisiteIds: [],
    requirements: {
      description: 'Adequate budget and moderate approval.',
      minBudgetBalance: -200,
      minApproval: 35,
    },
    reward: {
      structuralBonus: { humanCapitalBoost: 7 },
      unemploymentBonus: 0.3,
      legacyPoints: 3,
      populationGrowthBonuses: [{ ethnicity: 'Malay', bonus: 0.0004 }],
      flavourText: 'A generation of Bumiputera doctors, engineers, and lawyers returns from Britain and Australia. The demographic of the professional class begins its long transformation.',
      historicalNote: 'MARA sent thousands of Malay students abroad annually from the late 1960s. Many formed the technocratic backbone of Mahathir-era industrialisation and the Reformasi opposition alike.',
    },
  },

  {
    id: 'bumi_t1_bahasa_policy',
    treeId: 'bumiputera_agenda',
    tier: 1,
    category: 'social',
    icon: '📖',
    name: 'National Language Consolidation',
    description: 'Systematically expand Bahasa Malaysia as the medium of instruction across government, courts, and secondary education. Establish Dewan Bahasa dan Pustaka to develop technical and academic vocabulary. Fund Malay literature and cultural production.',
    durationMonths: 16,
    prerequisiteIds: [],
    requirements: {
      description: 'Centralist governance orientation.',
      minApproval: 36,
    },
    reward: {
      approvalBonus: 5,
      legacyPoints: 3,
      structuralBonus: { humanCapitalBoost: 4, corruptionReduction: -1 },
      populationGrowthBonuses: [{ ethnicity: 'Malay', bonus: 0.0005 }],
      crossTreeSynergies: [
        {
          beneficiaryTree: 'federal_pluralism',
          targetMissionId: 'fed_t2_language_rights',
          requirementReduction: -0.1,
          description: 'Aggressive language policy increases the political difficulty of multilingual education reform.',
        },
      ],
      flavourText: 'Bahasa Malaysia fills courtrooms, classrooms, and newspapers. National identity crystallises — but the forced transition creates friction in Chinese and Indian communities that will outlast any single election.',
      historicalNote: 'The National Language Act 1967 made Bahasa Malaysia the sole official language. English-medium universities were abolished by 1983 under the Universities and University Colleges Act.',
    },
  },

  {
    id: 'bumi_t1_felda_pioneer',
    treeId: 'bumiputera_agenda',
    tier: 1,
    category: 'social',
    icon: '🌴',
    name: 'FELDA Pioneer Schemes',
    description: 'Launch the first wave of Federal Land Development Authority pioneer settlements — clearing secondary jungle, laying access roads, and resettling Malay families from congested kampungs into organised rubber and oil palm schemes.',
    durationMonths: 18,
    prerequisiteIds: ['bumi_t1_land_reform'],
    requirements: {
      description: 'Agriculture priority and adequate budget.',
      requiredPolicy: { prioritySector: 'agriculture' },
      minBudgetBalance: -250,
    },
    reward: {
      gdpBonus: 0.45,
      unemploymentBonus: 0.55,
      legacyPoints: 4,
      populationGrowthBonuses: [{ ethnicity: 'Malay', bonus: 0.001 }, { ethnicity: 'Bumiputera Sabah (Non-Muslim)', bonus: 0.0003 }, { ethnicity: 'Bumiputera Sarawak (Non-Muslim)', bonus: 0.0003 }, { ethnicity: 'Orang Asli', bonus: 0.0003 }, { ethnicity: 'Others', bonus: 0.0003 }],
      structuralBonus: { infrastructureBoost: 5, inequalityReduction: -0.014 },
      crossTreeSynergies: [
        {
          beneficiaryTree: 'export_tiger',
          targetMissionId: 'tiger_t2_palm_oil',
          requirementReduction: 0.2,
          description: 'FELDA infrastructure provides the settled population base for palm oil industrialisation.',
        },
      ],
      flavourText: 'Jungle clearings become bustling FELDA towns. Families who owned nothing now have a smallholding, a house, and a cooperative store. Whether they can repay their development loans is another matter.',
      historicalNote: 'FELDA resettled over 112,000 families across 850,000 hectares by 1990. The schemes were the largest planned resettlement programme in the non-communist developing world.',
    },
  },

  {
    id: 'bumi_t1_orang_asli',
    treeId: 'bumiputera_agenda',
    tier: 1,
    category: 'social',
    icon: '🏕️',
    name: 'Orang Asli Integration Programme',
    description: 'Extend Bumiputera policy to the Orang Asli — peninsular Malaysia\'s original indigenous peoples. Provide primary schools, health clinics, and land registration in Orang Asli customary territories, ending centuries of administrative neglect.',
    durationMonths: 14,
    prerequisiteIds: [],
    requirements: {
      description: 'Genuine welfare commitment.',
      requiredPolicy: { welfareLevel: 'moderate' },
    },
    reward: {
      approvalBonus: 3,
      legacyPoints: 3,
      populationGrowthBonuses: [{ ethnicity: 'Bumiputera Sabah (Non-Muslim)', bonus: 0.0012 }, { ethnicity: 'Bumiputera Sarawak (Non-Muslim)', bonus: 0.0012 }, { ethnicity: 'Orang Asli', bonus: 0.0012 }, { ethnicity: 'Others', bonus: 0.0012 }],
      structuralBonus: { humanCapitalBoost: 4, inequalityReduction: -0.009 },
      crossTreeSynergies: [
        {
          beneficiaryTree: 'socialist_welfare',
          targetMissionId: 'soc_t3_rainforest_protection',
          requirementReduction: 0.2,
          description: 'Orang Asli land registration creates the legal framework for customary territorial rights.',
        },
      ],
      flavourText: 'Orang Asli villages receive teachers and doctors for the first time. But the integration programme comes with its own paternalism — converting animist communities to Islam is an unspoken expectation.',
      historicalNote: 'The Jabatan Hal Ehwal Orang Asli (JHEOA) administered Orang Asli affairs but was long criticised for assimilationist rather than rights-based approaches. Land rights remain legally precarious.',
    },
  },

  // ══════════════ TIER 2 — ECONOMIC RESTRUCTURING (8 missions) ══════════════

  {
    id: 'bumi_t2_nep',
    treeId: 'bumiputera_agenda',
    tier: 2,
    category: 'institutional',
    icon: '⚖️',
    name: 'New Economic Policy',
    description: 'Launch a comprehensive two-pronged affirmative action strategy: eradicate poverty irrespective of race, and restructure society to eliminate the identification of economic function with ethnicity. Set a 30% Bumiputera corporate equity target and poverty line at 16.7% within 20 years.',
    flavourQuote: '"The NEP is not against any community. It is for all Malaysians." — Tun Abdul Razak',
    durationMonths: 30,
    prerequisiteIds: ['bumi_t1_land_reform', 'bumi_t1_amanah'],
    requirements: {
      description: 'GDP growth above 3% and corruption below 55.',
      minGdpGrowth: 3.0,
      maxCorruption: 55,
      minApproval: 44,
    },
    reward: {
      gdpBonus: 0.55,
      unemploymentBonus: 0.75,
      approvalBonus: 7,
      legacyPoints: 8,
      populationGrowthBonuses: [{ ethnicity: 'Malay', bonus: 0.001 }, { ethnicity: 'Bumiputera Sabah (Non-Muslim)', bonus: 0.0002 }, { ethnicity: 'Bumiputera Sarawak (Non-Muslim)', bonus: 0.0002 }, { ethnicity: 'Orang Asli', bonus: 0.0002 }, { ethnicity: 'Others', bonus: 0.0002 }],
      structuralBonus: { humanCapitalBoost: 5, inequalityReduction: -0.022, corruptionReduction: -2 },
      crossTreeSynergies: [
        {
          beneficiaryTree: 'developmental_state',
          targetMissionId: 'dev_t2_technocrat_corps',
          requirementReduction: 0.15,
          description: 'NEP creates institutional demand for a professional Bumiputera civil service.',
        },
      ],
      flavourText: 'The NEP reshapes the landscape of Malaysian capitalism. Bumiputera poverty falls dramatically. But the 30% equity target creates a new political economy of licences, quotas, and Ali-Baba partnerships.',
      historicalNote: 'The NEP (1971–1990) reduced Bumiputera poverty from 65% to 17%. Malay corporate equity rose from 2.4% to ~20%. The 30% target was never fully met and remained contentious for decades.',
    },
  },

  {
    id: 'bumi_t2_felda_expansion',
    treeId: 'bumiputera_agenda',
    tier: 2,
    category: 'social',
    icon: '🌿',
    name: 'FELDA Mass Expansion',
    description: 'Dramatically scale FELDA operations: open 300,000 new hectares of jungle land, build the FELDA town model with schools, mosques, and cooperative stores, and introduce mechanisation to improve yields and reduce drudgery.',
    durationMonths: 24,
    prerequisiteIds: ['bumi_t1_felda_pioneer'],
    requirements: {
      description: 'Agriculture priority with expansionary spending.',
      requiredPolicy: { prioritySector: 'agriculture', spendingLevel: 'expansionary' },
      minBudgetBalance: -400,
    },
    reward: {
      gdpBonus: 0.6,
      unemploymentBonus: 0.9,
      budgetBonus: -60,
      legacyPoints: 5,
      populationGrowthBonuses: [{ ethnicity: 'Malay', bonus: 0.0009 }, { ethnicity: 'Bumiputera Sabah (Non-Muslim)', bonus: 0.0003 }, { ethnicity: 'Bumiputera Sarawak (Non-Muslim)', bonus: 0.0003 }, { ethnicity: 'Orang Asli', bonus: 0.0003 }, { ethnicity: 'Others', bonus: 0.0003 }],
      structuralBonus: { inequalityReduction: -0.02, infrastructureBoost: 7 },
      crossTreeSynergies: [
        {
          beneficiaryTree: 'export_tiger',
          targetMissionId: 'tiger_t2_palm_oil',
          requirementReduction: 0.25,
          description: 'Mass FELDA expansion provides the land, population, and institutional base for palm oil revolution.',
        },
      ],
      flavourText: 'Over 100,000 families resettle in jungle clearings that become thriving FELDA towns. Palm oil revenues fund the next generation of development. But the development loans compound quietly.',
      historicalNote: 'FELDA Global Ventures listed on Bursa Malaysia in 2012 as the world\'s largest IPO that year. The subsequent collapse in share price destroyed the savings of hundreds of thousands of FELDA settlers.',
    },
  },

  {
    id: 'bumi_t2_heavy_industry',
    treeId: 'bumiputera_agenda',
    tier: 2,
    category: 'economic',
    icon: '🏭',
    name: 'Heavy Industry Initiative',
    description: 'State-directed investment in HICOM: steel (Perwaja), cement, a national automobile (Proton), and a national motorcycle (Modenas). Use technology transfer agreements with Japanese and South Korean partners to build Bumiputera engineering capacity.',
    durationMonths: 36,
    prerequisiteIds: ['bumi_t1_rural_credit', 'bumi_t2_nep'],
    branch: 'ethnic_capitalism',
    mutuallyExclusiveWith: ['bumi_t2_cooperative_economy'],
    requirements: {
      description: 'Industry priority with expansionary spending and adequate infrastructure.',
      requiredPolicy: { prioritySector: 'industry', spendingLevel: 'expansionary' },
      minInfrastructure: 33,
    },
    reward: {
      gdpBonus: 1.1,
      unemploymentBonus: 0.9,
      inflationModifier: 0.35,
      budgetBonus: -90,
      legacyPoints: 6,
      structuralBonus: { infrastructureBoost: 9, humanCapitalBoost: 5, corruptionReduction: -4 },
      policyUnlock: {
        description: 'Unlocks "National Champion" industrial policy',
        unlockedOptions: { prioritySector: ['national_champion'] },
      },
      crossTreeSynergies: [
        {
          beneficiaryTree: 'developmental_state',
          targetMissionId: 'dev_t3_petronas',
          requirementReduction: 0.1,
          description: 'Industrial state capacity makes petroleum corporation management more viable.',
        },
      ],
      flavourText: 'Proton rolls off its first assembly line to national fanfare. Perwaja haemorrhages money in the shadows. The question is whether infant industries can survive adolescence.',
      historicalNote: 'Proton launched 1985, achieving 75% market share before competition eroded it to below 20%. Perwaja steel lost over RM10 billion before privatisation. The lesson of East Asian industrial policy without East Asian discipline.',
    },
  },

  {
    id: 'bumi_t2_cooperative_economy',
    treeId: 'bumiputera_agenda',
    tier: 2,
    category: 'economic',
    icon: '🤝',
    name: 'Bumiputera Cooperative Network',
    description: 'Build a network of Bumiputera producer and consumer cooperatives — less capital-intensive than state corporations, more broadly distributed, and with democratic governance structures that reduce the risk of elite capture.',
    durationMonths: 22,
    prerequisiteIds: ['bumi_t1_rural_credit', 'bumi_t2_nep'],
    branch: 'distributive',
    mutuallyExclusiveWith: ['bumi_t2_heavy_industry'],
    requirements: {
      description: 'Moderate welfare and adequate human capital.',
      requiredPolicy: { welfareLevel: 'moderate' },
      minHumanCapital: 28,
    },
    reward: {
      gdpBonus: 0.6,
      unemploymentBonus: 0.9,
      legacyPoints: 4,
      populationGrowthBonuses: [{ ethnicity: 'Malay', bonus: 0.0007 }],
      structuralBonus: { humanCapitalBoost: 6, inequalityReduction: -0.025, corruptionReduction: 3 },
      crossTreeSynergies: [
        {
          beneficiaryTree: 'socialist_welfare',
          targetMissionId: 'soc_t2_cooperatives',
          requirementReduction: 0.25,
          description: 'Bumiputera cooperative model provides a tested template for multiracial cooperative expansion.',
        },
      ],
      flavourText: 'A quieter path. Cooperative networks spread Bumiputera wealth more evenly, with less spectacular failure — and less spectacular success. The middle road, trodden by ordinary people.',
    },
  },

  {
    id: 'bumi_t2_education_quota',
    treeId: 'bumiputera_agenda',
    tier: 2,
    category: 'social',
    icon: '🏫',
    name: 'University Quota System',
    description: 'Mandate Bumiputera enrolment floors at all public universities — 55% initially. Establish the Maktab Rendah Sains MARA (MRSM) residential school network to identify talented rural students. Fund the University Teknologi MARA (UiTM) exclusively for Bumiputera students.',
    durationMonths: 20,
    prerequisiteIds: ['bumi_t1_mara_education'],
    requirements: {
      description: 'Adequate approval and budget.',
      minApproval: 38,
      minBudgetBalance: -220,
    },
    reward: {
      unemploymentBonus: 0.55,
      legacyPoints: 5,
      populationGrowthBonuses: [{ ethnicity: 'Malay', bonus: 0.0006 }],
      structuralBonus: { humanCapitalBoost: 10, inequalityReduction: -0.012, corruptionReduction: -1 },
      flavourText: 'A generation of Bumiputera graduates enters the professional class. Non-Bumiputera students migrate to private colleges or emigrate — the beginning of a brain drain that will not end.',
      historicalNote: 'University quotas introduced 1971 reduced non-Malay public university enrolment from ~70% to ~35% by 1980. Tunku Abdul Rahman University College was founded by MCA partly in response.',
    },
  },

  {
    id: 'bumi_t2_corporate_equity',
    treeId: 'bumiputera_agenda',
    tier: 2,
    category: 'economic',
    icon: '📊',
    name: 'Corporate Equity Drive',
    description: 'Use the Capital Issues Committee to require Bumiputera equity participation in all major new public listings. Establish PNB (Permodalan Nasional Bhd) as a holding company for state-acquired corporate stakes, gradually transferring them to individual Bumiputera investors.',
    durationMonths: 18,
    prerequisiteIds: ['bumi_t2_nep', 'bumi_t1_amanah'],
    requirements: {
      description: 'Stock market functioning and low corruption.',
      maxCorruption: 55,
      minBudgetBalance: -250,
    },
    reward: {
      gdpBonus: 0.55,
      budgetBonus: 80,
      legacyPoints: 5,
      structuralBonus: { humanCapitalBoost: 4, corruptionReduction: -2 },
      policyUnlock: {
        description: 'Unlocks "Bumiputera Equity Mandate" for private investment',
        unlockedOptions: {},
      },
      crossTreeSynergies: [
        {
          beneficiaryTree: 'liberal_open_economy',
          targetMissionId: 'lib_t1_stock_exchange',
          requirementReduction: -0.15,
          description: 'Equity mandates create friction with open capital markets.',
        },
      ],
      flavourText: 'PNB accumulates stakes across the economy. On paper, Bumiputera equity approaches 20%. But much of it is concentrated among political elites, not the smallholders FELDA was meant to serve.',
      historicalNote: 'PNB was established 1978 and managed RM300 billion by 2020. The Bumiputera equity figure remained contested — official figures showed ~17-23% depending on methodology.',
    },
  },

  {
    id: 'bumi_t2_islamic_finance_seed',
    treeId: 'bumiputera_agenda',
    tier: 2,
    category: 'economic',
    icon: '☪️',
    name: 'Islamic Finance Foundation',
    description: 'Establish Bank Islam Malaysia Berhad as the first fully Shariah-compliant commercial bank. Create the National Shariah Advisory Council to standardise Islamic banking principles. Build a framework for zakat redistribution tied to government development priorities.',
    durationMonths: 15,
    prerequisiteIds: ['bumi_t1_amanah', 'bumi_t1_bahasa_policy'],
    requirements: {
      description: 'Islamist-leaning governance.',
      minApproval: 40,
    },
    reward: {
      budgetBonus: 55,
      legacyPoints: 4,
      structuralBonus: { humanCapitalBoost: 3, corruptionReduction: 2 },
      policyUnlock: {
        description: 'Unlocks "Islamic Finance Window" in development spending',
        unlockedOptions: { spendingLevel: ['islamic_banking'] },
      },
      crossTreeSynergies: [
        {
          beneficiaryTree: 'export_tiger',
          targetMissionId: 'tiger_t3_fintech',
          requirementReduction: 0.2,
          description: 'Islamic finance foundation gives Malaysia a unique global niche.',
        },
      ],
      flavourText: 'Bank Islam opens its doors. Depositors who refused interest-based banking for religious reasons finally have an option. A small act that will have outsized consequences for Malaysian finance.',
      historicalNote: 'Bank Islam Malaysia Berhad was established in 1983, the first Islamic bank in Southeast Asia. Malaysia went on to become the world\'s largest sukuk market.',
    },
  },

  {
    id: 'bumi_t2_malay_chamber',
    treeId: 'bumiputera_agenda',
    tier: 2,
    category: 'institutional',
    icon: '🏛️',
    name: 'Dewan Perniagaan Melayu',
    description: 'Establish the National Malay Chamber of Commerce (DPIM) as a voice for Bumiputera business interests. Create a Bumiputera Business Development Centre in each state, a mentorship programme linking established Chinese businesses with Bumiputera partners, and an annual Bumiputera Economic Congress.',
    durationMonths: 12,
    prerequisiteIds: ['bumi_t1_rural_credit', 'bumi_t1_mara_education'],
    requirements: {
      description: 'Stable political environment.',
      minApproval: 35,
      minMonthsInPower: 12,
    },
    reward: {
      unemploymentBonus: 0.3,
      approvalBonus: 3,
      legacyPoints: 3,
      structuralBonus: { humanCapitalBoost: 4, corruptionReduction: 1 },
      crossTreeSynergies: [
        {
          beneficiaryTree: 'federal_pluralism',
          targetMissionId: 'fed_t2_interethnic_accord',
          requirementReduction: 0.1,
          description: 'A functioning Malay business chamber can be a counterpart to Chinese business organisations in ethnic economic negotiations.',
        },
      ],
      flavourText: 'The Chamber becomes the institutional voice of the Malay business class. Its annual congress sets the agenda for the following year\'s Bumiputera policy — and the guest list tells you everything about political power.',
    },
  },

  // ══════════════ TIER 3 — FORK: ETHNIC CAPITALISM vs INTEGRATIONIST (8 missions) ══════════════

  {
    id: 'bumi_t3_proton_national_car',
    treeId: 'bumiputera_agenda',
    tier: 3,
    category: 'economic',
    icon: '🚗',
    name: 'National Automobile Programme',
    description: 'Launch Proton as a fully national automobile — not an assembly operation but a marque with its own engineering, design, and brand identity. Negotiate technology transfer with Mitsubishi. Protect the domestic market with tariffs while Proton matures.',
    flavourQuote: '"We Malays must prove we can do anything the Japanese can do." — Mahathir Mohamad',
    durationMonths: 30,
    prerequisiteIds: ['bumi_t2_heavy_industry'],
    branch: 'ethnic_capitalism',
    mutuallyExclusiveWith: ['bumi_t3_bangsa_malaysia_compact'],
    requirements: {
      description: 'Industry priority with adequate infrastructure and human capital.',
      requiredPolicy: { prioritySector: 'industry' },
      minInfrastructure: 42,
      minHumanCapital: 36,
    },
    reward: {
      gdpBonus: 1.25,
      unemploymentBonus: 1.0,
      inflationModifier: 0.4,
      legacyPoints: 7,
      structuralBonus: { humanCapitalBoost: 8, corruptionReduction: -3 },
      policyUnlock: {
        description: 'Unlocks "Automotive Industrial Policy" — tariff protection for national champion',
        unlockedOptions: { prioritySector: ['automotive_champion'] },
      },
      flavourText: 'The Proton Saga rolls off the Shan Alam line to national fanfare. Every Malaysian is expected to buy one. Mechanics learn a new vocabulary. The question of whether to want it is not asked.',
      historicalNote: 'Proton launched the Saga in 1985 at RM25,000. Initial quality was poor — the saying was it stood for "Problems Recurring Over and Over Now." Yet Proton achieved 75% market share by 1993.',
    },
  },

  {
    id: 'bumi_t3_petronas_state_oil',
    treeId: 'bumiputera_agenda',
    tier: 3,
    category: 'economic',
    icon: '🛢️',
    name: 'PETRONAS National Oil Corporation',
    description: 'Nationalise petroleum rights under PETRONAS with mandatory equity participation from foreign oil companies. Direct oil revenues to a dedicated Development Fund, insulated from day-to-day operating budget pressures. Commission the Petronas Twin Towers as a symbol of national aspiration.',
    durationMonths: 28,
    prerequisiteIds: ['bumi_t2_heavy_industry', 'bumi_t2_corporate_equity'],
    branch: 'ethnic_capitalism',
    requirements: {
      description: 'High commodity prices and manageable corruption.',
      minCommodityIndex: 108,
      maxCorruption: 55,
    },
    reward: {
      gdpBonus: 1.7,
      budgetBonus: 280,
      inflationModifier: 0.35,
      legacyPoints: 10,
      structuralBonus: { infrastructureBoost: 12, corruptionReduction: -5 },
      policyUnlock: {
        description: 'Unlocks "Petrodollar Development Stimulus" spending option',
        unlockedOptions: { spendingLevel: ['petrodollar_stimulus'] },
      },
      crossTreeSynergies: [
        {
          beneficiaryTree: 'developmental_state',
          targetMissionId: 'dev_t3_petronas',
          requirementReduction: 0.25,
          bypassIdeologyGate: true,
          description: 'PETRONAS establishment creates the institutional base for the developmental state petroleum strategy.',
        },
        {
          beneficiaryTree: 'export_tiger',
          targetMissionId: 'tiger_t3_tiger_economy',
          requirementReduction: 0.1,
          description: 'Oil revenues provide the counter-cyclical buffer for tiger economy ambitions.',
        },
      ],
      flavourText: 'PETRONAS changes everything. The Twin Towers rise over Kuala Lumpur, visible for miles. Oil money flows into roads, universities, and state enterprises. It also flows into places not captured by the national accounts.',
      historicalNote: 'PETRONAS established 1974. By 2019 it contributed ~24% of government revenue. The Twin Towers were completed 1998 at a cost of RM6 billion, briefly the world\'s tallest buildings.',
    },
  },

  {
    id: 'bumi_t3_wawasan_2020',
    treeId: 'bumiputera_agenda',
    tier: 3,
    category: 'legacy',
    icon: '🌅',
    name: 'Vision 2020',
    description: 'Chart the grand national vision: a fully developed, united Malaysian nation by 2020 — in our own mould. Nine strategic challenges spanning economics, social justice, political stability, and cultural identity. Make Vision 2020 the centrepiece of every government programme.',
    flavourQuote: '"By the year 2020, Malaysia can be a fully developed country — in our own mould." — Mahathir Mohamad, 1991',
    durationMonths: 42,
    prerequisiteIds: ['bumi_t2_nep', 'bumi_t3_proton_national_car'],
    requirements: {
      description: 'Sustained GDP above 5%, low unemployment, strong approval.',
      minGdpGrowth: 5.0,
      maxUnemployment: 7.0,
      minApproval: 54,
      maxCorruption: 48,
    },
    reward: {
      gdpBonus: 1.7,
      unemploymentBonus: 1.1,
      inflationModifier: -0.2,
      budgetBonus: 90,
      approvalBonus: 11,
      legacyPoints: 12,
      populationGrowthBonuses: [{ ethnicity: 'Malay', bonus: 0.0011 }, { ethnicity: 'all', bonus: 0.0004 }],
      structuralBonus: { humanCapitalBoost: 11, infrastructureBoost: 9, inequalityReduction: -0.028, corruptionReduction: 4 },
      policyUnlock: {
        description: 'Unlocks "Wawasan Development Fund" sovereign wealth spending tier',
        unlockedOptions: { spendingLevel: ['sovereign_fund'] },
      },
      flavourText: 'Malaysia is declared a middle-income nation. Vision 2020 galvanises technocrats and the public alike. But 2020 will arrive — and the reckoning of what was not achieved will be quieter than the declaration.',
      historicalNote: 'Vision 2020 unveiled 1991. Malaysia\'s per capita GNI reached ~US$12,000 by 2020 — high middle income but not high income by World Bank thresholds. The gap between the vision and the reality became a permanent feature of Malaysian political discourse.',
    },
  },

  {
    id: 'bumi_t3_bangsa_malaysia_compact',
    treeId: 'bumiputera_agenda',
    tier: 3,
    category: 'legacy',
    icon: '🕊️',
    name: 'Bangsa Malaysia Compact',
    description: 'Formally embrace the Bangsa Malaysia concept: a unified Malaysian national identity that transcends ethnicity while preserving Bumiputera rights. Create a National Unity Council with real authority, mandate civics education, and reform the ICERD to include Malaysia in key racial discrimination covenants.',
    durationMonths: 36,
    prerequisiteIds: ['bumi_t2_cooperative_economy', 'bumi_t2_education_quota'],
    branch: 'integrationist',
    mutuallyExclusiveWith: ['bumi_t3_proton_national_car'],
    requirements: {
      description: 'High approval across communities and manageable corruption.',
      minApproval: 55,
      maxCorruption: 40,
    },
    reward: {
      approvalBonus: 14,
      legacyPoints: 15,
      populationGrowthBonuses: [{ ethnicity: 'all', bonus: 0.001 }],
      structuralBonus: { inequalityReduction: -0.038, humanCapitalBoost: 9, corruptionReduction: 5 },
      crossTreeSynergies: [
        {
          beneficiaryTree: 'federal_pluralism',
          targetMissionId: 'fed_t3_true_federation',
          requirementReduction: 0.25,
          description: 'Bangsa Malaysia identity makes constitutional pluralist reform politically viable.',
        },
        {
          beneficiaryTree: 'liberal_open_economy',
          targetMissionId: 'lib_t3_meritocracy',
          requirementReduction: 0.2,
          description: 'Civic nationalism reduces political resistance to meritocracy reforms.',
        },
      ],
      flavourText: '"We are all Malaysians first." A new national consciousness struggles to be born against decades of ethnic politics. Whether it takes root depends entirely on the generation that inherits it.',
      historicalNote: 'Bangsa Malaysia was a key element of Vision 2020. Critics noted the irresolvable tension with Bumiputera special rights. The concept was de-emphasised by the Abdullah and Najib administrations, revived under Pakatan Harapan, and remains unresolved.',
    },
  },

  {
    id: 'bumi_t3_sovereign_wealth',
    treeId: 'bumiputera_agenda',
    tier: 3,
    category: 'economic',
    icon: '💰',
    name: 'National Sovereign Wealth Fund',
    description: 'Establish Khazanah Nasional as a sovereign wealth fund, investing oil, palm oil, and tin revenues for long-term national benefit. Mandate professional fund management, international benchmarking of returns, and parliamentary oversight of major investments.',
    durationMonths: 28,
    prerequisiteIds: ['bumi_t3_petronas_state_oil'],
    requirements: {
      description: 'Commodity boom conditions and near-balanced budget.',
      minCommodityIndex: 115,
      minBudgetBalance: -120,
    },
    reward: {
      gdpBonus: 0.9,
      budgetBonus: 140,
      legacyPoints: 7,
      structuralBonus: { infrastructureBoost: 11, corruptionReduction: -2 },
      crossTreeSynergies: [
        {
          beneficiaryTree: 'export_tiger',
          targetMissionId: 'tiger_t3_tiger_economy',
          requirementReduction: 0.12,
          description: 'Sovereign wealth provides counter-cyclical buffer for tiger economy ambitions.',
        },
      ],
      flavourText: 'Petrodollars are channelled into the future rather than consumed. But a fund this large attracts political attention. The line between investment management and political patronage is drawn in pencil.',
      historicalNote: 'Khazanah Nasional established 1994. By 2020 it managed RM130 billion. Contrast with 1MDB, established 2009 — which illustrates precisely the patronage risk that Khazanah was designed to avoid.',
    },
  },

  {
    id: 'bumi_t3_mahathirism',
    treeId: 'bumiputera_agenda',
    tier: 3,
    category: 'institutional',
    icon: '✊',
    name: 'Mahathirism: Asian Values',
    description: 'Articulate a coherent ideology for Bumiputera capitalism: Asian values over Western liberal democracy, state-guided markets over laissez-faire, national champions over foreign multinationals. Use this framework to justify executive authority against judicial and parliamentary constraints.',
    durationMonths: 18,
    prerequisiteIds: ['bumi_t3_wawasan_2020'],
    branch: 'ethnic_capitalism',
    requirements: {
      description: 'Strong approval and governance capacity.',
      minApproval: 56,
      maxCorruption: 50,
    },
    reward: {
      approvalBonus: 8,
      legacyPoints: 6,
      structuralBonus: { corruptionReduction: -4, humanCapitalBoost: 2 },
      policyUnlock: {
        description: 'Unlocks "Developmental Authoritarianism" governance option',
        unlockedOptions: {},
      },
      flavourText: 'Mahathirism becomes an export product. Delegations from Africa and Central Asia arrive to study the Malaysian model. The inconvenient footnotes about judicial independence are omitted from the prospectus.',
      historicalNote: 'Mahathir\'s "Look East" policy and Asian values discourse made Malaysia a reference point for developmental authoritarian governance. The 1988 judicial crisis was its darkest expression.',
    },
  },

  {
    id: 'bumi_t3_multiracial_bumi',
    treeId: 'bumiputera_agenda',
    tier: 3,
    category: 'social',
    icon: '🌈',
    name: 'Expanded Bumiputera Definition',
    description: 'Formally recognise Sabah and Sarawak\'s indigenous peoples — Kadazan-Dusun, Iban, Bidayuh, Murut and others — as full beneficiaries of Bumiputera policy on equal terms with Peninsular Malays. Create a Borneo Bumiputera Development Authority.',
    durationMonths: 16,
    prerequisiteIds: ['bumi_t2_nep', 'bumi_t1_orang_asli'],
    requirements: {
      description: 'Multiracial support and moderate approval.',
      minApproval: 42,
    },
    reward: {
      approvalBonus: 9,
      legacyPoints: 5,
      populationGrowthBonuses: [
        { ethnicity: 'Bumiputera Sabah (Non-Muslim)', bonus: 0.0015 },
        { ethnicity: 'Bumiputera Sarawak (Non-Muslim)', bonus: 0.0015 },
        { ethnicity: 'Bumiputera Sabah (Muslim)', bonus: 0.0007 },
      ],
      structuralBonus: { inequalityReduction: -0.018 },
      crossTreeSynergies: [
        {
          beneficiaryTree: 'federal_pluralism',
          targetMissionId: 'fed_t1_borneo_rights',
          requirementReduction: 0.2,
          description: 'Expanded Bumiputera definition builds political goodwill for Borneo rights restoration.',
        },
      ],
      flavourText: 'East Malaysian leaders welcome the gesture. But they also notice that "equal beneficiary" and "equal political power" are different things — and Kuala Lumpur controls the budget.',
    },
  },

  // ══════════════ TIER 4 — CONSOLIDATION (6 missions) ══════════════

  {
    id: 'bumi_t4_nem',
    treeId: 'bumiputera_agenda',
    tier: 4,
    category: 'institutional',
    icon: '🔄',
    name: 'New Economic Model',
    description: 'Redesign NEP for the post-2010 era: needs-based targeting within Bumiputera communities, performance conditionality on corporate equity support, graduation of wealthy Bumiputera from subsidies, and a 10-year roadmap to high-income nation status.',
    durationMonths: 36,
    prerequisiteIds: ['bumi_t3_wawasan_2020', 'bumi_t3_bangsa_malaysia_compact'],
    requirements: {
      description: 'Strong institutions and high approval.',
      minHumanCapital: 55,
      maxCorruption: 35,
      minApproval: 58,
      minGdpGrowth: 4.0,
    },
    reward: {
      gdpBonus: 1.3,
      unemploymentBonus: 0.9,
      approvalBonus: 8,
      legacyPoints: 16,
      populationGrowthBonuses: [{ ethnicity: 'all', bonus: 0.0008 }],
      structuralBonus: { humanCapitalBoost: 14, inequalityReduction: -0.042, corruptionReduction: 10 },
      policyUnlock: {
        description: 'Unlocks "Needs-Based Affirmative Action" welfare policy',
        unlockedOptions: { welfareLevel: ['needs_based_aa'] },
      },
      crossTreeSynergies: [
        {
          beneficiaryTree: 'liberal_open_economy',
          targetMissionId: 'lib_t3_asian_financial_hub',
          requirementReduction: 0.2,
          description: 'NEM signals institutional maturity to international investors.',
        },
        {
          beneficiaryTree: 'federal_pluralism',
          targetMissionId: 'fed_t4_national_reconciliation',
          requirementReduction: 0.3,
          description: 'Needs-based reform creates conditions for genuine national reconciliation.',
        },
      ],
      flavourText: 'The hardest reform: dismantling a system that has defined Malaysian politics for fifty years. The loudest opposition comes from those who benefit most from the status quo. The people it was supposed to serve were never fully consulted.',
      historicalNote: 'The New Economic Model (2010) under Najib proposed needs-based affirmative action but was rolled back under UMNO pressure. Renamed the Economic Transformation Programme, the reforms were largely cosmetic.',
    },
  },

  {
    id: 'bumi_t4_msc_corridor',
    treeId: 'bumiputera_agenda',
    tier: 4,
    category: 'economic',
    icon: '💻',
    name: 'MSC Malaysia Technology Corridor',
    description: 'Designate the 15km × 50km corridor from KLCC to KLIA as the Multimedia Super Corridor — Cyberjaya, Putrajaya, and the KL financial centre. Offer regulatory freedoms, world-class connectivity, and a no-censorship internet guarantee to attract global tech firms.',
    durationMonths: 38,
    prerequisiteIds: ['bumi_t3_wawasan_2020', 'bumi_t3_petronas_state_oil'],
    requirements: {
      description: 'High human capital, infrastructure, and open trade.',
      minHumanCapital: 52,
      minInfrastructure: 58,
      requiredPolicy: { openTrade: true },
    },
    reward: {
      gdpBonus: 2.0,
      unemploymentBonus: 1.3,
      budgetBonus: 105,
      approvalBonus: 9,
      legacyPoints: 10,
      structuralBonus: { humanCapitalBoost: 14, infrastructureBoost: 10, corruptionReduction: 4 },
      policyUnlock: {
        description: 'Unlocks "Digital Economy" sector option',
        unlockedOptions: { prioritySector: ['digital'] },
      },
      flavourText: 'Cyberjaya glows on the map. The MSC Bill of Guarantees — no internet censorship, world-class bandwidth — becomes a model for e-governance. Whether it is honoured long-term is a different story.',
      historicalNote: 'MSC Malaysia launched 1996. By 2020 it housed 3,000+ companies. The dotcom bust and 2008 crisis reduced ambitions. The no-censorship guarantee lasted until 2011.',
    },
  },

  {
    id: 'bumi_t4_felda_ipo',
    treeId: 'bumiputera_agenda',
    tier: 4,
    category: 'economic',
    icon: '📉',
    name: 'FELDA Global Ventures Listing',
    description: 'List FELDA Global Ventures on Bursa Malaysia, raising capital to modernise plantations and giving settlers an equity stake in the company built on their labour. Use the IPO proceeds to fund the next generation of Bumiputera development.',
    durationMonths: 20,
    prerequisiteIds: ['bumi_t2_felda_expansion', 'bumi_t2_corporate_equity'],
    requirements: {
      description: 'Functioning capital markets and buoyant commodity prices.',
      minCommodityIndex: 105,
      minBudgetBalance: -150,
    },
    reward: {
      budgetBonus: 250,
      gdpBonus: 0.6,
      legacyPoints: 5,
      populationGrowthBonuses: [{ ethnicity: 'Malay', bonus: 0.0005 }],
      structuralBonus: { corruptionReduction: -3, infrastructureBoost: 5 },
      flavourText: 'The FGV IPO is the world\'s largest of the year. Settlers receive share certificates worth tens of thousands of ringgit — on paper. The subsequent collapse in share value will be a story told at FELDA town coffee stalls for a generation.',
      historicalNote: 'FGV listed in 2012, raising RM9.9 billion. By 2018 the share price had collapsed from RM4.55 to below RM1.50, destroying settler savings. A parliamentary inquiry found governance failures.',
    },
  },

  {
    id: 'bumi_t4_giatmara',
    treeId: 'bumiputera_agenda',
    tier: 4,
    category: 'social',
    icon: '🔧',
    name: 'Vocational Skills Revolution',
    description: 'Transform GiatMARA into a world-class vocational training network, providing Bumiputera school-leavers with industry-relevant skills in electrical engineering, automotive, construction, and digital trades. Replace the stigma of "not university material" with pride in technical mastery.',
    durationMonths: 22,
    prerequisiteIds: ['bumi_t2_education_quota', 'bumi_t3_mahathirism'],
    requirements: {
      description: 'Adequate human capital investment and budget.',
      minHumanCapital: 42,
      minBudgetBalance: -200,
    },
    reward: {
      unemploymentBonus: 1.1,
      approvalBonus: 5,
      legacyPoints: 5,
      populationGrowthBonuses: [{ ethnicity: 'Malay', bonus: 0.0007 }],
      structuralBonus: { humanCapitalBoost: 9, inequalityReduction: -0.014 },
      flavourText: 'GiatMARA graduates flood the construction and manufacturing sectors. The skills mismatch that left university graduates unemployed while factories imported foreign workers begins to close.',
    },
  },

  {
    id: 'bumi_t4_perumahan_rakyat',
    treeId: 'bumiputera_agenda',
    tier: 4,
    category: 'social',
    icon: '🏘️',
    name: 'National Housing Programme',
    description: 'Mandate that 30% of all new housing developments must be low-cost units for Bumiputera occupancy. Establish Syarikat Perumahan Negara (SPNB) to build affordable housing in urban areas where Bumiputera families are being priced out by Chinese commercial developers.',
    durationMonths: 26,
    prerequisiteIds: ['bumi_t2_nep', 'bumi_t3_bangsa_malaysia_compact'],
    requirements: {
      description: 'Adequate infrastructure and expansionary spending.',
      minInfrastructure: 35,
      requiredPolicy: { spendingLevel: 'expansionary' },
    },
    reward: {
      approvalBonus: 9,
      unemploymentBonus: 0.7,
      budgetBonus: -80,
      legacyPoints: 6,
      populationGrowthBonuses: [{ ethnicity: 'Malay', bonus: 0.0009 }],
      structuralBonus: { infrastructureBoost: 8, inequalityReduction: -0.016 },
      flavourText: 'Low-cost flats multiply across the Klang Valley. Bumiputera families secure urban footholds. The quality of construction becomes a standing joke in the opposition press — but having a roof over your head is not a joke.',
    },
  },

  // ══════════════ TIER 5 — ENDGAME (6 missions) ══════════════

  {
    id: 'bumi_t5_new_bumi_policy',
    treeId: 'bumiputera_agenda',
    tier: 5,
    category: 'legacy',
    icon: '⭐',
    name: 'New Bumiputera Policy Reform',
    description: 'Complete the transformation of Bumiputera policy for the 21st century: universal poverty targeting, performance-conditioned business support, Bumiputera graduation from subsidies above RM100k annual income, and a new constitutional compact that modernises Article 153 for a globalised economy.',
    durationMonths: 48,
    prerequisiteIds: ['bumi_t4_nem', 'bumi_t4_msc_corridor'],
    requirements: {
      description: 'All conditions for transformation: institutions, income, approval.',
      minHumanCapital: 62,
      maxCorruption: 28,
      minApproval: 60,
      minGdpGrowth: 4.5,
      minLegacyPoints: 50,
    },
    reward: {
      gdpBonus: 1.5,
      unemploymentBonus: 1.0,
      approvalBonus: 10,
      legacyPoints: 25,
      populationGrowthBonuses: [{ ethnicity: 'all', bonus: 0.001 }],
      structuralBonus: { humanCapitalBoost: 16, inequalityReduction: -0.05, corruptionReduction: 14, infrastructureBoost: 8 },
      policyUnlock: {
        description: 'Unlocks "Universal Development Policy" — ethnicity-blind poverty targeting',
        unlockedOptions: { welfareLevel: ['universal_development'] },
      },
      crossTreeSynergies: [
        {
          beneficiaryTree: 'liberal_open_economy',
          targetMissionId: 'lib_t4_high_income_society',
          requirementReduction: 0.25,
          description: 'Policy modernisation signals high-income nation readiness.',
        },
        {
          beneficiaryTree: 'federal_pluralism',
          targetMissionId: 'fed_t4_national_reconciliation',
          requirementReduction: 0.3,
          description: 'Genuine reform creates the political trust for national reconciliation.',
        },
      ],
      flavourText: 'This is the destination the NEP was always supposed to be travelling toward — a Malaysia where affirmative action has fulfilled its purpose and can be graduated. Whether it arrives determines what kind of country the next century inherits.',
      historicalNote: 'Every Malaysian government since 1990 has promised to review Bumiputera policy. None has substantially reformed it. The New Bumiputera Policy remains the road not taken.',
    },
  },

  {
    id: 'bumi_t5_institutionalised_patronage',
    treeId: 'bumiputera_agenda',
    tier: 5,
    category: 'institutional',
    icon: '🎭',
    name: 'Institutionalised Patron-Client Networks',
    description: 'Formalise the political economy of Bumiputera patronage: GLCs as political instruments, business licences as political rewards, UMNO as the ultimate arbiter of Bumiputera economic opportunity. What began as affirmative action has become a system of political control.',
    durationMonths: 24,
    prerequisiteIds: ['bumi_t3_mahathirism', 'bumi_t4_felda_ipo'],
    mutuallyExclusiveWith: ['bumi_t5_new_bumi_policy'],
    requirements: {
      description: 'Strong party control but deteriorating institutions.',
      minApproval: 48,
      minMonthsInPower: 60,
    },
    reward: {
      approvalBonus: 5,
      budgetBonus: 120,
      legacyPoints: -8,
      structuralBonus: { corruptionReduction: -15, humanCapitalBoost: -3 },
      flavourText: 'The machinery is perfected. UMNO controls the economy; the economy reinforces UMNO. It is stable, efficient, and ultimately unsustainable. The question is not whether it will fall, but when.',
      historicalNote: 'The patronage system built under Mahathir and extended under Abdullah and Najib eventually triggered the Reformasi movement (1998) and the 1MDB scandal (2015). GE14 (2018) was its electoral consequence.',
    },
  },

  {
    id: 'bumi_t5_malaysia_baru',
    treeId: 'bumiputera_agenda',
    tier: 5,
    category: 'legacy',
    icon: '🌅',
    name: 'Malaysia Baharu',
    description: 'Following a seismic electoral shift, lead the transition to a new Malaysia: anti-corruption institutions with real independence, a free media, constitutional reform to balance Article 153 with minority rights, and a new social contract negotiated by all Malaysians.',
    flavourQuote: '"We want a Malaysia that belongs to all Malaysians." — Pakatan Harapan 2018 Manifesto',
    durationMonths: 36,
    prerequisiteIds: ['bumi_t4_nem', 'bumi_t3_bangsa_malaysia_compact'],
    requirements: {
      description: 'Electoral mandate for reform and clean governance record.',
      maxCorruption: 30,
      minApproval: 58,
      minLegacyPoints: 55,
    },
    reward: {
      approvalBonus: 18,
      gdpBonus: 0.8,
      legacyPoints: 30,
      populationGrowthBonuses: [{ ethnicity: 'all', bonus: 0.0012 }],
      structuralBonus: { corruptionReduction: 20, humanCapitalBoost: 12, inequalityReduction: -0.044 },
      policyUnlock: {
        description: 'Unlocks "New Malaysia Compact" — full suite of institutional reforms',
        unlockedOptions: {},
      },
      crossTreeSynergies: [
        {
          beneficiaryTree: 'federal_pluralism',
          targetMissionId: 'fed_t4_national_reconciliation',
          bypassIdeologyGate: true,
          requirementReduction: 0.35,
          description: 'Malaysia Baharu mandate creates the political space for deep constitutional reform.',
        },
      ],
      flavourText: 'For the first time since 1957, a different coalition governs Malaysia. The institutions groan under the weight of change. Some things are easier than expected. Many things are harder.',
      historicalNote: 'Pakatan Harapan\'s 2018 election victory — the first change of federal government in 61 years — ended with the Sheraton Move political crisis in 2020, illustrating the fragility of reform coalitions.',
    },
  },

  {
    id: 'bumi_t5_kleptocracy_crisis',
    treeId: 'bumiputera_agenda',
    tier: 5,
    category: 'crisis',
    icon: '💥',
    name: 'Sovereign Fund Corruption Scandal',
    description: 'Investigations reveal billions siphoned from state investment vehicles through fictitious transactions, ghost bond issuances, and the complicity of international banks. A reckoning is unavoidable. Choose: stonewalling and denial, or accountability and reform.',
    durationMonths: 24,
    prerequisiteIds: ['bumi_t3_sovereign_wealth'],
    requirements: {
      description: 'Triggered when corruption rises above 65 after Sovereign Wealth Fund completion.',
      crisisTrigger: { gdpBelow: 0, unemploymentAbove: 0 },
      maxCorruption: 150,
    },
    reward: {
      budgetBonus: -350,
      approvalBonus: -18,
      legacyPoints: -12,
      structuralBonus: { corruptionReduction: 22, inequalityReduction: 0.015 },
      policyUnlock: {
        description: 'Unlocks "Emergency Anti-Corruption Commission" powers',
        unlockedOptions: { spendingLevel: ['anti_corruption_commission'] },
      },
      flavourText: 'The scandal makes international headlines. The ringgit falls. Bond spreads widen. But forced transparency creates conditions for the institutional reform that political patronage had prevented for decades.',
      historicalNote: '1MDB (2009-2015): US$4.5 billion allegedly misappropriated. The scandal involved Goldman Sachs, Abu Dhabi sovereign funds, and Hollywood productions. It brought down the Najib government in 2018 and became a global case study in kleptocracy.',
    },
  },

  {
    id: 'bumi_t5_racial_harmony_act',
    treeId: 'bumiputera_agenda',
    tier: 5,
    category: 'social',
    icon: '🤲',
    name: 'Racial Harmony and National Unity Act',
    description: 'Replace the Sedition Act and Official Secrets Act with a balanced Racial Harmony Act: criminalising incitement to racial hatred while protecting free speech, creating a National Harmony Council with investigative and mediation powers.',
    durationMonths: 28,
    prerequisiteIds: ['bumi_t5_malaysia_baru'],
    requirements: {
      description: 'Reform mandate and clean governance.',
      maxCorruption: 30,
      minApproval: 55,
      minHumanCapital: 58,
    },
    reward: {
      approvalBonus: 12,
      legacyPoints: 18,
      populationGrowthBonuses: [{ ethnicity: 'all', bonus: 0.0009 }],
      structuralBonus: { corruptionReduction: 8, humanCapitalBoost: 7, inequalityReduction: -0.022 },
      flavourText: 'The Sedition Act, used for decades to silence dissent, is repealed. Politicians of all races discover they must now argue their positions rather than invoke their legal privileges. Most adapt. Some do not.',
    },
  },
];

export { BUMIPUTERA_MISSIONS };
